using DriveIndexer.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DriveIndexer.Database
{
    public class DefaultFileTypesGame
    {
        public static List<FileTypeData> AllKnownTypes()
        {
            List<FileTypeData> fileTypes = new List<FileTypeData>();
            fileTypes.Add(new FileTypeData(".lrf", "League of Legends Replay File"));
            fileTypes.Add(new FileTypeData(".sims3pack", "The Sims 3 Package File"));
            fileTypes.Add(new FileTypeData(".p3t", "PlayStation 3 Theme File"));
            fileTypes.Add(new FileTypeData(".rep", "Grand Theft Auto Replay File"));
            fileTypes.Add(new FileTypeData(".vpk", "Valve Pak"));
            fileTypes.Add(new FileTypeData(".rgss3a", "RPG Maker VX Ace RGSS Encrypted Archive"));
            fileTypes.Add(new FileTypeData(".wad", "Doom WAD File"));
            fileTypes.Add(new FileTypeData(".schematic", "MCEdit Schematic File"));
            fileTypes.Add(new FileTypeData(".pxp", "Counter-Strike PODBot Experience File"));
            fileTypes.Add(new FileTypeData(".wrpl", "Widelands Saved Game File"));
            fileTypes.Add(new FileTypeData(".sc2save", "Blizzard StarCraft 2 Saved Game"));
            fileTypes.Add(new FileTypeData(".pk6", "Generation 6 Pokémon Save File"));
            fileTypes.Add(new FileTypeData(".forge", "Assassin's Creed Game Data File"));
            fileTypes.Add(new FileTypeData(".pss", "PlayStation 2 Game Video File"));
            fileTypes.Add(new FileTypeData(".sc4", "SimCity 4 Saved File"));
            fileTypes.Add(new FileTypeData(".ttarch", "Telltale Games Archive"));
            fileTypes.Add(new FileTypeData(".bsp", "Quake Engine Game Map File"));
            fileTypes.Add(new FileTypeData(".w3n", "Warcraft 3 Expansion Campaign File"));
            fileTypes.Add(new FileTypeData(".rbxl", "ROBLOX Location File"));
            fileTypes.Add(new FileTypeData(".tor", "Star Wars: The Old Republic Asset File"));
            fileTypes.Add(new FileTypeData(".d3dbsp", "Call of Duty Map File"));
            fileTypes.Add(new FileTypeData(".gbx", "Nadeo Game File"));
            fileTypes.Add(new FileTypeData(".pcc", "Mass Effect Package"));
            fileTypes.Add(new FileTypeData(".sc2replay", "Blizzard StarCraft 2 Replay File"));
            fileTypes.Add(new FileTypeData(".sm", "StepMania Song File"));
            fileTypes.Add(new FileTypeData(".sqf", "ArmA Script File"));
            fileTypes.Add(new FileTypeData(".wz", "MapleStory Game Data File"));
            fileTypes.Add(new FileTypeData(".aao", "America's Army Map File"));
            fileTypes.Add(new FileTypeData(".bfs", "FlatOut Game Data File"));
            fileTypes.Add(new FileTypeData(".galaxy", "Blizzard Galaxy File"));
            fileTypes.Add(new FileTypeData(".m2", "World or Warcraft Model Object"));
            fileTypes.Add(new FileTypeData(".mas", "rFactor Track File"));
            fileTypes.Add(new FileTypeData(".n3pmesh", "Knight Online 3D Mesh File"));
            fileTypes.Add(new FileTypeData(".pwf", "Counter-Strike PODBot Waypoint File"));
            fileTypes.Add(new FileTypeData(".sfar", "Mass Effect 3 DLC File"));
            fileTypes.Add(new FileTypeData(".dat_mcr", "Minecraft Level.dat Backup File"));
            fileTypes.Add(new FileTypeData(".diva", "Project DIVA Song File"));
            fileTypes.Add(new FileTypeData(".properties", "Minecraft Properties File"));
            fileTypes.Add(new FileTypeData(".osz", "Osu! Beatmap File"));
            fileTypes.Add(new FileTypeData(".blp", "Blizzard Texture File"));
            fileTypes.Add(new FileTypeData(".sami", "Grand Theft Auto San Andres Mod Installer File"));
            fileTypes.Add(new FileTypeData(".mcmeta", "Minecraft Animation File"));
            fileTypes.Add(new FileTypeData(".package", "Electronic Arts Game Package File"));
            fileTypes.Add(new FileTypeData(".ct", "Cheat Engine Cheat Table"));
            fileTypes.Add(new FileTypeData(".unity", "Unity Scene File"));
            fileTypes.Add(new FileTypeData(".game", "Apple Chess Saved Game"));
            fileTypes.Add(new FileTypeData(".ydr", "Yu-Gi-Oh! Power of Chaos Replay File"));
            fileTypes.Add(new FileTypeData(".w3m", "Warcraft 3 Map File"));
            fileTypes.Add(new FileTypeData(".b", "Grand Theft Auto 3 Saved Game File"));
            fileTypes.Add(new FileTypeData(".unity3d", "Unity Web Player File"));
            fileTypes.Add(new FileTypeData(".xbe", "Xbox Executable File"));
            fileTypes.Add(new FileTypeData(".h2o", "Battle Realms Game Data File"));
            fileTypes.Add(new FileTypeData(".scs", "SimCity Societies Saved Game File"));
            fileTypes.Add(new FileTypeData(".vtf", "Valve Texture File"));
            fileTypes.Add(new FileTypeData(".mcr", "Minecraft Region File"));
            fileTypes.Add(new FileTypeData(".gam", "Saved Game File"));
            fileTypes.Add(new FileTypeData(".mrs", "GunZ Game Data File"));
            fileTypes.Add(new FileTypeData(".ukx", "Unreal Animation Package"));
            fileTypes.Add(new FileTypeData(".p2s", "PCSX2 Saved State"));
            fileTypes.Add(new FileTypeData(".pb2map", "Plazma Burst 2 Custom Map file"));
            fileTypes.Add(new FileTypeData(".w3x", "Warcraft 3 Expansion Map FIle"));
            fileTypes.Add(new FileTypeData(".dem", "Video Game Demo File"));
            fileTypes.Add(new FileTypeData(".cmd", "M.U.G.E.N. Character Commands File"));
            fileTypes.Add(new FileTypeData(".sfo", "PSP Game Parameters File"));
            fileTypes.Add(new FileTypeData(".plr", "Terraria Player File"));
            fileTypes.Add(new FileTypeData(".cpk", "CRI Middleware Package"));
            fileTypes.Add(new FileTypeData(".fpop", "Spider-Man: Shattered Dimensions Saved Game"));
            fileTypes.Add(new FileTypeData(".grf", "Ragnarok Client Archive"));
            fileTypes.Add(new FileTypeData(".mf", "Gameplay Multifile"));
            fileTypes.Add(new FileTypeData(".litemod", "Minecraft LiteLoader Mod File"));
            fileTypes.Add(new FileTypeData(".pk3", "Quake 3 Engine Game Data File"));
            fileTypes.Add(new FileTypeData(".upk", "Unreal Engine 3 Package"));
            fileTypes.Add(new FileTypeData(".ain", "Source Engine Compiled AI Nodegraph File"));
            fileTypes.Add(new FileTypeData(".bus", "OMSI Bus Configuration File"));
            fileTypes.Add(new FileTypeData(".dazip", "Dragon Age: Origins Game File"));
            fileTypes.Add(new FileTypeData(".honmod", "HON Modification Manager File"));
            fileTypes.Add(new FileTypeData(".mp2m", "Max Payne 2 Mod File"));
            fileTypes.Add(new FileTypeData(".osk", "Osu! Skin File"));
            fileTypes.Add(new FileTypeData(".scm", "CLEO Compiled Script"));
            fileTypes.Add(new FileTypeData(".ydc", "Yu-Gi-Oh! Card Deck File"));
            fileTypes.Add(new FileTypeData(".z2f", "Zoo Tycoon 2 Object File"));
            fileTypes.Add(new FileTypeData(".zs9", "ZSNES Slot 9 Saved State File"));
            fileTypes.Add(new FileTypeData(".pak", "Video Game Package"));
            fileTypes.Add(new FileTypeData(".wotreplay", "World of Tanks Replay File"));
            fileTypes.Add(new FileTypeData(".naz", "Total Overdose Game Data File"));
            fileTypes.Add(new FileTypeData(".wtd", "Grand Theft Auto IV Textures File"));
            fileTypes.Add(new FileTypeData(".smd", "Sega Mega Drive ROM"));
            fileTypes.Add(new FileTypeData(".viv", "Need for Speed Car Data File"));
            fileTypes.Add(new FileTypeData(".steamstart", "Valve Steam Start File"));
            fileTypes.Add(new FileTypeData(".ff", "Call of Duty 4 Fast File"));
            fileTypes.Add(new FileTypeData(".wtf", "World of Warcraft Text File"));
            fileTypes.Add(new FileTypeData(".s2z", "Heroes of Newerth Game Data File"));
            fileTypes.Add(new FileTypeData(".ltx", "S.T.A.L.K.E.R. Properties File"));
            fileTypes.Add(new FileTypeData(".sff", "M.U.G.E.N. Sprite File"));
            fileTypes.Add(new FileTypeData(".rez", "Lithtech Game Engine Resource File"));
            fileTypes.Add(new FileTypeData(".esm", "Elder Scrolls Master File"));
            fileTypes.Add(new FileTypeData(".udk", "Unreal Engine Map File"));
            fileTypes.Add(new FileTypeData(".gsc", "Call of Duty Game Script"));
            fileTypes.Add(new FileTypeData(".mis", "Marble Blast Gold Mission File"));
            fileTypes.Add(new FileTypeData(".rvproj2", "RPG Maker VX Ace Project File"));
            fileTypes.Add(new FileTypeData(".spb", "Flight Simulator Mission File"));
            fileTypes.Add(new FileTypeData(".xpd", "PlayStation Store PSP License File"));
            fileTypes.Add(new FileTypeData(".agx", "AGT Game File"));
            fileTypes.Add(new FileTypeData(".rasunsoft", "Rasunsoft Game Replay File"));
            fileTypes.Add(new FileTypeData(".ros", "BattleScribe Roster Editor File"));
            fileTypes.Add(new FileTypeData(".sve", "Simutrans Saved Game"));
            fileTypes.Add(new FileTypeData(".kodu", "Kodu Game File"));
            fileTypes.Add(new FileTypeData(".sav", "Nintendo DS Save File"));
            fileTypes.Add(new FileTypeData(".par", "FMS Aircraft Parameters File"));
            fileTypes.Add(new FileTypeData(".xpk", "WWE RAW Model File"));
            fileTypes.Add(new FileTypeData(".sims2pack", "Downloaded Sims 2 Package File"));
            fileTypes.Add(new FileTypeData(".pnach", "PCSX2 Patch File"));
            fileTypes.Add(new FileTypeData(".i3pack", "Point Blank Game Data File"));
            fileTypes.Add(new FileTypeData(".mpq", "Blizzard Mo'PaQ File"));
            fileTypes.Add(new FileTypeData(".asset", "Unity Asset File"));
            fileTypes.Add(new FileTypeData(".sii", "18 Wheels of Steel: Haulin' Truck Definition File"));
            fileTypes.Add(new FileTypeData(".mca", "Minecraft Anvil Map File"));
            fileTypes.Add(new FileTypeData(".mp2s", "Max Payne 2 Saved Game"));
            fileTypes.Add(new FileTypeData(".rpf", "Grand Theft Auto Data File"));
            fileTypes.Add(new FileTypeData(".sub", "SubTerra Level File"));
            fileTypes.Add(new FileTypeData(".sims3", "The Sims 3 Game Save File"));
            fileTypes.Add(new FileTypeData(".sgm", "VisualBoyAdvance Saved Game"));
            fileTypes.Add(new FileTypeData(".cfr", "Cross Fire Replay File"));
            fileTypes.Add(new FileTypeData(".bar", "Age of Empires 3 Data File"));
            fileTypes.Add(new FileTypeData(".xp3", "KiriKiri Package File"));
            fileTypes.Add(new FileTypeData(".mpk", "Project64 Memory Pack File"));
            fileTypes.Add(new FileTypeData("0	The", "Ur-Quan Masters Saved Game Slot 0 File"));
            fileTypes.Add(new FileTypeData(".esp", "Fallout 3 Plugin File"));
            fileTypes.Add(new FileTypeData(".esp", "Elder Scrolls Plugin File"));
            fileTypes.Add(new FileTypeData(".mine", "Minecraft Map File"));
            fileTypes.Add(new FileTypeData(".mix", "Command & Conquer Data File"));
            fileTypes.Add(new FileTypeData(".lang", "Minecraft Language File"));
            fileTypes.Add(new FileTypeData(".pkg", "PlayStation Store Downloaded Package"));
            fileTypes.Add(new FileTypeData(".bsa", "Bethesda Softworks Archive"));
            fileTypes.Add(new FileTypeData(".cs", "CLEO Custom Script"));
            fileTypes.Add(new FileTypeData(".vdf", "Valve Data File"));
            fileTypes.Add(new FileTypeData(".ifp", "GTA Animation File"));
            fileTypes.Add(new FileTypeData(".w3g", "Warcraft 3 Replay File"));
            fileTypes.Add(new FileTypeData(".ps2", "PCSX2 Memory Card File"));
            fileTypes.Add(new FileTypeData(".pbp", "PSP Firmware Update File"));
            fileTypes.Add(new FileTypeData(".big", "Electronic Arts Game Data File"));
            fileTypes.Add(new FileTypeData(".bms", "BeatMania Song File"));
            fileTypes.Add(new FileTypeData(".bzw", "BZFlag World File"));
            fileTypes.Add(new FileTypeData(".crp", "Cities: Skylines Colossal Raw Asset Package"));
            fileTypes.Add(new FileTypeData(".dek", "Magic: The Gathering Deck File"));
            fileTypes.Add(new FileTypeData(".masseffectsave", "Mass Effect Saved Game"));
            fileTypes.Add(new FileTypeData(".mdl", "Half-Life Model File"));
            fileTypes.Add(new FileTypeData(".pcsav", "Mass Effect 2 Saved Game"));
            fileTypes.Add(new FileTypeData(".sc2assets", "Blizzard StarCraft 2 Assets File"));
            fileTypes.Add(new FileTypeData(".sc2map", "Blizzard StarCraft 2 Map File"));
            fileTypes.Add(new FileTypeData(".sc2mod", "Blizzard StarCraft 2 Modification File"));
            fileTypes.Add(new FileTypeData(".acf", "Steam Application Cache File"));
            fileTypes.Add(new FileTypeData(".adt", "World of Warcraft Map File"));
            fileTypes.Add(new FileTypeData(".age3rec", "Age of Empires 3 Recording"));
            fileTypes.Add(new FileTypeData(".age3sav", "Age of Empires 3 Save File"));
            fileTypes.Add(new FileTypeData(".am1", "Adventure Maker"));
            fileTypes.Add(new FileTypeData(".arp", "Audition Replay File"));
            fileTypes.Add(new FileTypeData(".bmd", "MU Online Game Data File"));
            fileTypes.Add(new FileTypeData(".bns", "Portal Bonus Map Script"));
            fileTypes.Add(new FileTypeData(".cbh", "ChessBase Database Header File"));
            fileTypes.Add(new FileTypeData(".cdp", "Trainz Simulator Content Dispatcher Pack"));
            fileTypes.Add(new FileTypeData(".cgz", "Cube Map File"));
            fileTypes.Add(new FileTypeData(".compiled", "Compiled Game Resource File"));
            fileTypes.Add(new FileTypeData(".fgd", "Forge Game Data File"));
            fileTypes.Add(new FileTypeData(".fl", "Freelancer Saved Game File"));
            fileTypes.Add(new FileTypeData(".fml", "WWE RAW Character File"));
            fileTypes.Add(new FileTypeData(".fomod", "Fallout Mod Archive"));
            fileTypes.Add(new FileTypeData(".gmres", "Game Maker Resource File"));
            fileTypes.Add(new FileTypeData(".gr2", "Granny 3D File"));
            fileTypes.Add(new FileTypeData(".h4r", "Heroes of Might and Magic IV Data File"));
            fileTypes.Add(new FileTypeData(".hot", "The Sims Sound File"));
            fileTypes.Add(new FileTypeData(".lvl", "Game Level File"));
            fileTypes.Add(new FileTypeData(".mgx", "Rise of Nations Saved Game"));
            fileTypes.Add(new FileTypeData(".npa", "Steins;Gate Archive"));
            fileTypes.Add(new FileTypeData(".pk4", "Doom 3 Engine Game Data File"));
            fileTypes.Add(new FileTypeData(".pqhero", "Puzzle Quest Saved Game"));
            fileTypes.Add(new FileTypeData(".prk", "Thrillville Park File"));
            fileTypes.Add(new FileTypeData(".pssg", "EGO Engine Textures File"));
            fileTypes.Add(new FileTypeData(".psv", "PlayStation 2 Save File"));
            fileTypes.Add(new FileTypeData(".raw", "Dolphin Wii and Gamecube Emulator Game Save File"));
            fileTypes.Add(new FileTypeData(".rep", "StarCraft Replay File"));
            fileTypes.Add(new FileTypeData(".rvdata", "RPG Maker VX Data File"));
            fileTypes.Add(new FileTypeData(".sc2archive", "Blizzard StarCraft 2 Archive File"));
            fileTypes.Add(new FileTypeData(".sc4lot", "SimCity 4 Lot File"));
            fileTypes.Add(new FileTypeData(".sga", "Relic Entertainment Game Archive"));
            fileTypes.Add(new FileTypeData(".sli", "OMSI Spline Configuration File"));
            fileTypes.Add(new FileTypeData(".sta", "MAME Saved State File"));
            fileTypes.Add(new FileTypeData(".svs", "Game Boy Advance Saved State File"));
            fileTypes.Add(new FileTypeData(".tim", "The Incredible Machine Level"));
            fileTypes.Add(new FileTypeData(".uc", "UnrealScript Class"));
            fileTypes.Add(new FileTypeData(".umd", "Splinter Cell Blacklist Game Data File"));
            fileTypes.Add(new FileTypeData(".umx", "Unreal Music Package"));
            fileTypes.Add(new FileTypeData(".unr", "Unreal Level Map"));
            fileTypes.Add(new FileTypeData(".usa", "Unreal Saved Game File"));
            fileTypes.Add(new FileTypeData(".usx", "Unreal Static Meshes"));
            fileTypes.Add(new FileTypeData(".vmf", "Valve Map File"));
            fileTypes.Add(new FileTypeData(".xen", "Guitar Hero III Data File"));
            fileTypes.Add(new FileTypeData(".ydk", "Yu-Gi-Oh! Deck File"));
            fileTypes.Add(new FileTypeData(".z3", "Z-machine Z-code File"));
            fileTypes.Add(new FileTypeData(".z4", "Z-machine Z-code File"));
            fileTypes.Add(new FileTypeData(".z5", "Z-machine Z-code File"));
            fileTypes.Add(new FileTypeData(".zs7", "ZSNES Slot 7 Saved State File"));
            fileTypes.Add(new FileTypeData(".ztmp", "Steam Compressed Game Resource File"));
            fileTypes.Add(new FileTypeData(".abk", "Arena Opening Book File"));
            fileTypes.Add(new FileTypeData(".arc", "African Safari Data File"));
            fileTypes.Add(new FileTypeData(".", "$$	AGT Game Encrypted Message File"));
            fileTypes.Add(new FileTypeData(".ekx", "Encrypted 3DS Pokémon Save File"));
            fileTypes.Add(new FileTypeData(".ftl", "Faster Than Light Mod File"));
            fileTypes.Add(new FileTypeData(".fxt", "Grand Theft Auto Fake Text File"));
            fileTypes.Add(new FileTypeData(".ide", "GTA Item Definition File"));
            fileTypes.Add(new FileTypeData(".mcgame", "Minecraft Game Backup File"));
            fileTypes.Add(new FileTypeData(".nav", "Id Tech 3 Bot Navigation File"));
            fileTypes.Add(new FileTypeData(".ogz", "Cube 2 Map File"));
            fileTypes.Add(new FileTypeData(".pak", "Simutrans Object File"));
            fileTypes.Add(new FileTypeData(".pbo", "Packed Bohemia Object"));
            fileTypes.Add(new FileTypeData(".phz", "Algodoo Phun Compressed Phunlet"));
            fileTypes.Add(new FileTypeData(".qvm", "Quake 3 Virtual Machine File"));
            fileTypes.Add(new FileTypeData(".sfb", "PlayStation 3 Disc Data File"));
            fileTypes.Add(new FileTypeData(".sims", ".backup	The Sims 3 Game Save Backup File"));
            fileTypes.Add(new FileTypeData(".vp", "Volition Package File"));
            fileTypes.Add(new FileTypeData(".wpl", "GTA Binary Item Placement File"));
            fileTypes.Add(new FileTypeData("0", "555	Black & White Weather Settings File"));
            fileTypes.Add(new FileTypeData(".8ld", "Overlord 2 Language File"));
            fileTypes.Add(new FileTypeData(".bmg", "Nintendo DS On-Screen Text File"));
            fileTypes.Add(new FileTypeData(".cbs", "Code Breaker PS2 Save File"));
            fileTypes.Add(new FileTypeData(".enc", "Cabal Online Data File"));
            fileTypes.Add(new FileTypeData(".sgr", "SimCity 4 Graphics Rules File"));
            fileTypes.Add(new FileTypeData(".viv", "PlayStation Video File"));
            fileTypes.Add(new FileTypeData(".dat", "Minecraft Data File"));
            fileTypes.Add(new FileTypeData(".bin", "Sega Genesis Game ROM"));
            fileTypes.Add(new FileTypeData(".pck", "Perfect World Data File"));
            fileTypes.Add(new FileTypeData(".bin", "Atari 2600 Game ROM"));
            fileTypes.Add(new FileTypeData(".sid", "Steam Game Data Backup File"));
            fileTypes.Add(new FileTypeData(".sav", "Saved Game"));
            fileTypes.Add(new FileTypeData(".game", "GameSalad Exported Game File"));
            fileTypes.Add(new FileTypeData(".papa", "Game Save Backup File"));
            fileTypes.Add(new FileTypeData(".chk", "StarCraft Chunk File"));
            fileTypes.Add(new FileTypeData(".gma", "Garry's Mod Addon File"));
            fileTypes.Add(new FileTypeData(".arch00", "F.E.A.R. Game Archive"));
            fileTypes.Add(new FileTypeData(".ess", "The Elder Scrolls Saved Game"));
            fileTypes.Add(new FileTypeData(".ldw", "Virtual Villagers Saved Game File"));
            fileTypes.Add(new FileTypeData(".scx", "Microsoft Game Scenario File"));
            fileTypes.Add(new FileTypeData(".srm", "Super Nintendo ROM Save File"));
            fileTypes.Add(new FileTypeData(".bfg", "Big Fish Games Application File"));
            fileTypes.Add(new FileTypeData(".scs", "Prism3D Game Data File"));
            fileTypes.Add(new FileTypeData(".map", "Quake Engine Map File"));
            fileTypes.Add(new FileTypeData("0", "001	Snes9x Slot 2 Saved State"));
            fileTypes.Add(new FileTypeData(".cbv", "ChessBase Database File"));
            fileTypes.Add(new FileTypeData(".wz", "Warzone 2100 Data File"));
            fileTypes.Add(new FileTypeData(".kv6", "Ace of Spades Model File"));
            fileTypes.Add(new FileTypeData(".ras", "Remedy Archive System File"));
            fileTypes.Add(new FileTypeData(".iwd", "Call of Duty Game Data File"));
            fileTypes.Add(new FileTypeData(".ssfsav", "Super Smash Flash Saved Game File"));
            fileTypes.Add(new FileTypeData(".ipl", "GTA Item Placement File"));
            fileTypes.Add(new FileTypeData(".mpm", "Max Payne Modfication File"));
            fileTypes.Add(new FileTypeData(".rbxm", "ROBLOX Model"));
            fileTypes.Add(new FileTypeData(".u", "Unreal Tournament Class Package"));
            fileTypes.Add(new FileTypeData(".dat_old", "Minecraft Level.dat Backup File"));
            fileTypes.Add(new FileTypeData(".gme", "DexDrive Game Card File"));
            fileTypes.Add(new FileTypeData(".rfa", "Battlefield 1942 Game Package"));
            fileTypes.Add(new FileTypeData(".purblepairssav", "-ms	Purble Pairs Saved Game"));
            fileTypes.Add(new FileTypeData(".scene", "Antibody Level File"));
            fileTypes.Add(new FileTypeData(".spo", "Spore Saved Game"));
            fileTypes.Add(new FileTypeData(".sav", "Mass Effect 3 Saved Game"));
            fileTypes.Add(new FileTypeData(".craft", "KSP Spacecraft File"));
            fileTypes.Add(new FileTypeData(".xex", "Xbox 360 Executable File"));
            fileTypes.Add(new FileTypeData(".epk", "Metin2 Game Data Package"));
            fileTypes.Add(new FileTypeData(".db", "X-Ray Engine Database"));
            fileTypes.Add(new FileTypeData(".narc", "Nintendo DS Archive File"));
            fileTypes.Add(new FileTypeData(".osr", "Osu! Replay File"));
            fileTypes.Add(new FileTypeData(".abk", "Need for Speed Underground Audio File"));
            fileTypes.Add(new FileTypeData(".grp", "StarCraft Graphics Group File"));
            fileTypes.Add(new FileTypeData(".jag", "Jagex Data File"));
            fileTypes.Add(new FileTypeData(".map", "Furcadia Dream File"));
            fileTypes.Add(new FileTypeData(".rel", "Relocatable Module File"));
            fileTypes.Add(new FileTypeData(".crysisjmsf", "Crysis Saved Game"));
            fileTypes.Add(new FileTypeData(".ecl", "Touhou Stage Script"));
            fileTypes.Add(new FileTypeData(".flash", "Frictional Games Flashback File"));
            fileTypes.Add(new FileTypeData(".nam", "G.E.C.K. Mod Data File"));
            fileTypes.Add(new FileTypeData(".sc4", "RollerCoaster Tycoon Scenario File"));
            fileTypes.Add(new FileTypeData("0	M3", "DS Real Save File"));
            fileTypes.Add(new FileTypeData(".wa2", "Wonderland Adventures Custom Adventure File"));
            fileTypes.Add(new FileTypeData(".map", "Halo Map File"));
            fileTypes.Add(new FileTypeData(".pgn", "Portable Game Notation File"));
            fileTypes.Add(new FileTypeData(".ips", "Internal Patching System Patch File"));
            fileTypes.Add(new FileTypeData(".wbfs", "Wii Backup File System File"));
            fileTypes.Add(new FileTypeData(".bin", "PCSX PlayStation BIOS Image"));
            fileTypes.Add(new FileTypeData(".bix", "Civilization 3 Scenario File"));
            fileTypes.Add(new FileTypeData(".pk3", "ZDoom Package"));
            fileTypes.Add(new FileTypeData(".rpy", "Touhou Project Replay File"));
            fileTypes.Add(new FileTypeData(".dz", "Land of the Dead Level File"));
            fileTypes.Add(new FileTypeData(".pkm", "Pokémon Saved Game Data File"));
            fileTypes.Add(new FileTypeData(".bgl", "Flight Simulator Scenery File"));
            fileTypes.Add(new FileTypeData(".dat", "SimCity 4 Game Data File"));
            fileTypes.Add(new FileTypeData(".chd", "MAME Hard Disk Image"));
            fileTypes.Add(new FileTypeData(".acww", "Animal Crossing Wild World Pattern File"));
            fileTypes.Add(new FileTypeData(".age3scn", "Age of Empires 3 Scenario File"));
            fileTypes.Add(new FileTypeData(".bls", "Blockland Saved Game File"));
            fileTypes.Add(new FileTypeData(".cty", "SimCity City File"));
            fileTypes.Add(new FileTypeData(".ddt", "Football Manager Keep Player Data File"));
            fileTypes.Add(new FileTypeData(".fcs", "FCEUX Save State File"));
            fileTypes.Add(new FileTypeData(".fssave", "Flight Simulator Save File"));
            fileTypes.Add(new FileTypeData(".hum", "OMSI Human Configuration File"));
            fileTypes.Add(new FileTypeData(".lsd", "RPG Maker Game Save File"));
            fileTypes.Add(new FileTypeData(".mae", "My Avatar Editor Character File"));
            fileTypes.Add(new FileTypeData(".mis", "Saved Game Mission File"));
            fileTypes.Add(new FileTypeData(".rpl", "Toribash Replay File"));
            fileTypes.Add(new FileTypeData(".rvproj", "RPG Maker VX Project File"));
            fileTypes.Add(new FileTypeData(".rxdata", "RMXP Data File"));
            fileTypes.Add(new FileTypeData(".swc", "Super Nintendo Wild Card ROM File"));
            fileTypes.Add(new FileTypeData(".twt", "Carmageddon 2 Data File"));
            fileTypes.Add(new FileTypeData(".ut4mod", "Unreal Tournament 2004 Module"));
            fileTypes.Add(new FileTypeData(".w3z", "Warcraft 3 Saved Game File"));
            fileTypes.Add(new FileTypeData(".wad", "Nintendo Wii Game Data File"));
            fileTypes.Add(new FileTypeData(".wld", "Terraria World File"));
            fileTypes.Add(new FileTypeData(".ycm", "Yugioh Card Maker File"));
            fileTypes.Add(new FileTypeData(".zs0", "ZSNES Slot 0 Saved State File"));
            fileTypes.Add(new FileTypeData(".asstrm", "Splinter Cell Blacklist Game Data File"));
            fileTypes.Add(new FileTypeData(".biq", "Civilization 3 Scenario File"));
            fileTypes.Add(new FileTypeData(".civ5mod", "Civilization 5 Mod File"));
            fileTypes.Add(new FileTypeData(".civ5save", "Civilization 5 Saved Game"));
            fileTypes.Add(new FileTypeData(".con", "Battlefield 1942 Configuration File"));
            fileTypes.Add(new FileTypeData(".cps", "The Powder Toy Save File"));
            fileTypes.Add(new FileTypeData(".d2s", "Diablo 2 Save File"));
            fileTypes.Add(new FileTypeData(".da1", "AGT Game Data File"));
            fileTypes.Add(new FileTypeData(".dpf", "Dargon Package"));
            fileTypes.Add(new FileTypeData(".elm", "Eternal Lands Map File"));
            fileTypes.Add(new FileTypeData(".exs", "Blades of Exile Scenario"));
            fileTypes.Add(new FileTypeData(".gar", "Farming Simulator Game Archive File"));
            fileTypes.Add(new FileTypeData(".gci", "GameCube Save File"));
            fileTypes.Add(new FileTypeData(".gla", "Ghoul 2 Animation File"));
            fileTypes.Add(new FileTypeData(".gs0", "Sega Genesis Emulator Quick Slot 0 Save File"));
            fileTypes.Add(new FileTypeData(".ham", "Descent 2 Resource File"));
            fileTypes.Add(new FileTypeData(".jkb", "Jedi Knight Bot File"));
            fileTypes.Add(new FileTypeData(".loc", "TrackMania Locator File"));
            fileTypes.Add(new FileTypeData(".map", "Fallout Map File"));
            fileTypes.Add(new FileTypeData(".max", "Action Replay Max Save File"));
            fileTypes.Add(new FileTypeData(".mcr", "ePSXe Memory Card File"));
            fileTypes.Add(new FileTypeData(".me2mod", "Mass Effect 2 Modification File"));
            fileTypes.Add(new FileTypeData(".per", "Age of Empires Personality File"));
            fileTypes.Add(new FileTypeData(".pig", "Descent Texture File"));
            fileTypes.Add(new FileTypeData(".profile", "Pandemic Studios Game Player Profile"));
            fileTypes.Add(new FileTypeData(".psdl", "Midtown Madness 2 City File"));
            fileTypes.Add(new FileTypeData(".rfgs_pc", "Red Faction: Guerilla Saved Game File"));
            fileTypes.Add(new FileTypeData(".rpyc", "Ren'Py Compiled Script"));
            fileTypes.Add(new FileTypeData(".s4m", "SWAT 4 Map File"));
            fileTypes.Add(new FileTypeData(".sc2", "SimCity 2000 City File"));
            fileTypes.Add(new FileTypeData(".sc3", "SimCity 3000 City File"));
            fileTypes.Add(new FileTypeData(".scm", "StarCraft Map File"));
            fileTypes.Add(new FileTypeData(".sh2", "Stronghold 2 Saved Game"));
            fileTypes.Add(new FileTypeData(".tlk", "BioWare Aurora Engine Talk Table File"));
            fileTypes.Add(new FileTypeData(".vvvvvv", "VVVVVV Game Level File"));
            fileTypes.Add(new FileTypeData(".wl6", "Wolfenstein 3D Data File"));
            fileTypes.Add(new FileTypeData(".wpm", "Warcraft 3 Path Map File"));
            fileTypes.Add(new FileTypeData(".bus", "VirtualBus Board Parameters File"));
            fileTypes.Add(new FileTypeData(".comfycakessav", "-ms	Comfy Cakes Saved Game"));
            fileTypes.Add(new FileTypeData(".bin", "Nintendo DS Binary File"));
            fileTypes.Add(new FileTypeData(".sav", "Fallout 2 Map Archive"));
            fileTypes.Add(new FileTypeData(".col", "Grand Theft Auto Collision File"));
            fileTypes.Add(new FileTypeData(".zip", "MAME Game ROM"));
            fileTypes.Add(new FileTypeData(".bsb", "BioShock Saved Game File"));
            fileTypes.Add(new FileTypeData(".far", "The Sims Archive File"));
            fileTypes.Add(new FileTypeData(".mahjongtitanssav", "-ms	Mahjong Titans Saved Game"));
            fileTypes.Add(new FileTypeData(".ctm", "Star Wars Republic Commando Map File"));
            fileTypes.Add(new FileTypeData(".fc2map", "Far Cry 2 User Map"));
            fileTypes.Add(new FileTypeData(".zad", "Carmageddon Game Data File"));
            fileTypes.Add(new FileTypeData(".ivt", "International Volleyball 2006 Data File"));
            fileTypes.Add(new FileTypeData(".bik", "Video Game Movie File"));
            fileTypes.Add(new FileTypeData(".masseffectprofile", "Mass Effect Player Profile"));
            fileTypes.Add(new FileTypeData(".rgssad", "RPG Maker VX RGSS Encrypted Archive"));
            fileTypes.Add(new FileTypeData(".wdb", "Blizzard World of Warcraft Database File"));
            fileTypes.Add(new FileTypeData(".xmb", "X-Wing Mission Briefing File"));
            fileTypes.Add(new FileTypeData(".msg", "Fallout Message File"));
            fileTypes.Add(new FileTypeData(".skse", "Skyrim Script Extender Save File"));
            fileTypes.Add(new FileTypeData(".zsd", "Dave Mirra Freestyle BMX Data File"));
            fileTypes.Add(new FileTypeData(".gcf", "Game Cache File"));
            fileTypes.Add(new FileTypeData(".jap", "Nonogram Puzzle File"));
            fileTypes.Add(new FileTypeData(".plr", "rFactor Player File"));
            fileTypes.Add(new FileTypeData(".puz", "Across Lite Crossword Puzzle"));
            fileTypes.Add(new FileTypeData(".sc2bank", "StarCraft 2 Bank File"));
            fileTypes.Add(new FileTypeData(".world", "Terraria Mobile World File"));
            fileTypes.Add(new FileTypeData(".cm", "CLEO Custom Mission"));
            fileTypes.Add(new FileTypeData(".mus", "Electronic Arts Game Music File"));
            fileTypes.Add(new FileTypeData(".rim", "BioWare Resource Image File"));
            fileTypes.Add(new FileTypeData(".scn", "OpenTTD Scenario File"));
            fileTypes.Add(new FileTypeData(".z8", "Z-machine Z-code File"));
            fileTypes.Add(new FileTypeData(".eix", "Metin2 Game Data File"));
            fileTypes.Add(new FileTypeData(".mclevel", "Minecraft Map File"));
            fileTypes.Add(new FileTypeData(".air", "M.U.G.E.N. Animation File"));
            fileTypes.Add(new FileTypeData(".bif", "BioWare Infinity Engine File"));
            fileTypes.Add(new FileTypeData(".dl", "Zoo Tycoon 2 Data File"));
            fileTypes.Add(new FileTypeData(".img", "Grand Theft Auto Data File"));
            fileTypes.Add(new FileTypeData(".cfg", "Wesnoth Markup Language File"));
            fileTypes.Add(new FileTypeData(".cli", "Grand Theft Auto Clip Data File"));
            fileTypes.Add(new FileTypeData(".sdf", "World in Conflict Game Map"));
            fileTypes.Add(new FileTypeData(".dat_new", "Minecraft World Level File"));
            fileTypes.Add(new FileTypeData(".vob", "Live for Speed Car File"));
            fileTypes.Add(new FileTypeData(".utx", "Unreal Texture Package"));
            fileTypes.Add(new FileTypeData(".ldb", "Max Payne Level File"));
            fileTypes.Add(new FileTypeData(".str", "BFME2 Strings File"));
            fileTypes.Add(new FileTypeData(".prx", "PSP Plugin File"));
            fileTypes.Add(new FileTypeData(".xnb", "XNA Game Studio Binary Package"));
            fileTypes.Add(new FileTypeData(".bf", "CryoBF Game Data File"));
            fileTypes.Add(new FileTypeData(".erf", "BioWare Entity Resource File"));
            fileTypes.Add(new FileTypeData(".ssc", "StepMania Song File"));
            fileTypes.Add(new FileTypeData(".age3xrec", "Age of Empires 3: The WarChiefs Recording"));
            fileTypes.Add(new FileTypeData(".age3xsav", "Age of Empires 3: The WarChiefs Save File"));
            fileTypes.Add(new FileTypeData(".age3yrec", "Age of Empires 3: The Asian Dynasties Recording"));
            fileTypes.Add(new FileTypeData(".age3ysav", "Age of Empires 3: The Asian Dynasties Save File"));
            fileTypes.Add(new FileTypeData(".blackhawkstriker2", "Blackhawk Striker 2 Saved Game"));
            fileTypes.Add(new FileTypeData(".blasterball3savedgame", "BlasterBall 3 Saved Game"));
            fileTypes.Add(new FileTypeData(".blz", "N-Gage Mobile Video Game File"));
            fileTypes.Add(new FileTypeData(".bme", "BeatMania 7-Key Song File"));
            fileTypes.Add(new FileTypeData(".bmz", "Portal Bonus Map Zip File"));
            fileTypes.Add(new FileTypeData(".bps", "BPS Patch File"));
            fileTypes.Add(new FileTypeData(".cdp2", "Trainz Classics Content Dispatcher Pack 2"));
            fileTypes.Add(new FileTypeData(".cgf", "Crytek Geometry Format File"));
            fileTypes.Add(new FileTypeData(".cpn", "Age of Mythology Campaign File"));
            fileTypes.Add(new FileTypeData(".dek", "Yugioh Virtual Desktop Deck File"));
            fileTypes.Add(new FileTypeData(".dek", "LackeyCCG Card Deck File"));
            fileTypes.Add(new FileTypeData(".dif", "MAME CHD Diff File"));
            fileTypes.Add(new FileTypeData(".dm2", "Quake 2 Demo File"));
            fileTypes.Add(new FileTypeData(".dmb", "BYOND Game Executable"));
            fileTypes.Add(new FileTypeData(".dmo", "Duke Nukem 3D Demo File"));
            fileTypes.Add(new FileTypeData(".dm_82", "Wolfenstein 1.00 Demo Movie File"));
            fileTypes.Add(new FileTypeData(".dm_83", "Wolfenstein 1.02 Demo Movie File"));
            fileTypes.Add(new FileTypeData(".dns", "Duke Nukem Forever Save File"));
            fileTypes.Add(new FileTypeData(".dsg", "Doom Saved Game"));
            fileTypes.Add(new FileTypeData(".duc", "Action Replay Max DS Save File"));
            fileTypes.Add(new FileTypeData(".dun", "Dungeon Defenders Saved Game File"));
            fileTypes.Add(new FileTypeData(".dv2", "Divinity 2 Data File"));
            fileTypes.Add(new FileTypeData(".egm", "Enigmo Custom Game File"));
            fileTypes.Add(new FileTypeData(".eng", "Chess Engine"));
            fileTypes.Add(new FileTypeData(".erb", "Evil Genius Resource File"));
            fileTypes.Add(new FileTypeData(".esg", "Enigmo Saved Game File"));
            fileTypes.Add(new FileTypeData(".esm", "Fallout 3 Master File"));
            fileTypes.Add(new FileTypeData(".fcm", "fCraft World File"));
            fileTypes.Add(new FileTypeData(".fpg", "FPS Creator Game Project File"));
            fileTypes.Add(new FileTypeData(".fps", "FPS Creator Segment File"));
            fileTypes.Add(new FileTypeData(".frz", "Snes9x Saved State"));
            fileTypes.Add(new FileTypeData(".fs2", "FreeSpace 2 Saved Mission File"));
            fileTypes.Add(new FileTypeData(".g3x", "RealFlight Content File"));
            fileTypes.Add(new FileTypeData(".gbaskin", "Game Boy Advance Controller Skin File"));
            fileTypes.Add(new FileTypeData(".gbcskin", "Game Boy Color Controller Skin File"));
            fileTypes.Add(new FileTypeData(".gdi", "Dreamcast Gigabyte Disc Image"));
            fileTypes.Add(new FileTypeData(".gfx", "GFx Scaleform File"));
            fileTypes.Add(new FileTypeData(".h3m", "Heroes 3 Map File"));
            fileTypes.Add(new FileTypeData(".hps", "HPL Script"));
            fileTypes.Add(new FileTypeData(".ibt", "Texture and Model File"));
            fileTypes.Add(new FileTypeData(".idx0", "Runescape Cache Index File"));
            fileTypes.Add(new FileTypeData(".idx255", "Runescape Cache File"));
            fileTypes.Add(new FileTypeData(".info", "Minecraft Forge Information File"));
            fileTypes.Add(new FileTypeData(".isr", "GoMoku Game File"));
            fileTypes.Add(new FileTypeData(".j2i", "Jazz 2 Internet Link File"));
            fileTypes.Add(new FileTypeData(".j2l", "Jazz Jackrabbit 2 Level File"));
            fileTypes.Add(new FileTypeData(".jg4", "BigJig Jigsaw Puzzle"));
            fileTypes.Add(new FileTypeData(".jst", "Jnes Save State"));
            fileTypes.Add(new FileTypeData(".kwreplay", "Command & Conquer 3 Replay File"));
            fileTypes.Add(new FileTypeData(".lip", "Bethesda Softworks Lip Sync File"));
            fileTypes.Add(new FileTypeData(".lmp", "Quake Engine Lump File"));
            fileTypes.Add(new FileTypeData(".lmu", "RPG Maker Map File"));
            fileTypes.Add(new FileTypeData(".lsw", "RPG Maker Saved Game File"));
            fileTypes.Add(new FileTypeData(".luxb", "Lux Map File"));
            fileTypes.Add(new FileTypeData(".maplet", "Maplet World File"));
            fileTypes.Add(new FileTypeData(".mcserver", "Minecraft Server File"));
            fileTypes.Add(new FileTypeData(".md2", "Quake 2 Player Model"));
            fileTypes.Add(new FileTypeData(".menu", "Quake 3 Engine Menu File"));
            fileTypes.Add(new FileTypeData(".mgl", "Age of Empires 2 Replay File"));
            fileTypes.Add(new FileTypeData(".mgx", "Age of Empires 2 Expansion Replay File"));
            fileTypes.Add(new FileTypeData(".mii", "Wii Virtual Avatar File"));
            fileTypes.Add(new FileTypeData(".minesweepersav", "-ms	Minesweeper Saved Game"));
            fileTypes.Add(new FileTypeData(".mul", "Ultima Online Multi File"));
            fileTypes.Add(new FileTypeData(".nar", "Nexon game archive"));
            fileTypes.Add(new FileTypeData(".ncf", "No Cache File"));
            fileTypes.Add(new FileTypeData(".ngage", "N-Gage Game File"));
            fileTypes.Add(new FileTypeData(".nltrack", "NoLimits Roller Coaster Track File"));
            fileTypes.Add(new FileTypeData(".ns1", "Nestopia Save State"));
            fileTypes.Add(new FileTypeData(".nsbca", "Nintendo DS Model Animation File"));
            fileTypes.Add(new FileTypeData(".nsbmd", "Nintendo DS Model File"));
            fileTypes.Add(new FileTypeData(".ntrk", "Pacific FIghters Online Track File"));
            fileTypes.Add(new FileTypeData(".omod", "Oblivion Mod Archive"));
            fileTypes.Add(new FileTypeData(".ovh", "OMSI Vehicle Configuration File"));
            fileTypes.Add(new FileTypeData(".phn", "Algodoo Phun Phunlet"));
            fileTypes.Add(new FileTypeData(".pkx", "Decrypted 3DS Pokémon Save File"));
            fileTypes.Add(new FileTypeData(".player", "Terraria Mobile Player File"));
            fileTypes.Add(new FileTypeData(".playmission", "MissionPlayer Game File"));
            fileTypes.Add(new FileTypeData(".pln", "Flight Simulator Flight Plan"));
            fileTypes.Add(new FileTypeData(".qwd", "QuakeWorld Demo File"));
            fileTypes.Add(new FileTypeData(".radq", "Need for Madness Game Archive"));
            fileTypes.Add(new FileTypeData(".rfm", "rFactor Modification File"));
            fileTypes.Add(new FileTypeData(".rvdata2", "RPG Maker VX Ace Data File"));
            fileTypes.Add(new FileTypeData(".sad", "Black & White Audio File"));
            fileTypes.Add(new FileTypeData(".sc2data", "Blizzard StarCraft 2 Data File"));
            fileTypes.Add(new FileTypeData(".sc2ma", "StarCraft 2 Map Data File"));
            fileTypes.Add(new FileTypeData(".sc4desc", "SimCity 4 Description File"));
            fileTypes.Add(new FileTypeData(".scx", "Game Scenario File"));
            fileTypes.Add(new FileTypeData(".sd7", "Spring Content Package"));
            fileTypes.Add(new FileTypeData(".sdt", "Grand Theft Auto 3 Audio File"));
            fileTypes.Add(new FileTypeData(".sdz", "Spring Content Package"));
            fileTypes.Add(new FileTypeData(".sg0", "Humongous Entertainment Game Save File"));
            fileTypes.Add(new FileTypeData(".sgb", "Dawn of War Map File"));
            fileTypes.Add(new FileTypeData(".sgpbprj", "Baltie Project"));
            fileTypes.Add(new FileTypeData(".smrailroadssavedgame", "Sid Meier's Railroads! Saved Game"));
            fileTypes.Add(new FileTypeData(".splane", "Simple Planes Plane File"));
            fileTypes.Add(new FileTypeData(".sprite", "SuperTux Sprite File"));
            fileTypes.Add(new FileTypeData(".sv5", "BigJig Saved Puzzle"));
            fileTypes.Add(new FileTypeData(".tbm", "Toribash Mod File"));
            fileTypes.Add(new FileTypeData(".umod", "Unreal Tournament Module File"));
            fileTypes.Add(new FileTypeData(".unityproj", "Unity 3D Project"));
            fileTypes.Add(new FileTypeData(".ut2mod", "Unreal Tournament 2003/2004 Module File"));
            fileTypes.Add(new FileTypeData(".ut3", "Unreal Tournament 3 Map File"));
            fileTypes.Add(new FileTypeData(".vfs0", "Metro 2033 Sound File"));
            fileTypes.Add(new FileTypeData(".vmv", "VisualBoyAdvance Recording"));
            fileTypes.Add(new FileTypeData(".vmv", "VirtuaNES Recording"));
            fileTypes.Add(new FileTypeData(".vol", "Video Game Archive"));
            fileTypes.Add(new FileTypeData(".wagame", "Worms Armageddon Game Recording"));
            fileTypes.Add(new FileTypeData(".wam", "Worms Armageddon Mission File"));
            fileTypes.Add(new FileTypeData(".wbt", "Toribash Help File"));
            fileTypes.Add(new FileTypeData(".whirld", "Unity Whirld Package"));
            fileTypes.Add(new FileTypeData(".xmb", "Age of Empires Game Data File"));
            fileTypes.Add(new FileTypeData(".xom", "Worms 3D Object File"));
            fileTypes.Add(new FileTypeData(".xs", "Age of Empires 3 Map AI Generator"));
            fileTypes.Add(new FileTypeData(".zblorb", "Z-machine Package Game File"));
            fileTypes.Add(new FileTypeData(".zds", "GZDoom Save File"));
            fileTypes.Add(new FileTypeData(".zmap", "Zombies Ate My Neighbors Map File"));
            fileTypes.Add(new FileTypeData(".zs1", "ZSNES Slot 1 Saved State File"));
            fileTypes.Add(new FileTypeData(".zs2", "ZSNES Slot 2 Saved State File"));
            fileTypes.Add(new FileTypeData(".zs3", "ZSNES Slot 3 Saved State File"));
            fileTypes.Add(new FileTypeData(".zs4", "ZSNES Slot 4 Saved State File"));
            fileTypes.Add(new FileTypeData(".zs5", "ZSNES Slot 5 Saved State File"));
            fileTypes.Add(new FileTypeData(".zs6", "ZSNES Slot 6 Saved State File"));
            fileTypes.Add(new FileTypeData(".zs8", "ZSNES Slot 8 Saved State File"));
            fileTypes.Add(new FileTypeData(".zst", "ZSNES Save File"));
            fileTypes.Add(new FileTypeData(".ztd", "Zoo Tycoon Data Archive"));
            fileTypes.Add(new FileTypeData(".acx", "Atari ST Program"));
            fileTypes.Add(new FileTypeData(".ar", "Midtown Madness Data File"));
            fileTypes.Add(new FileTypeData(".blb", "Interactive Fiction Package Game File"));
            fileTypes.Add(new FileTypeData(".c4k", "Clonk Key File"));
            fileTypes.Add(new FileTypeData(".dzip", "The Witcher 2 Game Archive"));
            fileTypes.Add(new FileTypeData(".fox", "Furcadia Art File"));
            fileTypes.Add(new FileTypeData(".ibre", "IncrediBots Replay File"));
            fileTypes.Add(new FileTypeData(".ja", "Jet Archive"));
            fileTypes.Add(new FileTypeData(".nfs11save", "Need for Speed: Hot Pursuit Save File"));
            fileTypes.Add(new FileTypeData(".peg", "Peggle Replay File"));
            fileTypes.Add(new FileTypeData(".pop", "Team Fortress 2 Population File"));
            fileTypes.Add(new FileTypeData(".rpy", "Ren'Py Script"));
            fileTypes.Add(new FileTypeData(".spidersolitairesav", "-ms	Microsoft Spider Solitaire Saved Game"));
            fileTypes.Add(new FileTypeData(".spk", "Deer Hunter Map File"));
            fileTypes.Add(new FileTypeData(".wmo", "World of Warcraft World Map Object"));
            fileTypes.Add(new FileTypeData(".agb", "Game Boy Advance ROM"));
            fileTypes.Add(new FileTypeData(".ai", "Battlefield 2 Artificial Intelligence File"));
            fileTypes.Add(new FileTypeData(".alr", "ADRIFT Language Resource File"));
            fileTypes.Add(new FileTypeData(".chr0", "Wii Model Animation File"));
            fileTypes.Add(new FileTypeData(".cpr", "CPC Plus Cartridge"));
            fileTypes.Add(new FileTypeData(".cpx", "Rise of Rome Campaign File"));
            fileTypes.Add(new FileTypeData(".gamedata", "Sandlot Game Data File"));
            fileTypes.Add(new FileTypeData(".gct", "Ocarina Cheat Code Manager File"));
            fileTypes.Add(new FileTypeData(".hmp", "Worms Height Map File"));
            fileTypes.Add(new FileTypeData(".ins", "AGT Game Instruction File"));
            fileTypes.Add(new FileTypeData(".jap", "Japanese Nintendo 64 Game ROM"));
            fileTypes.Add(new FileTypeData(".jigsaw", "Jigsaw Explorer Save File"));
            fileTypes.Add(new FileTypeData(".laby", "Laby Level File"));
            fileTypes.Add(new FileTypeData(".mission", "Vega Strike Mission File"));
            fileTypes.Add(new FileTypeData(".mix", "MotoGP Game File"));
            fileTypes.Add(new FileTypeData(".nclr", "Nintendo DS Color Palette File"));
            fileTypes.Add(new FileTypeData(".ppf", "PlayStation Patch Format File"));
            fileTypes.Add(new FileTypeData(".ps2", "Sharkport Saved Game"));
            fileTypes.Add(new FileTypeData(".purbleshopsav", "-ms	Purble Place Shop Saved Game"));
            fileTypes.Add(new FileTypeData(".pvpf", "Pet ville Save File"));
            fileTypes.Add(new FileTypeData(".settings", "Minecraft iConomy Plug-in Settings File"));
            fileTypes.Add(new FileTypeData(".sims", ".bad	The Sims 3 Failed Game Save File"));
            fileTypes.Add(new FileTypeData(".srk", "Sub Rosa Client File"));
            fileTypes.Add(new FileTypeData(".sv6", "RollerCoaster Tycoon 2 Saved Game"));
            fileTypes.Add(new FileTypeData(".tdb", "Transcendence Game Data File"));
            fileTypes.Add(new FileTypeData(".updatr", "iConomy Update File"));
            fileTypes.Add(new FileTypeData(".vhv", "Valve Source Lighting File"));
            fileTypes.Add(new FileTypeData(".wgf", "Widelands Game File"));
            fileTypes.Add(new FileTypeData(".wop", "Wonderland Object Preset"));
            fileTypes.Add(new FileTypeData(".wrp", ".wgf	Widelands Initial Saved Game File"));
            fileTypes.Add(new FileTypeData(".ydt", "Yu-Gi-Oh! Power of Chaos Data File"));
            fileTypes.Add(new FileTypeData(".z6", "Z-machine Z-code File"));
            fileTypes.Add(new FileTypeData(".tja", "Taikojiro Song Map File"));
            fileTypes.Add(new FileTypeData(".elf", "PlayStation Executable File"));
            fileTypes.Add(new FileTypeData(".scn", "Age of Mythology Scenario File"));
            fileTypes.Add(new FileTypeData(".love", "LÖVE Game File"));
            fileTypes.Add(new FileTypeData(".rom", "Killing Floor Map File"));
            fileTypes.Add(new FileTypeData(".vdf", "Gothic Game Data File"));
            fileTypes.Add(new FileTypeData(".uxx", "Unreal Tournament Cache"));
            fileTypes.Add(new FileTypeData(".world", "The Sims 3 Create a World Tool File"));
            fileTypes.Add(new FileTypeData(".def", "M.U.G.E.N. Character Definition File"));
            fileTypes.Add(new FileTypeData(".bejeweled2deluxesavedgame", "Bejeweled 2 Deluxe Saved Game"));
            fileTypes.Add(new FileTypeData(".ctx", "Valve ICE Encoded Script"));
            fileTypes.Add(new FileTypeData(".fuk", "Postal 2 Map File"));
            fileTypes.Add(new FileTypeData(".ll", "List & Label Preview File"));
            fileTypes.Add(new FileTypeData(".pbn", "Portable Bridge Notation File"));
            fileTypes.Add(new FileTypeData(".world", "WorldPainter File"));
            fileTypes.Add(new FileTypeData(".gpf", "Gecko Patch File"));
            fileTypes.Add(new FileTypeData(".", "-gage	N-Gage Application"));
            fileTypes.Add(new FileTypeData(".nbt", "Minecraft Named Binary Tag File"));
            fileTypes.Add(new FileTypeData(".nfo", "Age of Empires Player File"));
            fileTypes.Add(new FileTypeData(".sclvl", "Scritter's Nest Data File"));
            fileTypes.Add(new FileTypeData(".sfs", "Kerbal Space Program Save File"));
            fileTypes.Add(new FileTypeData(".svt", "Torchlight Saved Game File"));
            fileTypes.Add(new FileTypeData(".chesstitanssav", "-ms	Microsoft Chess Titans Saved Game"));
            fileTypes.Add(new FileTypeData(".mcworld", "Minecraft World Backup File"));
            fileTypes.Add(new FileTypeData(".rda", "Anno 2070 Data File"));
            fileTypes.Add(new FileTypeData(".stl", "SuperTux Level File"));
            fileTypes.Add(new FileTypeData(".z7", "Z-machine Z-code File"));
            fileTypes.Add(new FileTypeData(".rgss2a", "RPG Maker VX RGSS Encrypted Archive"));
            fileTypes.Add(new FileTypeData(".res", "Star Wars KotOR Save Resources File"));
            fileTypes.Add(new FileTypeData(".blorb", "Interactive Fiction Package Game File"));
            fileTypes.Add(new FileTypeData(".carc", "Nintendo DS Compressed Archive File"));
            fileTypes.Add(new FileTypeData(".fos", "Fallout 3 Saved Game"));
            fileTypes.Add(new FileTypeData(".fsm", "FreeSpace Mission File"));
            fileTypes.Add(new FileTypeData(".hit", "The Sims Sound File"));
            fileTypes.Add(new FileTypeData(".pod", "Terminal Reality Game Data File"));
            fileTypes.Add(new FileTypeData(".qc", "QuakeC Source Code File"));
            fileTypes.Add(new FileTypeData(".smzip", "StepMania Package"));
            fileTypes.Add(new FileTypeData(".utc", "Bioware Creature File"));
            fileTypes.Add(new FileTypeData(".bio", "Fallout 2 Character Biography File"));
            fileTypes.Add(new FileTypeData(".crs", "StepMania Course File"));
            fileTypes.Add(new FileTypeData(".drm", "Deus Ex Data File"));
            fileTypes.Add(new FileTypeData(".lock", "Minecraft World Lock File"));
            fileTypes.Add(new FileTypeData(".nkm", "Mario Kart DS Track Data File"));
            fileTypes.Add(new FileTypeData(".osu", "Osu! Script"));
            fileTypes.Add(new FileTypeData(".ovl", "Rollercoaster Tycoon 3 Data File"));
            fileTypes.Add(new FileTypeData(".pegn", "Peggle Nights Replay File"));
            fileTypes.Add(new FileTypeData(".pq", "Progress Quest Save File"));
            fileTypes.Add(new FileTypeData(".rws", "RenderWare Stream File"));
            fileTypes.Add(new FileTypeData(".sco", "OMSI Scenery Object Configuration File"));
            fileTypes.Add(new FileTypeData(".utw", "Unity Whirld File"));
            fileTypes.Add(new FileTypeData(".wxn", "Waixing Famicom Game ROM"));
            fileTypes.Add(new FileTypeData(".ibro", "IncrediBots Robot File"));
            fileTypes.Add(new FileTypeData(".pig", "Pirates of the Burning Sea Data File"));
            fileTypes.Add(new FileTypeData(".vis", "Visibility Image File"));
            fileTypes.Add(new FileTypeData(".dol", "GameCube Executable File"));
            fileTypes.Add(new FileTypeData(".mp2", "Heroes of Might and Magic II Map File"));
            fileTypes.Add(new FileTypeData(".svg", "Saved Game File"));
            fileTypes.Add(new FileTypeData(".nsbtx", "Nintendo DS Model Texture File"));
            fileTypes.Add(new FileTypeData(".spc", "SNES Soundtrack File"));
            fileTypes.Add(new FileTypeData(".mem", "Virtual Game Station Memory File"));
            fileTypes.Add(new FileTypeData(".pcf", "Valve Particle System File"));
            fileTypes.Add(new FileTypeData(".sms", "Sega Master System ROM"));
            fileTypes.Add(new FileTypeData(".tpl", "Wii Image File"));
            fileTypes.Add(new FileTypeData(".k2s", "Kaiser 2 Saved Game"));
            fileTypes.Add(new FileTypeData(".maz", "Hover! Maze File"));
            fileTypes.Add(new FileTypeData(".mdl", "Luigi's Mansion 3D Model File"));
            fileTypes.Add(new FileTypeData(".rle", "Golly Simulation Pattern File"));
            fileTypes.Add(new FileTypeData(".taf", "ADRIFT Text Adventure File"));
            fileTypes.Add(new FileTypeData(".brres", "Wii BRRES Resource Package"));
            fileTypes.Add(new FileTypeData(".ds", "Furcadia DragonSpeak File"));
            fileTypes.Add(new FileTypeData(".sqm", "Operation Flashpoint Mission File"));
            fileTypes.Add(new FileTypeData(".bnk", "Test Drive Unlimited Data Package"));
            fileTypes.Add(new FileTypeData(".bookwormdeluxesavedgame", "Bookworm Deluxe Saved Game"));
            fileTypes.Add(new FileTypeData(".dm_84", "Wolfenstein 2.06 Demo Movie File"));
            fileTypes.Add(new FileTypeData(".dnf", "Duke Nukem Forever Map File"));
            fileTypes.Add(new FileTypeData(".e2gm", "Pangea Enigmo 2 Custom Game File"));
            fileTypes.Add(new FileTypeData(".fst", "Crazy Machines 2 Object File"));
            fileTypes.Add(new FileTypeData(".gpf", "GRAVITY Ragnarok Online Patch File"));
            fileTypes.Add(new FileTypeData(".inform", "Inform Project"));
            fileTypes.Add(new FileTypeData(".lgp", "Final Fantasy Media Archive"));
            fileTypes.Add(new FileTypeData(".md3", "Quake 3 3D Model"));
            fileTypes.Add(new FileTypeData(".scn", "SimCity Scenario File"));
            fileTypes.Add(new FileTypeData(".sud", "Sudoku Puzzle File"));
            fileTypes.Add(new FileTypeData(".ted", "Alamo Map File"));
            fileTypes.Add(new FileTypeData(".tiger", "Tomb Raider Game Data Archive"));
            fileTypes.Add(new FileTypeData(".ups", "UPS Patch File"));
            fileTypes.Add(new FileTypeData(".ut2", "Unreal Tournament Map"));
            fileTypes.Add(new FileTypeData(".uvx", "Unreal Tournament 2003 Saved Game"));
            fileTypes.Add(new FileTypeData(".vcm", "Vice City Mod Manager File"));
            fileTypes.Add(new FileTypeData(".wal", "Quake 2 Texture File"));
            fileTypes.Add(new FileTypeData(".xds", "DS Game Maker Project File"));
            fileTypes.Add(new FileTypeData(".arena", "Quake 3 Engine Arena File"));
            fileTypes.Add(new FileTypeData(".ash", "Audiosurf Audio Metadata File"));
            fileTypes.Add(new FileTypeData(".ass", "Splinter Cell Blacklist Game Data File"));
            fileTypes.Add(new FileTypeData(".bar", "Age of Mythology Data File"));
            fileTypes.Add(new FileTypeData(".bb3", "BlasterBall 3 Level File Support"));
            fileTypes.Add(new FileTypeData(".bdae", "Gameloft Game Data File"));
            fileTypes.Add(new FileTypeData(".bdf", "BSDiff Patch File"));
            fileTypes.Add(new FileTypeData(".bfm", "Terminal Reality Model File"));
            fileTypes.Add(new FileTypeData(".bic", "Civilization 3 Scenario File"));
            fileTypes.Add(new FileTypeData(".bic", "Neverwinter Nights Character File"));
            fileTypes.Add(new FileTypeData(".blb", "Dreamworks Resource File"));
            fileTypes.Add(new FileTypeData(".bmd", "GameCube 3D Model File"));
            fileTypes.Add(new FileTypeData(".bng", "The Bingo Maker Card File"));
            fileTypes.Add(new FileTypeData(".bnz", "The Bingo Maker Card Template File"));
            fileTypes.Add(new FileTypeData(".brmdl", "Wii BRMDL Model File"));
            fileTypes.Add(new FileTypeData(".brtex", "Wii BRTEX Texture File"));
            fileTypes.Add(new FileTypeData(".bs1", "VirtualBus Vehicle Configuration File"));
            fileTypes.Add(new FileTypeData(".cbf", "ChessBase Game Information File"));
            fileTypes.Add(new FileTypeData(".cfge", "Jewel Quest Configuration File"));
            fileTypes.Add(new FileTypeData(".cht", "SNES Cheat File"));
            fileTypes.Add(new FileTypeData(".civ5map", "Civilization 5 Map"));
            fileTypes.Add(new FileTypeData(".clt", "VisualBoyAdvance Cheat List File"));
            fileTypes.Add(new FileTypeData(".cme", "Crazy Machines Experiment File"));
            fileTypes.Add(new FileTypeData(".cns", "M.U.G.E.N. Character States File"));
            fileTypes.Add(new FileTypeData(".cos", "Creatures CAOS File"));
            fileTypes.Add(new FileTypeData(".cpg", "StarCraft Campaign File"));
            fileTypes.Add(new FileTypeData(".cwd", "Nonogram Puzzle File"));
            fileTypes.Add(new FileTypeData(".da3", "AGT Game Data File"));
            fileTypes.Add(new FileTypeData(".da4", "AGT Game Data File"));
            fileTypes.Add(new FileTypeData(".da5", "AGT Game Data File"));
            fileTypes.Add(new FileTypeData(".dam", "DAME Project"));
            fileTypes.Add(new FileTypeData(".ddb", "Command & Conquer: Renegade Data File"));
            fileTypes.Add(new FileTypeData(".demo", "Pokémon Type Wild Data File"));
            fileTypes.Add(new FileTypeData(".desc", "Battlefield 2 Map Description File"));
            fileTypes.Add(new FileTypeData(".dlg", "Dialogue File"));
            fileTypes.Add(new FileTypeData(".dm3", "Quake 3 Demo File"));
            fileTypes.Add(new FileTypeData(".dmo", "Cube 2: Sauerbraten Demo File"));
            fileTypes.Add(new FileTypeData(".dms", "Dream Maker Script"));
            fileTypes.Add(new FileTypeData(".dm_68", "Quake 3 Demo File"));
            fileTypes.Add(new FileTypeData(".dxs", "Deus Ex Saved Game"));
            fileTypes.Add(new FileTypeData(".efx", "Jedi Knight Effects File"));
            fileTypes.Add(new FileTypeData(".erp", "Alter Ego Game Archive"));
            fileTypes.Add(new FileTypeData(".est_uax", "Spanish Unreal Audio Package"));
            fileTypes.Add(new FileTypeData(".fbrb", "Battlefield Bad Company 2 Data File"));
            fileTypes.Add(new FileTypeData(".fc1", "FCEUX Save State File"));
            fileTypes.Add(new FileTypeData(".fld", "YSFLIGHT Field File"));
            fileTypes.Add(new FileTypeData(".fpid", "FPS Creator AI Wizard Data File"));
            fileTypes.Add(new FileTypeData(".fpk", "Civilization 4 Data File"));
            fileTypes.Add(new FileTypeData(".fpmb", "FPS Creator Mab Buffer File"));
            fileTypes.Add(new FileTypeData(".fpmo", "FPS Creator Map Overlay File"));
            fileTypes.Add(new FileTypeData(".frc", "FS Recorder File"));
            fileTypes.Add(new FileTypeData(".freecellsav", "-ms	Microsoft FreeCell Saved Game"));
            fileTypes.Add(new FileTypeData(".frm", "Fallout Graphics File"));
            fileTypes.Add(new FileTypeData(".fsg", "FreeCol Saved Game File"));
            fileTypes.Add(new FileTypeData(".gcd", "Fallout 2 Character Profile File"));
            fileTypes.Add(new FileTypeData(".gg", "Sega Game Gear ROM"));
            fileTypes.Add(new FileTypeData(".glksave", "Zoom Game Save Package"));
            fileTypes.Add(new FileTypeData(".god", "Gore Game Data File"));
            fileTypes.Add(new FileTypeData(".goomod", "World of Goo Add-on"));
            fileTypes.Add(new FileTypeData(".grf", "Transport Tycoon Graphics Resource File"));
            fileTypes.Add(new FileTypeData(".gsx", "Sega Genesis Emulator Saved State File"));
            fileTypes.Add(new FileTypeData(".he", "Humongous Entertainment Game Archive"));
            fileTypes.Add(new FileTypeData(".he0", "Humongous Entertainment Game Archive"));
            fileTypes.Add(new FileTypeData(".he1", "Humongous Entertainment Game Archive"));
            fileTypes.Add(new FileTypeData(".he2", "Humongous Entertainment Game Archive"));
            fileTypes.Add(new FileTypeData(".heartssav", "-ms	Microsoft Hearts Save File"));
            fileTypes.Add(new FileTypeData(".hi", "MacMAME High Scores File"));
            fileTypes.Add(new FileTypeData(".hog", "Descent Mission File"));
            fileTypes.Add(new FileTypeData(".hpk", "Tropico Game Archive"));
            fileTypes.Add(new FileTypeData(".hwd", "Hedgewars Demo File"));
            fileTypes.Add(new FileTypeData(".hwmap", "Hedgewars Drawn Map File"));
            fileTypes.Add(new FileTypeData(".hws", "Hedgewars Saved Game"));
            fileTypes.Add(new FileTypeData(".ibch", "IncrediBots Challenge File"));
            fileTypes.Add(new FileTypeData(".int", "Fallout Compiled Script"));
            fileTypes.Add(new FileTypeData(".int", "Unreal International Localization File"));
            fileTypes.Add(new FileTypeData(".inv", "INVedit File"));
            fileTypes.Add(new FileTypeData(".itr", "Icy Tower Replay File"));
            fileTypes.Add(new FileTypeData(".jam", "PS3 Unreal Tournament 3 Mod File"));
            fileTypes.Add(new FileTypeData(".jcr", "Nonogram Puzzle File"));
            fileTypes.Add(new FileTypeData(".kag", "King Arthur's Gold Map File"));
            fileTypes.Add(new FileTypeData(".kar", "Karel Function Dictionary"));
            fileTypes.Add(new FileTypeData(".kcl", "Mario Kart Collision File"));
            fileTypes.Add(new FileTypeData(".kf2", "Max Payne Resource File"));
            fileTypes.Add(new FileTypeData(".kfs", "Max Payne Model File"));
            fileTypes.Add(new FileTypeData(".lgl", "LeechGet Download List"));
            fileTypes.Add(new FileTypeData(".lip", "Real Virtuality Lip Sync File"));
            fileTypes.Add(new FileTypeData(".lod", "Heroes of Might and Magic 3 Graphics File"));
            fileTypes.Add(new FileTypeData(".lpb", "LaserTank Replay File"));
            fileTypes.Add(new FileTypeData(".lvlx", "Extendable Level File"));
            fileTypes.Add(new FileTypeData(".mad", "Electronic Arts Madcow Movie File"));
            fileTypes.Add(new FileTypeData(".mddbs", "Manic Digger Database"));
            fileTypes.Add(new FileTypeData(".mod", "Neverwinter Nights Module"));
            fileTypes.Add(new FileTypeData(".momma", "Offspring Fling Replay File"));
            fileTypes.Add(new FileTypeData(".mps", "Max Payne Saved Game"));
            fileTypes.Add(new FileTypeData(".mpz", "Red Eclipse Map File"));
            fileTypes.Add(new FileTypeData(".ms1", "VirtualBus Map File"));
            fileTypes.Add(new FileTypeData(".mul", "Deus Ex: HR Multiplexed Audio File"));
            fileTypes.Add(new FileTypeData(".mx2", "Heroes of Might and Magic II Expansion Map File"));
            fileTypes.Add(new FileTypeData(".ngc", "NeoGeo Pocket Color ROM"));
            fileTypes.Add(new FileTypeData(".ngs", "Steins;Gate Game File"));
            fileTypes.Add(new FileTypeData(".nlelem", "NoLimits Track Element File"));
            fileTypes.Add(new FileTypeData(".nml", "NSMB Editor Exported Level File"));
            fileTypes.Add(new FileTypeData(".nv", "MAME NVRAM File"));
            fileTypes.Add(new FileTypeData(".p2m", "Gameshark PlayStation 2 Cheats file"));
            fileTypes.Add(new FileTypeData(".pcd", "Pokémon Wonder Card File"));
            fileTypes.Add(new FileTypeData(".pcsxstate", "PCSX Saved State File"));
            fileTypes.Add(new FileTypeData(".pgf", "Pokémon Mystery Gift for Black & White File"));
            fileTypes.Add(new FileTypeData(".pgt", "Pokémon Gift File"));
            fileTypes.Add(new FileTypeData(".pj", "Project64 Saved State File"));
            fileTypes.Add(new FileTypeData(".pl1", "Adventure Maker Plug-in"));
            fileTypes.Add(new FileTypeData(".player", "Pokémon Type Wild Player Data File"));
            fileTypes.Add(new FileTypeData(".prof", "Super Smash Bros. Crusade Profile"));
            fileTypes.Add(new FileTypeData(".psu", "EMS PS2 Memory Adapter Save File"));
            fileTypes.Add(new FileTypeData(".pzl", "Tibo Jigs@w Puzzle File"));
            fileTypes.Add(new FileTypeData(".pzp", "Tibo Jigs@w Compressed Puzzle File"));
            fileTypes.Add(new FileTypeData(".qdp", "MPQDraft Plugin File"));
            fileTypes.Add(new FileTypeData(".rbj", "XRK Compiled Redcode Object File"));
            fileTypes.Add(new FileTypeData(".rmf", "Hammer Rich Map Format"));
            fileTypes.Add(new FileTypeData(".rot", "Homeworld 2 Graphics File"));
            fileTypes.Add(new FileTypeData(".rpl", "Special Force Replay"));
            fileTypes.Add(new FileTypeData(".run", "Rune Map File"));
            fileTypes.Add(new FileTypeData(".rwd", "Microsoft Flight Simulator Rewards File"));
            fileTypes.Add(new FileTypeData(".s2m", "The Settlers 2 Map File"));
            fileTypes.Add(new FileTypeData(".s2m", "Stronghold 2 Map File"));
            fileTypes.Add(new FileTypeData(".s2mh", "StarCraft 2 Map Header File"));
            fileTypes.Add(new FileTypeData(".s5x", "Heritage of Kings: The Settlers Map File"));
            fileTypes.Add(new FileTypeData(".sa1", "Game Boy Emulator Save File"));
            fileTypes.Add(new FileTypeData(".sab", "Saber File"));
            fileTypes.Add(new FileTypeData(".sc2scene", "StarCraft 2 Cut Scene File"));
            fileTypes.Add(new FileTypeData(".sc6", "RollerCoaster Tycoon 2 Scenario File"));
            fileTypes.Add(new FileTypeData(".scf", "SimTown Sounds File"));
            fileTypes.Add(new FileTypeData(".sgb", "Super Game Boy ROM File"));
            fileTypes.Add(new FileTypeData(".skd", "Max Payne Skin Data File"));
            fileTypes.Add(new FileTypeData(".slst", "Game Data File"));
            fileTypes.Add(new FileTypeData(".smpd", "Sc2gears Mouse Print Data File"));
            fileTypes.Add(new FileTypeData(".sna", "NO$GBA Snapshot File"));
            fileTypes.Add(new FileTypeData(".sod", "Spear of Destiny Data File"));
            fileTypes.Add(new FileTypeData(".soe", "Star Wars: Shadows of the Empire Save File"));
            fileTypes.Add(new FileTypeData(".solitairesav", "-ms	Microsoft Solitaire Saved Game"));
            fileTypes.Add(new FileTypeData(".sounds", "Quake 3 Engine Sound Definition File"));
            fileTypes.Add(new FileTypeData(".sps", "Quake 3 Engine Speaker Definition File"));
            fileTypes.Add(new FileTypeData(".sps", "Sharkport PS2 Save File"));
            fileTypes.Add(new FileTypeData(".ssl", "Fallout Script"));
            fileTypes.Add(new FileTypeData(".stage", "Pokémon Type Wild Stage Data File"));
            fileTypes.Add(new FileTypeData(".sts", "DuoS DSEMU Saved State File"));
            fileTypes.Add(new FileTypeData(".sv5", "Chris Sawyer's Locomotion Saved Game"));
            fileTypes.Add(new FileTypeData(".sve", "Fallout 2 Video Subtitle File"));
            fileTypes.Add(new FileTypeData(".td6", "RollerCoaster Tycoon Track Design File"));
            fileTypes.Add(new FileTypeData(".tdt", "Sim Tower Game File"));
            fileTypes.Add(new FileTypeData(".ted", "Tribes 2 Game Data File"));
            fileTypes.Add(new FileTypeData(".tkr", "Tinker Custom Level File"));
            fileTypes.Add(new FileTypeData(".trk", "Pacific Fighters Offline Track File"));
            fileTypes.Add(new FileTypeData(".ucl", "Killing Floor System File"));
            fileTypes.Add(new FileTypeData(".ulx", "Glulx Game File"));
            fileTypes.Add(new FileTypeData(".uop", "Ultima Online Patch File"));
            fileTypes.Add(new FileTypeData(".veh", "Vehicle File"));
            fileTypes.Add(new FileTypeData(".vmx", "Valve Map Backup File"));
            fileTypes.Add(new FileTypeData(".vwp", "Vehicle Weapon File"));
            fileTypes.Add(new FileTypeData(".wdf", "Wiimm Disc File"));
            fileTypes.Add(new FileTypeData(".weap", "Quake 3 Engine Weapon File"));
            fileTypes.Add(new FileTypeData(".wldx", "World Map File"));
            fileTypes.Add(new FileTypeData(".wolfquest", "WolfQuest Saved Game"));
            fileTypes.Add(new FileTypeData(".wsc", "WonderSwan Color Game ROM"));
            fileTypes.Add(new FileTypeData(".wx", "Flight Simulator Weather File"));
            fileTypes.Add(new FileTypeData(".xan", "Worms Map File"));
            fileTypes.Add(new FileTypeData(".xbsav", "Mass Effect 2 Xbox Saved Game"));
            fileTypes.Add(new FileTypeData(".xp4", "KiriKiri Package"));
            fileTypes.Add(new FileTypeData(".xvmconf", "World of Tanks XVM Configuration File"));
            fileTypes.Add(new FileTypeData(".y3a", "Yu-Gi-Oh! ONLINE 3 Avatar File"));
            fileTypes.Add(new FileTypeData(".y3d", "Yu-Gi-Oh! ONLINE 3 Deck File"));
            fileTypes.Add(new FileTypeData(".yfs", "YSFLIGHT Mission File"));
            fileTypes.Add(new FileTypeData(".zlb", "Z-machine Package Game File"));
            fileTypes.Add(new FileTypeData(".abs", "AB SuDoKu Saved Game"));
            fileTypes.Add(new FileTypeData(".mm6", "Might and Magic 6 Saved Game"));
            fileTypes.Add(new FileTypeData(".prg", "Commodore Program File"));
            fileTypes.Add(new FileTypeData(".szs", "GameCube Data File"));
            fileTypes.Add(new FileTypeData(".tsc", "Cave Story Script"));
            fileTypes.Add(new FileTypeData(".zoo", "Zoo Tycoon Saved Game"));
            fileTypes.Add(new FileTypeData(".glb", "Glulx Blorb Game File"));
            fileTypes.Add(new FileTypeData(".zzz", "Black & White Game Data File"));
            fileTypes.Add(new FileTypeData(".toc", "World of Warcraft Add-on Table of Contents File"));
            fileTypes.Add(new FileTypeData(".vb", "Virtual Boy ROM File"));
            fileTypes.Add(new FileTypeData(".s10", "Brasfoot Saved Game File"));
            fileTypes.Add(new FileTypeData(".sve", "Carmageddon: TDR 2000 Saved Game"));
            fileTypes.Add(new FileTypeData(".car", "Gary Gadget Car File"));
            fileTypes.Add(new FileTypeData(".edat", "Sony Encrypted Data File"));
            fileTypes.Add(new FileTypeData(".ek6", "Generation 6 Pokémon Save File"));
            fileTypes.Add(new FileTypeData(".fds", "Nintendo FDS ROM"));
            fileTypes.Add(new FileTypeData(".fpp", "FPS Creator Prefab File"));
            fileTypes.Add(new FileTypeData(".gblorb", "Glulx Blorb Game File"));
            fileTypes.Add(new FileTypeData(".gsba", "Game Save Backup Archive"));
            fileTypes.Add(new FileTypeData(".md", "Sharkport Saved Game File"));
            fileTypes.Add(new FileTypeData(".nsbva", "Nintendo DS Visibility Animation File"));
            fileTypes.Add(new FileTypeData(".prison", "Prison Architect Saved Game"));
            fileTypes.Add(new FileTypeData(".spa", "Nintendo DS Particle File"));
            fileTypes.Add(new FileTypeData(".ttl", "AGT Game Title File"));
            fileTypes.Add(new FileTypeData(".wld", "SMBX World File"));
            fileTypes.Add(new FileTypeData(".atm", "PSP Game Audio File"));
            fileTypes.Add(new FileTypeData(".cem", "Children of the Nile Model File"));
            fileTypes.Add(new FileTypeData(".dwp", "Darwin Pond Save File"));
            fileTypes.Add(new FileTypeData(".itk", "ScummVM Game Data File"));
            fileTypes.Add(new FileTypeData(".mdl0", "Wii Model File"));
            fileTypes.Add(new FileTypeData(".pat0", "Wii Texture Pattern File"));
            fileTypes.Add(new FileTypeData(".sow", "Descent ARJ Archive"));
            fileTypes.Add(new FileTypeData(".tap", "Tap Tap Revenge Tap File"));
            fileTypes.Add(new FileTypeData(".z1", "Z-machine Z-code File"));
            fileTypes.Add(new FileTypeData(".inp", "MAME Replay File"));
            fileTypes.Add(new FileTypeData(".map", "Leges Motus Map File"));
            fileTypes.Add(new FileTypeData(".shader", "Quake 3 Engine Shader File"));
            fileTypes.Add(new FileTypeData(".bwa", "Bookworm Adventures Player File"));
            fileTypes.Add(new FileTypeData(".pof", "Descent Robot Definition File"));
            fileTypes.Add(new FileTypeData(".sfc", "Creatures Saved Game"));
            fileTypes.Add(new FileTypeData(".an2", "Croc Legend of the Gobbos Animation File"));
            fileTypes.Add(new FileTypeData(".ars", "Carmageddon Saved Game"));
            fileTypes.Add(new FileTypeData(".ash", "KoLmafia ASH Script"));
            fileTypes.Add(new FileTypeData(".bgz", "Blood Frontier Map File"));
            fileTypes.Add(new FileTypeData(".blp", "Speedy Eggbert Game Data File"));
            fileTypes.Add(new FileTypeData(".breff", "Wii Effect Controls File"));
            fileTypes.Add(new FileTypeData(".breft", "Wii Effects File"));
            fileTypes.Add(new FileTypeData(".brlyt", "Wii Textures and Material Lists File"));
            fileTypes.Add(new FileTypeData(".brn", "Gabriel Knight Barn File"));
            fileTypes.Add(new FileTypeData(".brsar", "Wii BRSAR Audio Package"));
            fileTypes.Add(new FileTypeData(".bsdiff", "BSDiff Patch File"));
            fileTypes.Add(new FileTypeData(".clr0", "Wii Color Swapping Animation File"));
            fileTypes.Add(new FileTypeData(".cml", "Crazy Machines Lab File"));
            fileTypes.Add(new FileTypeData(".crysispsf", "Crysis Warhead Saved Game"));
            fileTypes.Add(new FileTypeData(".da2", "AGT Game Data File"));
            fileTypes.Add(new FileTypeData(".da6", "AGT Game Data File"));
            fileTypes.Add(new FileTypeData(".day", "Day of the Zombie Map File"));
            fileTypes.Add(new FileTypeData(".dn1", "Duke Nukem 1 Game Data File"));
            fileTypes.Add(new FileTypeData(".dn2", "Duke Nukem Episode 2 Game File"));
            fileTypes.Add(new FileTypeData(".dn3", "Duke Nukem Episode 3 Game File"));
            fileTypes.Add(new FileTypeData(".dnh", "Danmakufu Script"));
            fileTypes.Add(new FileTypeData(".dsg", "Decker Saved Game"));
            fileTypes.Add(new FileTypeData(".eepf", "EmuOS Exchangeable Packet File"));
            fileTypes.Add(new FileTypeData(".epc", "Doctor Who Game Data File"));
            fileTypes.Add(new FileTypeData(".exc", "Black & White Zone File"));
            fileTypes.Add(new FileTypeData(".ffd", "FATE Saved Game"));
            fileTypes.Add(new FileTypeData(".fila", "Aleph One Replay File"));
            fileTypes.Add(new FileTypeData(".fnta", "Aleph One Font File"));
            fileTypes.Add(new FileTypeData(".gc", "Galactic Conquest Saved Game"));
            fileTypes.Add(new FileTypeData(".gcs", "GameCube SharkSave File"));
            fileTypes.Add(new FileTypeData(".gdw", "Jaws Unleashed Data File"));
            fileTypes.Add(new FileTypeData(".gjd", "The 7th Guest Media File"));
            fileTypes.Add(new FileTypeData(".gmv", "Gens Game Recording"));
            fileTypes.Add(new FileTypeData(".gnp", "GenePool Save File"));
            fileTypes.Add(new FileTypeData(".god", "Populous II Player Progress File"));
            fileTypes.Add(new FileTypeData(".hhsl", "Hockey High Score List File"));
            fileTypes.Add(new FileTypeData(".hs", "LaserTank High Scores File"));
            fileTypes.Add(new FileTypeData(".hxm", "Descent 2 Resource Modification"));
            fileTypes.Add(new FileTypeData(".ib2", "IncrediBots 2 Saved Challenge File"));
            fileTypes.Add(new FileTypeData(".ib3", "IncrediBots 3 Saved Challenge File"));
            fileTypes.Add(new FileTypeData(".imga", "Aleph One Image File"));
            fileTypes.Add(new FileTypeData(".jrc", "PCjr Cartridge ROM File"));
            fileTypes.Add(new FileTypeData(".jrz", "PSP Game Data File"));
            fileTypes.Add(new FileTypeData(".kmp", "Mario Kart Wii Course Description File"));
            fileTypes.Add(new FileTypeData(".l3d", "Black & White Graphics File"));
            fileTypes.Add(new FileTypeData(".ltg", "LaserTank Graphics File"));
            fileTypes.Add(new FileTypeData(".manm", "Vietcong Game Data File"));
            fileTypes.Add(new FileTypeData(".mato", "Atomic Combat Saved Game"));
            fileTypes.Add(new FileTypeData(".mdm", "Mario Dash Map File"));
            fileTypes.Add(new FileTypeData(".mm7", "Might and Magic 7 Saved Game"));
            fileTypes.Add(new FileTypeData(".mm8", "Might and Magic 8 Saved Game"));
            fileTypes.Add(new FileTypeData(".msbt", "Nintendo Wii Galaxy Dialogue File"));
            fileTypes.Add(new FileTypeData(".n3d", "Super 3D Noah's Ark Data File"));
            fileTypes.Add(new FileTypeData(".ncgr", "Nintendo DS Title Graphics File"));
            fileTypes.Add(new FileTypeData(".neosave", "Neopets Save File"));
            fileTypes.Add(new FileTypeData(".nlpx", "NoLimits Package"));
            fileTypes.Add(new FileTypeData(".nscr", "Nintendo DS Title Screen File"));
            fileTypes.Add(new FileTypeData(".odf", "Battlezone Object Definition File"));
            fileTypes.Add(new FileTypeData(".opt", "AGT Game Data File"));
            fileTypes.Add(new FileTypeData(".pat", "Kega Fusion Cheats File"));
            fileTypes.Add(new FileTypeData(".phya", "Aleph One Physics File"));
            fileTypes.Add(new FileTypeData(".plf", "Mr. Bean Game Data File"));
            fileTypes.Add(new FileTypeData(".plt0", "Wii Color Palette File"));
            fileTypes.Add(new FileTypeData(".pog", "Descent 2 Texture Modification"));
            fileTypes.Add(new FileTypeData(".prefs", "MMORPG Tycoon Preferences File"));
            fileTypes.Add(new FileTypeData(".psx", "PlayStation Save File"));
            fileTypes.Add(new FileTypeData(".psys", "ZEQ2 Lite Particle Effects File"));
            fileTypes.Add(new FileTypeData(".rfd", "Emperor: Battle for Dune Data File"));
            fileTypes.Add(new FileTypeData(".rgp", "RealArcade Game Package"));
            fileTypes.Add(new FileTypeData(".rkg", "Mario Kart Wii Ghost Data File"));
            fileTypes.Add(new FileTypeData(".rkp", "Rockchip MP4 Player Game"));
            fileTypes.Add(new FileTypeData(".rl", "The 7th Guest Audio Data File"));
            fileTypes.Add(new FileTypeData(".rl", ".gz	Golly Compressed Simulation Pattern File"));
            fileTypes.Add(new FileTypeData(".rp2", "RetroPlatform Player Program Archive"));
            fileTypes.Add(new FileTypeData(".rs2", "RailSim2 Saved Layout File"));
            fileTypes.Add(new FileTypeData(".sc5", "Chris Sawyer's Locomotion Scenario File"));
            fileTypes.Add(new FileTypeData(".scea", "Aleph One Map File"));
            fileTypes.Add(new FileTypeData(".scn0", "Wii Texture Animation File"));
            fileTypes.Add(new FileTypeData(".sgaa", "Aleph One Saved Game"));
            fileTypes.Add(new FileTypeData(".shpa", "Aleph One Shape File"));
            fileTypes.Add(new FileTypeData(".skein", "Skein XML File"));
            fileTypes.Add(new FileTypeData(".smo", "Sumotori Dreams Arena File"));
            fileTypes.Add(new FileTypeData(".snda", "Aleph One Sound File"));
            fileTypes.Add(new FileTypeData(".sp2", "Super Ball 2 Level File"));
            fileTypes.Add(new FileTypeData(".srt0", "Wii Texture Animation File"));
            fileTypes.Add(new FileTypeData(".ssa", "Children of the Nile Campaign File"));
            fileTypes.Add(new FileTypeData(".sst", "Children of the Nile Textures File"));
            fileTypes.Add(new FileTypeData(".stsg", "SuperTux Saved Game"));
            fileTypes.Add(new FileTypeData(".stwm", "SuperTux World Map File"));
            fileTypes.Add(new FileTypeData(".sv4", "RollerCoaster Tycoon Saved Game"));
            fileTypes.Add(new FileTypeData(".swv", "Microsoft Sidewinder Game Voice Settings File"));
            fileTypes.Add(new FileTypeData(".sww", "Anno Saved Game"));
            fileTypes.Add(new FileTypeData(".syb", "Syberia Game Data File"));
            fileTypes.Add(new FileTypeData(".system", "Vega Strike Virtual System File"));
            fileTypes.Add(new FileTypeData(".td4", "RollerCoaster Tycoon Track File"));
            fileTypes.Add(new FileTypeData(".tex0", "Wii Texture File"));
            fileTypes.Add(new FileTypeData(".tfr", "TIE Fighter Pilot File"));
            fileTypes.Add(new FileTypeData(".tjc", "Taikojiro Song Map Sequence File"));
            fileTypes.Add(new FileTypeData(".tp4", "RollerCoaster Tycoon Track Picture File"));
            fileTypes.Add(new FileTypeData(".ttm", "Tower Toppler Mission File"));
            fileTypes.Add(new FileTypeData(".tut", "Children of the Nile Tutorial File"));
            fileTypes.Add(new FileTypeData(".ucm", "Crazy Machines Model File"));
            fileTypes.Add(new FileTypeData(".uqm", "The Ur-Quan Masters Game Data File"));
            fileTypes.Add(new FileTypeData(".ut8", "Ghost Master Language File"));
            fileTypes.Add(new FileTypeData(".vbf", "City Interactive Game Data File"));
            fileTypes.Add(new FileTypeData(".vgi", "Vista Game Explorer Editor Game File"));
            fileTypes.Add(new FileTypeData(".wdf", "Wonderland Adventures Media File"));
            fileTypes.Add(new FileTypeData(".wl1", "Wolfenstein 3D Data File"));
            fileTypes.Add(new FileTypeData(".wmf", "Widelands Map File"));
            fileTypes.Add(new FileTypeData(".wpt", "Cube 2 Waypoint File"));
            fileTypes.Add(new FileTypeData(".xp", "XPilot Map"));
            fileTypes.Add(new FileTypeData(".xp2", "XPilot NG"));
            fileTypes.Add(new FileTypeData(".xtl", "Vietcong Data File"));
            fileTypes.Add(new FileTypeData(".z2", "Z-machine Z-code File"));
            
            return fileTypes;
        }

        // http://fileinfo.com/filetypes/video
        public static List<FileTypeData> DefaultTypes()
        {
            List<FileTypeData> fileTypes = new List<FileTypeData>();

            fileTypes.Add(new FileTypeData(".adf", "Amiga Disk ROM"));
            fileTypes.Add( new FileTypeData(".gen", "Sega Genesis ROM") );
            fileTypes.Add( new FileTypeData(".gcm", "GameCube ROM") );
            fileTypes.Add( new FileTypeData(".gb", "Game Boy ROM File") );
            fileTypes.Add( new FileTypeData(".gba", "Game Boy Advance ROM") );
            fileTypes.Add( new FileTypeData(".v64", "Nintendo 64 ROM Dump") );
            fileTypes.Add( new FileTypeData(".z64", "Nintendo 64 Game ROM") );
            fileTypes.Add( new FileTypeData(".nes", "Nintendo (NES) ROM File") );
            fileTypes.Add( new FileTypeData(".gbc", "Game Boy Color ROM") );
            fileTypes.Add( new FileTypeData(".32x", "Sega 32X ROM") );
            fileTypes.Add( new FileTypeData(".3ds", "Nintendo 3DS ROM") );
            fileTypes.Add( new FileTypeData(".nds", "Nintendo DS Game ROM") );
            fileTypes.Add( new FileTypeData(".smc", "Super Nintendo Game ROM") );
            fileTypes.Add( new FileTypeData(".n64", "Nintendo 64 Emulator ROM File") );
            fileTypes.Add( new FileTypeData(".rom", "N64 Game ROM File") );
            fileTypes.Add( new FileTypeData(".sfc", "Super Nintendo ROM") );
            fileTypes.Add( new FileTypeData(".a52", "Atari 5200 ROM") );
            fileTypes.Add( new FileTypeData(".gcz", "Compressed GameCube/Wii ROM") );
            fileTypes.Add( new FileTypeData(".pce", "TurboGrafx-16 ROM") );
            fileTypes.Add( new FileTypeData(".ngp", "NeoGeo Pocket ROM") );
            fileTypes.Add( new FileTypeData(".a26", "Atari 2600 ROM") );
            fileTypes.Add( new FileTypeData(".md", "SEGA Mega Drive ROM") );

            return fileTypes;
        }
    }
}
