using DriveIndexer.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DriveIndexer.Database
{
    public class DefaultFileTypesSystem
    {
        // http://fileinfo.com/filetypes/video
        public static List<FileTypeData> DefaultTypes()
        {
            List<FileTypeData> fileTypes = new List<FileTypeData>();

            //fileTypes.Add(new FileTypeData(".sdb", "Custom Application Compatibility Database"));
            //fileTypes.Add(new FileTypeData(".ebd", "Windows EBD System File"));
            //fileTypes.Add(new FileTypeData(".prop", "Android Build Properties File"));
            //fileTypes.Add(new FileTypeData(".htt", "Hypertext Template File"));
            //fileTypes.Add(new FileTypeData(".ion", "File Description File"));
            //fileTypes.Add(new FileTypeData(".qvm", "Q Virtual Machine"));
            //fileTypes.Add(new FileTypeData(".iconpackage", "IconPackager Theme File"));
            //fileTypes.Add(new FileTypeData(".cpl", "Windows Control Panel Item"));
            //fileTypes.Add(new FileTypeData(".pnf", "Precompiled INF File"));
            //fileTypes.Add(new FileTypeData(".bash_history", "Bash History File"));
            //fileTypes.Add(new FileTypeData(".pol", "Windows Policy File"));
            //fileTypes.Add(new FileTypeData(".nb0", "Device Boot Loader Image"));
            //fileTypes.Add(new FileTypeData(".reg", "Registry File"));
            //fileTypes.Add(new FileTypeData(".hiv", "Windows Registry Hive File"));
            //fileTypes.Add(new FileTypeData(".scr", "Windows Screensaver"));
            //fileTypes.Add(new FileTypeData(".bash_profile", "Bash Interactive Login Shell File"));
            //fileTypes.Add(new FileTypeData(".nfo", "System Information File"));
            //fileTypes.Add(new FileTypeData(".clb", "COM+ Catalog File"));
            //fileTypes.Add(new FileTypeData(".hdmp", "Windows Heap Dump"));
            fileTypes.Add(new FileTypeData(".dll", "Dynamic Link Library"));
            //fileTypes.Add(new FileTypeData(".icns", "Mac OS X Icon Resource File"));
            fileTypes.Add(new FileTypeData(".dmp", "Windows Memory Dump"));
            //fileTypes.Add(new FileTypeData(".lnk", "Windows File Shortcut"));
            //fileTypes.Add(new FileTypeData(".asec", "Android Secure Application File"));
            //fileTypes.Add(new FileTypeData(".ani", "Windows Animated Cursor"));
            //fileTypes.Add(new FileTypeData(".profile", "Bash Shell Profile"));
            //fileTypes.Add(new FileTypeData(".scf", "Windows Explorer Command"));
            //fileTypes.Add(new FileTypeData(".mdmp", "Windows Minidump"));
            //fileTypes.Add(new FileTypeData(".mobileconfig", "Apple Mobile Configuration File"));
            //fileTypes.Add(new FileTypeData(".aml", "ACPI Machine Language File"));
            //fileTypes.Add(new FileTypeData(".prt", "Printer Driver File"));
            //fileTypes.Add(new FileTypeData(".cur", "Windows Cursor"));
            //fileTypes.Add(new FileTypeData("0	Shared", "Library Link File"));
            //fileTypes.Add(new FileTypeData(".vxd", "Virtual Device Driver"));
            //fileTypes.Add(new FileTypeData("0", "386	Windows Virtual Device Driver"));
            //fileTypes.Add(new FileTypeData(".msp", "Windows Installer Patch"));
            //fileTypes.Add(new FileTypeData(".cnt", "Help Contents File"));
            //fileTypes.Add(new FileTypeData(".msstyles", "Windows XP Style"));
            //fileTypes.Add(new FileTypeData(".cab", "Windows Cabinet File"));
            //fileTypes.Add(new FileTypeData(".h1s", "Windows Assistance Platform Help File"));
            //fileTypes.Add(new FileTypeData("0	Indexing", "Service Data File"));
            //fileTypes.Add(new FileTypeData(".sys", "Motorola Driver File"));
            //fileTypes.Add(new FileTypeData(".pk2", "Silkroad Online Game Data File"));
            fileTypes.Add(new FileTypeData(".sys", "Windows System File"));
            //fileTypes.Add(new FileTypeData(".manifest", "Windows Application Manifest File"));
            //fileTypes.Add(new FileTypeData(".dat", "Windows Registry Hive File"));
            //fileTypes.Add(new FileTypeData(".sfcache", "ReadyBoost Cache File"));
            //fileTypes.Add(new FileTypeData(".bashrc", "Bash Non-Interactive Login Shell File"));
            //fileTypes.Add(new FileTypeData(".edj", "Enlightenment Theme File"));
            //fileTypes.Add(new FileTypeData(".admx", "Group Policy Administrative Template File"));
            //fileTypes.Add(new FileTypeData(".cpr", "Windows Phone Display Settings File"));
            //fileTypes.Add(new FileTypeData(".desklink", "Desktop Shortcut"));
            //fileTypes.Add(new FileTypeData(".hhc", "HTML Help Table of Contents"));
            //fileTypes.Add(new FileTypeData(".hhk", "HTML Help Index"));
            //fileTypes.Add(new FileTypeData(".job", "Windows Task Scheduler Job File"));
            //fileTypes.Add(new FileTypeData(".lpd", "Lookout Protocol Driver File"));
            //fileTypes.Add(new FileTypeData(".mapimail", "Send To Mail Recipient"));
            //fileTypes.Add(new FileTypeData(".mlc", "Microsoft Language Interface Pack"));
            //fileTypes.Add(new FileTypeData(".msc", "Microsoft Management Console Snap-in Control File"));
            //fileTypes.Add(new FileTypeData(".nt", "Windows NT Startup File"));
            //fileTypes.Add(new FileTypeData(".sbn", "Cisco IP Phone Firmware File"));
            //fileTypes.Add(new FileTypeData(".shd", "Windows Print Job Shadow File"));
            //fileTypes.Add(new FileTypeData(".bio", "BIOS File"));
            //fileTypes.Add(new FileTypeData(".ci", "Windows Content Indexer Catalog File"));
            //fileTypes.Add(new FileTypeData(".dev", "Windows Device Driver File"));
            //fileTypes.Add(new FileTypeData(".mbr", "Master Boot Record File"));
            //fileTypes.Add(new FileTypeData(".ntfs", "NTFS Partition File"));
            //fileTypes.Add(new FileTypeData(".vga", "VGA Display Driver"));
            //fileTypes.Add(new FileTypeData(".vx_", "Compressed Virtual Device Driver File"));
            //fileTypes.Add(new FileTypeData(".deskthemepack", "Windows 8 Desktop Theme Pack File"));
            //fileTypes.Add(new FileTypeData(".dvd", "DOS Device Driver"));
            //fileTypes.Add(new FileTypeData(".diagcab", "Troubleshooting Pack Cabinet File"));
            //fileTypes.Add(new FileTypeData(".mui", "Multilingual User Interface File"));
            //fileTypes.Add(new FileTypeData(".regtran", "-ms	Registry Transaction Log File"));
            //fileTypes.Add(new FileTypeData(".bcd", "Windows Boot Configuration Data File"));
            //fileTypes.Add(new FileTypeData(".pck", "System Center Configuration Manager Package File"));
            //fileTypes.Add(new FileTypeData(".efi", "Extensible Firmware Interface File"));
            //fileTypes.Add(new FileTypeData(".wdgt", "Dashboard Widget"));
            //fileTypes.Add(new FileTypeData(".adm", "Administrative Template File"));
            //fileTypes.Add(new FileTypeData(".log1", "Windows Registry Hive Log File"));
            //fileTypes.Add(new FileTypeData(".theme", "Microsoft Plus! Desktop Theme"));
            //fileTypes.Add(new FileTypeData(".ico", "Icon File"));
            //fileTypes.Add(new FileTypeData(".lst", "GRUB Boot List File"));
            //fileTypes.Add(new FileTypeData(".inf_loc", "Windows Driver Information Cache File"));
            //fileTypes.Add(new FileTypeData(".mtz", "MIUI Theme"));
            //fileTypes.Add(new FileTypeData(".drv", "Device Driver"));
            //fileTypes.Add(new FileTypeData(".rc1", "Samsung Mobile Device Firmware File"));
            //fileTypes.Add(new FileTypeData(".pit", "Samsung Phone Firmware File"));
            //fileTypes.Add(new FileTypeData(".cat", "Windows Catalog File"));
            //fileTypes.Add(new FileTypeData(".c32", "Syslinux COM32 Module"));
            //fileTypes.Add(new FileTypeData(".elf", "Executable and Linkable Format File"));
            //fileTypes.Add(new FileTypeData(".prf", "Windows System File"));
            //fileTypes.Add(new FileTypeData(".ppd", "PostScript Printer Description File"));
            //fileTypes.Add(new FileTypeData(".shsh", "iPhone/iPod Touch SHSH Blob File"));
            //fileTypes.Add(new FileTypeData(".ins", "Internet Naming Service File"));
            //fileTypes.Add(new FileTypeData(".sbf", "Android System File"));
            //fileTypes.Add(new FileTypeData(".bk2", "Windows Indexing Service Data File"));
            //fileTypes.Add(new FileTypeData(".idx", "Index File"));
            //fileTypes.Add(new FileTypeData(".pat", "DiskStation Manager Installation File"));
            //fileTypes.Add(new FileTypeData(".rmt", "Router Firmware File"));
            //fileTypes.Add(new FileTypeData(".spl", "Windows Print Spool File"));
            //fileTypes.Add(new FileTypeData(".zon", ".identifier	Windows Zone Identifier File"));
            //fileTypes.Add(new FileTypeData(".bom", "Mac OS X Bill of Materials File"));
            //fileTypes.Add(new FileTypeData(".chg", "Windows Net Logon File"));
            //fileTypes.Add(new FileTypeData(".ffx", "Microsoft Find Fast Index"));
            //fileTypes.Add(new FileTypeData(".ks", "Kickstart File"));
            //fileTypes.Add(new FileTypeData(".lpd", "LPD Daemon Print Permissions File"));
            //fileTypes.Add(new FileTypeData(".msstyle", "Windows XP Unsigned Style"));
            //fileTypes.Add(new FileTypeData(".trx_dll", "Windows Startup File"));
            //fileTypes.Add(new FileTypeData(".uce", "Windows UCE System File"));
            //fileTypes.Add(new FileTypeData(".dimax", "DiMAX Firmware Image File"));
            //fileTypes.Add(new FileTypeData(".chk", "Netgear Router Firmware File"));
            //fileTypes.Add(new FileTypeData(".etl", "Microsoft Event Trace Log File"));
            //fileTypes.Add(new FileTypeData(".flg", "Puppy Linux Partition Flag File"));
            //fileTypes.Add(new FileTypeData(".key", "Security Key"));
            //fileTypes.Add(new FileTypeData(".bin", "Router Firmware File"));
            //fileTypes.Add(new FileTypeData(".swp", "Swap File"));
            //fileTypes.Add(new FileTypeData(".grp", "Windows Program Manager Group"));
            //fileTypes.Add(new FileTypeData(".2fs", "Puppy Linux Save State File"));
            //fileTypes.Add(new FileTypeData(".blf", "CLFS Base Log File"));
            //fileTypes.Add(new FileTypeData(".sqm", "Service Quality Monitoring File"));
            //fileTypes.Add(new FileTypeData(".icl", "Windows Icon Library File"));
            //fileTypes.Add(new FileTypeData(".fpbf", "Mac OS X Burn Folder"));
            //fileTypes.Add(new FileTypeData(".group", "Windows Contacts Group File"));
            //fileTypes.Add(new FileTypeData(".hlp", "Windows Help File"));
            //fileTypes.Add(new FileTypeData(".cgz", "Linux Drivers Archive"));
            //fileTypes.Add(new FileTypeData(".configprofile", "Apple Configuration Profile"));
            //fileTypes.Add(new FileTypeData(".cpi", "Codepage Information File"));
            //fileTypes.Add(new FileTypeData(".dit", "Active Directory Information Tree File"));
            //fileTypes.Add(new FileTypeData(".drpm", "Delta RPM File"));
            //fileTypes.Add(new FileTypeData(".efires", "EFI Image File"));
            //fileTypes.Add(new FileTypeData(".escopy", "ES Explorer Temporary File"));
            //fileTypes.Add(new FileTypeData(".fota", "Firmware Over-the-Air File"));
            //fileTypes.Add(new FileTypeData(".help", "Mac OS X Help Book"));
            //fileTypes.Add(new FileTypeData(".hpj", "Help Project File"));
            //fileTypes.Add(new FileTypeData(".img3", "iPhone IMG3 File"));
            //fileTypes.Add(new FileTypeData(".itemdat", "-ms	Windows 8 Start Screen Item Data File"));
            //fileTypes.Add(new FileTypeData(".ius", "InfoTMIC Firmware Update File"));
            //fileTypes.Add(new FileTypeData(".kext", "Mac OS X Kernel Extension"));
            //fileTypes.Add(new FileTypeData(".ko", "Linux Kernel Module File"));
            //fileTypes.Add(new FileTypeData(".librar", "-ms	Windows Library Description File"));
            //fileTypes.Add(new FileTypeData(".lockfile", "Mac OS X PLIST Lock File"));
            //fileTypes.Add(new FileTypeData(".log2", "Windows Registry Hive Log 2 File"));
            //fileTypes.Add(new FileTypeData(".mi4", "Audio Player Firmware File"));
            //fileTypes.Add(new FileTypeData(".mum", "Windows Vista Update Package"));
            //fileTypes.Add(new FileTypeData(".nls", "Microsoft National Language Support File"));
            //fileTypes.Add(new FileTypeData(".odex", "Optimized Dalvik Executable"));
            //fileTypes.Add(new FileTypeData(".pdr", "Windows Port Driver"));
            //fileTypes.Add(new FileTypeData(".prefpane", "Mac OS X System Preference Pane"));
            //fileTypes.Add(new FileTypeData(".provisionprofile", "Apple Provision Profile"));
            //fileTypes.Add(new FileTypeData(".pwl", "Windows Password List"));
            //fileTypes.Add(new FileTypeData(".rfw", "Rockchip Firmware File"));
            //fileTypes.Add(new FileTypeData(".savedsearch", "Spotlight Saved Search"));
            //fileTypes.Add(new FileTypeData(".saver", "Mac OS X Screen Saver"));
            //fileTypes.Add(new FileTypeData(".searchconnecto", "-ms	Windows Search Connector File"));
            //fileTypes.Add(new FileTypeData(".wdf", "Windows Driver Foundation File"));
            //fileTypes.Add(new FileTypeData(".wgz", "S60 Web Runtime Widget Package"));
            //fileTypes.Add(new FileTypeData(".wph", "Phoenix BIOS File"));
            //fileTypes.Add(new FileTypeData(".8xu", "TI-83 and TI-84 Plus Operating System File"));
            //fileTypes.Add(new FileTypeData(".adml", "Group Policy Language-Specific Administrative Template"));
            //fileTypes.Add(new FileTypeData(".mbn", "Multi Boot Image"));
            //fileTypes.Add(new FileTypeData(".metadata_never_index", "Spotlight Never Index File"));
            //fileTypes.Add(new FileTypeData(".vgd", "Generic CADD VGA Driver"));
            //fileTypes.Add(new FileTypeData(".wer", "Windows Error Report"));
            //fileTypes.Add(new FileTypeData(".atahd", "ATA Hard Drive Flag File"));
            //fileTypes.Add(new FileTypeData(".cht", "Windows Chinese Traditional Noise-Word List File"));
            //fileTypes.Add(new FileTypeData(".fid", "Microsoft Catalog Indexing Service File"));
            //fileTypes.Add(new FileTypeData(".hsh", "Windows Catalog Search Index File"));
            //fileTypes.Add(new FileTypeData(".ps2", "Microsoft Search Catalog Index File"));
            //fileTypes.Add(new FileTypeData(".str", "Windows Screensaver File"));
            //fileTypes.Add(new FileTypeData(".evtx", "Windows 7 Event Log File"));
            //fileTypes.Add(new FileTypeData(".crash", "Mac OS X Crash Log File"));
            //fileTypes.Add(new FileTypeData(".dfu", "iOS DFU File"));
            //fileTypes.Add(new FileTypeData(".ruf", "Samsung DVD and Blu-ray Player Firmware File"));
            //fileTypes.Add(new FileTypeData(".automaticdestination", "-ms	Windows Jump List File"));
            //fileTypes.Add(new FileTypeData(".nbh", "ROM Update Utility Image File"));
            //fileTypes.Add(new FileTypeData(".sb", "Slax Bundle"));
            //fileTypes.Add(new FileTypeData(".bk1", "Windows Indexing Service File"));
            //fileTypes.Add(new FileTypeData(".wpx", "Printer Description File"));
            //fileTypes.Add(new FileTypeData(".ifw", "INTUS Firmware File"));
            //fileTypes.Add(new FileTypeData(".iptheme", "IconPackager Raw Theme File"));
            //fileTypes.Add(new FileTypeData(".mem", "Parallels Desktop Memory Dump File"));
            //fileTypes.Add(new FileTypeData(".rco", "PlayStation Portable Resource File"));
            //fileTypes.Add(new FileTypeData(".spx", "System Profiler XML Report"));
            //fileTypes.Add(new FileTypeData(".qky", "Quirky Kernel"));
            //fileTypes.Add(new FileTypeData(".tha", "Windows Thai Noise-Words List File"));
            //fileTypes.Add(new FileTypeData(".pfx", "PKCS #12 Certificate File"));
            //fileTypes.Add(new FileTypeData(".dss", "DCC Active Designer File"));
            //fileTypes.Add(new FileTypeData(".adv", "Audio Driver File"));
            //fileTypes.Add(new FileTypeData(".ps1", "Microsoft Indexing Service Data File"));
            //fileTypes.Add(new FileTypeData(".rs", "Windows Rating System File"));
            //fileTypes.Add(new FileTypeData(".evt", "Windows Event Viewer Log File"));
            //fileTypes.Add(new FileTypeData(".idi", "EVA Controller Event Log"));
            //fileTypes.Add(new FileTypeData(".kbd", "Keyboard Layout Script"));
            //fileTypes.Add(new FileTypeData(".mydocs", "Send To My Documents"));
            //fileTypes.Add(new FileTypeData(".webpnp", "Web Point and Print File"));
            //fileTypes.Add(new FileTypeData(".3fs", "Puppy Linux Save State File"));
            //fileTypes.Add(new FileTypeData(".73u", "TI-73 Explorer Operating System File"));
            //fileTypes.Add(new FileTypeData(".aos", "ARCHOS PCtablet Firmware File"));
            //fileTypes.Add(new FileTypeData(".cap", "ASUS BIOS Update File"));
            //fileTypes.Add(new FileTypeData(".cdmp", "WCS Device Model Profile"));
            //fileTypes.Add(new FileTypeData(".cpq", "Compaq OEM Disc Configuration File"));
            //fileTypes.Add(new FileTypeData(".diagcfg", "Troubleshooting Pack Configuration File"));
            //fileTypes.Add(new FileTypeData(".diagpkg", "Troubleshooting Pack File"));
            //fileTypes.Add(new FileTypeData(".emerald", "Emerald Theme"));
            //fileTypes.Add(new FileTypeData(".ffa", "Find Fast Status File"));
            //fileTypes.Add(new FileTypeData(".ffl", "Find Fast Document List"));
            //fileTypes.Add(new FileTypeData(".ffo", "Find Fast Document Properties Cache"));
            //fileTypes.Add(new FileTypeData(".ftg", "Full Text Group"));
            //fileTypes.Add(new FileTypeData(".fts", "Full Text Search"));
            //fileTypes.Add(new FileTypeData(".gmmp", "WCS Gamut Map Model Profile"));
            //fileTypes.Add(new FileTypeData(".internetconnect", "Apple Internet Connect Document"));
            //fileTypes.Add(new FileTypeData(".ipod", "Rockbox Firmware File"));
            //fileTypes.Add(new FileTypeData(".mod", "GRUB Module"));
            //fileTypes.Add(new FileTypeData(".mui_cccd5ae0", "Hid User Library"));
            //fileTypes.Add(new FileTypeData(".networkconnect", "Apple Network Connect Document"));
            //fileTypes.Add(new FileTypeData(".panic", "Kernel Panic File"));
            //fileTypes.Add(new FileTypeData(".printerexport", "Windows Printer Migration File"));
            //fileTypes.Add(new FileTypeData(".scap", "EFI Firmware File"));
            //fileTypes.Add(new FileTypeData(".schemas", "GConf Schema Definition File"));
            //fileTypes.Add(new FileTypeData(".sdt", "Siemens Desktop Theme File"));
            //fileTypes.Add(new FileTypeData(".s", ".0	Unix Shared Library File"));
            //fileTypes.Add(new FileTypeData(".tdz", "Drobo Firmware File"));
            //fileTypes.Add(new FileTypeData(".xfb", "Xserve RAID Firmware Binary File"));
            //fileTypes.Add(new FileTypeData(".dlx", "Renamed DLL File"));
            //fileTypes.Add(new FileTypeData(".grl", "Windows Update Status File"));
            //fileTypes.Add(new FileTypeData(".pid", "Creative Driver File"));
            //fileTypes.Add(new FileTypeData(".fx", "ReadyBoot Trace File"));
            //fileTypes.Add(new FileTypeData(".bud", "Binary Printer Description File"));
            //fileTypes.Add(new FileTypeData(".ime", "Windows Input Method Editor File"));
            //fileTypes.Add(new FileTypeData(".rc2", "Samsung Mobile Device Firmware File"));
            //fileTypes.Add(new FileTypeData(".xr", "-ms	Microsoft Security Certificate"));
            //fileTypes.Add(new FileTypeData(".dyc", "Xerox Printer Driver Configuration File"));
            //fileTypes.Add(new FileTypeData(".jpn", "Windows Japanese Noise-Word List File"));
            //fileTypes.Add(new FileTypeData(".ann", "Help Annotations"));
            //fileTypes.Add(new FileTypeData(".bmk", "Help Bookmarks"));
            //fileTypes.Add(new FileTypeData(".ppm", "Post Programmable Memory File"));
            //fileTypes.Add(new FileTypeData(".chs", "Windows Chinese Noise-Word List File"));
            //fileTypes.Add(new FileTypeData(".ioplist", "Mac OS X IOPLIST File"));
            //fileTypes.Add(new FileTypeData(".its", "Internet Document Set"));
            //fileTypes.Add(new FileTypeData(".kor", "Windows Korean Noise-Words List File"));
            //fileTypes.Add(new FileTypeData(".lfs", "Samsung Phone params.lfs File"));
            //fileTypes.Add(new FileTypeData(".me", "Puppy Linux Partition Flag File"));

            return fileTypes;
        }
    }
}
