using DriveIndexer.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DriveIndexer.Database
{
    public class DefaultFileTypesCode
    {
        // http://fileinfo.com/filetypes/video
        public static List<FileTypeData> DefaultTypes()
        {
            List<FileTypeData> fileTypes = new List<FileTypeData>();

            fileTypes.Add(new FileTypeData(".cs", "Visual C# Source Code File"));
            fileTypes.Add(new FileTypeData(".rc", "Resource Script"));
            fileTypes.Add(new FileTypeData(".def", "Module-Definition File"));
            fileTypes.Add(new FileTypeData(".s19", "Motorola S19 File Record"));
            fileTypes.Add(new FileTypeData(".vbp", "Visual Basic Project File"));
            fileTypes.Add(new FileTypeData(".w32", "Win32 Makefile"));
            fileTypes.Add(new FileTypeData(".hpp", "C++ Header File"));
            fileTypes.Add(new FileTypeData(".hbs", "Handlebars Template"));
            fileTypes.Add(new FileTypeData(".yml", "YAML Document"));
            fileTypes.Add(new FileTypeData(".dproj", "Delphi Project"));
            fileTypes.Add(new FileTypeData(".erb", "Ruby ERB Script"));
            fileTypes.Add(new FileTypeData(".fsproj", "Visual F# Project File"));
            fileTypes.Add(new FileTypeData(".jspf", "Java Server Page Fragment"));
            fileTypes.Add(new FileTypeData(".pbxuser", "Xcode Project User Data File"));
            fileTypes.Add(new FileTypeData(".proto", "Protocol Buffer File"));
            fileTypes.Add(new FileTypeData(".vbproj", "Visual Studio Visual Basic Project"));
            fileTypes.Add(new FileTypeData(".xq", "XQuery File"));
            fileTypes.Add(new FileTypeData(".cod", "Compiled Source Code"));
            fileTypes.Add(new FileTypeData(".ctp", "CakePHP Template"));
            fileTypes.Add(new FileTypeData(".ipr", "InstallShield Professional Project File"));
            fileTypes.Add(new FileTypeData(".mk", "Makefile"));
            fileTypes.Add(new FileTypeData(".nls", "NetLogo Source File"));
            fileTypes.Add(new FileTypeData(".pb", "PureBasic Source File"));
            fileTypes.Add(new FileTypeData(".pika", "Pika Software Builder Project File"));
            fileTypes.Add(new FileTypeData(".resources", "Visual Studio Resource File"));
            fileTypes.Add(new FileTypeData(".suo", "Visual Studio Solution User Options File"));
            fileTypes.Add(new FileTypeData(".ui", "User Interface File"));
            fileTypes.Add(new FileTypeData(".jav", "Java Source File"));
            fileTypes.Add(new FileTypeData(".appx", "Windows 8 App Package"));
            fileTypes.Add(new FileTypeData(".dtd", "Document Type Definition File"));
            fileTypes.Add(new FileTypeData(".class", "Java Class File"));
            fileTypes.Add(new FileTypeData(".sb", "Scratch Project File"));
            fileTypes.Add(new FileTypeData(".ise", "InstallShield Express Project File"));
            fileTypes.Add(new FileTypeData(".trx", "Visual Studio Test Results File"));
            fileTypes.Add(new FileTypeData(".vcproj", "Visual C++ Project File"));
            fileTypes.Add(new FileTypeData(".kv", "Kivy Language File"));
            fileTypes.Add(new FileTypeData(".gmk", "Game Maker Project File"));
            fileTypes.Add(new FileTypeData(".mo", "Machine Object File"));
            fileTypes.Add(new FileTypeData(".lua", "Lua Source File"));
            fileTypes.Add(new FileTypeData(".sln", "Visual Studio Solution File"));
            fileTypes.Add(new FileTypeData(".ads", "Ada Specification File"));
            fileTypes.Add(new FileTypeData(".bet", "BETA Source File"));
            fileTypes.Add(new FileTypeData(".cd", "Visual Studio Class Diagram"));
            fileTypes.Add(new FileTypeData(".cp", "Captivate Source File"));
            fileTypes.Add(new FileTypeData(".i", "Visual Studio Intermediate File"));
            fileTypes.Add(new FileTypeData(".pyw", "Python GUI Source File"));
            fileTypes.Add(new FileTypeData(".qpr", "FoxPro Generated Query Program"));
            fileTypes.Add(new FileTypeData(".rc2", "Visual Studio Resources File"));
            fileTypes.Add(new FileTypeData(".s", "Source Code File"));
            fileTypes.Add(new FileTypeData(".smali", "Android Smali Assembly Language File"));
            fileTypes.Add(new FileTypeData(".vc", "Verge Code File"));
            fileTypes.Add(new FileTypeData(".xaml", "XAML File"));
            fileTypes.Add(new FileTypeData(".xt", "Xdebug Trace File"));
            fileTypes.Add(new FileTypeData(".b", "BuRg3r Definition File"));
            fileTypes.Add(new FileTypeData(".xap", "XACT Project"));
            fileTypes.Add(new FileTypeData(".pas", "Delphi Unit Source File"));
            fileTypes.Add(new FileTypeData(".set", "Alpha Five Set Data Dictionary File"));
            fileTypes.Add(new FileTypeData(".sb2", "Scratch 2.0 Project File"));
            fileTypes.Add(new FileTypeData(".ocx", "ActiveX Control"));
            fileTypes.Add(new FileTypeData(".vbg", "Visual Basic Project Group File"));
            fileTypes.Add(new FileTypeData(".cpp", "C++ Source Code File"));
            fileTypes.Add(new FileTypeData(".asi", "Alpha Five Variable File"));
            fileTypes.Add(new FileTypeData(".ex", "Euphoria Source Code"));
            fileTypes.Add(new FileTypeData(".java", "Java Source Code File"));
            fileTypes.Add(new FileTypeData(".ism", "InstallShield Project File"));
            fileTypes.Add(new FileTypeData(".b", "BASIC Source File"));
            fileTypes.Add(new FileTypeData(".res", "Windows Resource File"));
            fileTypes.Add(new FileTypeData(".py", "Python Script"));
            fileTypes.Add(new FileTypeData(".c", "C/C++ Source Code File"));
            fileTypes.Add(new FileTypeData(".fla", "Adobe Flash Animation"));
            fileTypes.Add(new FileTypeData(".sh", "Bash Shell Script"));
            fileTypes.Add(new FileTypeData(".pwn", "Pawn Source Code File"));
            fileTypes.Add(new FileTypeData(".res", "C++ Complied Resource Script"));
            fileTypes.Add(new FileTypeData(".abc", "ActionScript Byte Code File"));
            fileTypes.Add(new FileTypeData(".dex", "Dalvik Executable File"));
            fileTypes.Add(new FileTypeData(".r", "R Script File"));
            fileTypes.Add(new FileTypeData(".scratch", "Scratch Project File"));
            fileTypes.Add(new FileTypeData(".swift", "Swift Source Code File"));
            fileTypes.Add(new FileTypeData(".as3proj", "FlashDevelop ActionScript 3 Project File"));
            fileTypes.Add(new FileTypeData(".bbprojectd", "BBEdit Project Document"));
            fileTypes.Add(new FileTypeData(".cp", "Xcode C++ Source File"));
            fileTypes.Add(new FileTypeData(".dcproj", "Dashcode Project"));
            fileTypes.Add(new FileTypeData(".fsx", "Visual F# Script File"));
            fileTypes.Add(new FileTypeData(".ftl", "FreeMarker Template File"));
            fileTypes.Add(new FileTypeData(".gfar", "Greenfoot Archive"));
            fileTypes.Add(new FileTypeData(".groupproj", "Delphi Project Group File"));
            fileTypes.Add(new FileTypeData(".markdown", "Markdown Documentation File"));
            fileTypes.Add(new FileTypeData(".mshc", "Microsoft Help Container File"));
            fileTypes.Add(new FileTypeData(".pbj", "Pixel Bender Bytecode File"));
            fileTypes.Add(new FileTypeData(".pch", "Precompiled Header File"));
            fileTypes.Add(new FileTypeData(".playground", "Xcode Playground File"));
            fileTypes.Add(new FileTypeData(".psm1", "Windows PowerShell Script Module File"));
            fileTypes.Add(new FileTypeData(".rbw", "Ruby Script"));
            fileTypes.Add(new FileTypeData(".rexx", "Rexx Source File"));
            fileTypes.Add(new FileTypeData(".rkt", "Racket Source Code File"));
            fileTypes.Add(new FileTypeData(".sdef", "AppleScript Dictionary Document"));
            fileTypes.Add(new FileTypeData(".v", "Verilog Source Code File"));
            fileTypes.Add(new FileTypeData(".vdproj", "Visual Studio Setup and Deployment Project"));
            fileTypes.Add(new FileTypeData(".vtm", "Visual Tool Markup Language Document"));
            fileTypes.Add(new FileTypeData(".wixproj", "WiX Project File"));
            fileTypes.Add(new FileTypeData(".4db", "4th Dimension Database Structure File"));
            fileTypes.Add(new FileTypeData(".apa", "RSView Development Project Archive"));
            fileTypes.Add(new FileTypeData(".arsc", "Android Package Resource File"));
            fileTypes.Add(new FileTypeData(".asvf", "Asphyre Sphinx Archive File"));
            fileTypes.Add(new FileTypeData(".bbc", "BBC BASIC Data File"));
            fileTypes.Add(new FileTypeData(".bluej", "BlueJ Package File"));
            fileTypes.Add(new FileTypeData(".cc", "C++ Source Code File"));
            fileTypes.Add(new FileTypeData(".d", "D Source Code File"));
            fileTypes.Add(new FileTypeData(".dcp", "Delphi Compiled Package"));
            fileTypes.Add(new FileTypeData(".diff", "Patch File"));
            fileTypes.Add(new FileTypeData(".dox", "Visual Basic Binary UserDocument"));
            fileTypes.Add(new FileTypeData(".edmx", "ADO.NET Entity Data Model Designer File"));
            fileTypes.Add(new FileTypeData(".erl", "Erlang Source Code File"));
            fileTypes.Add(new FileTypeData(".fbp", "wxFormBuilder Project"));
            fileTypes.Add(new FileTypeData(".for", "Fortran 77 Source File"));
            fileTypes.Add(new FileTypeData(".fxc", "FilePackager Configuration"));
            fileTypes.Add(new FileTypeData(".gitignore", "Git Ignore File"));
            fileTypes.Add(new FileTypeData(".gmx", "GameMaker File"));
            fileTypes.Add(new FileTypeData(".hs", "Haskell Script"));
            fileTypes.Add(new FileTypeData(".idt", "Windows Installer Database Text Archive File"));
            fileTypes.Add(new FileTypeData(".ilk", "Incremental Linking File"));
            fileTypes.Add(new FileTypeData(".kdevprj", "KDevelop Project File"));
            fileTypes.Add(new FileTypeData(".lgo", "Logo Instructions File"));
            fileTypes.Add(new FileTypeData(".m4", "Macro Processor Library"));
            fileTypes.Add(new FileTypeData(".mf", "Java Manifest File"));
            fileTypes.Add(new FileTypeData(".ml", "ML Source Code File"));
            fileTypes.Add(new FileTypeData(".mom", "Managed Object Model"));
            fileTypes.Add(new FileTypeData(".mshi", "Microsoft Help Index File"));
            fileTypes.Add(new FileTypeData(".mss", "Microprocessor Software Specification File"));
            fileTypes.Add(new FileTypeData(".mxml", "Flex MXML Component"));
            fileTypes.Add(new FileTypeData(".myapp", "Visual Studio Application XML File"));
            fileTypes.Add(new FileTypeData(".nuspec", "NuGet Specification File"));
            fileTypes.Add(new FileTypeData(".pri", "Windows Compiled Resources File"));
            fileTypes.Add(new FileTypeData(".psc", "Papyrus Script"));
            fileTypes.Add(new FileTypeData(".pyd", "Python Dynamic Module"));
            fileTypes.Add(new FileTypeData(".rav", "Rave Reports Project File"));
            fileTypes.Add(new FileTypeData(".rpy", "Python Script"));
            fileTypes.Add(new FileTypeData(".so", "Shared Library"));
            fileTypes.Add(new FileTypeData(".ssi", "Adobe Dreamweaver Server Side Include File"));
            fileTypes.Add(new FileTypeData(".vhd", "VHDL Source File"));
            fileTypes.Add(new FileTypeData(".wdgt", "Adobe Captivate Widget File"));
            fileTypes.Add(new FileTypeData(".wdp", "Windev Project File"));
            fileTypes.Add(new FileTypeData(".workspace", "Code::Blocks Workspace File"));
            fileTypes.Add(new FileTypeData(".xamlx", "Visual Studio Workflow Service File"));
            fileTypes.Add(new FileTypeData(".xcappdata", "Xcode App Data File"));
            fileTypes.Add(new FileTypeData(".adb", "Ada Body File"));
            fileTypes.Add(new FileTypeData(".appxsym", "Windows 8 App Package Symbols File"));
            fileTypes.Add(new FileTypeData(".dev", "Dev-C++ Project File"));
            fileTypes.Add(new FileTypeData(".filters", "Visual C++ Project Filters File"));
            fileTypes.Add(new FileTypeData(".fpp", "Fortran Source Code"));
            fileTypes.Add(new FileTypeData(".p6", "Perl 6 Source Code File"));
            fileTypes.Add(new FileTypeData(".psd1", "Windows PowerShell Data File"));
            fileTypes.Add(new FileTypeData(".sex", "Alpha Five Set Data Dictionary Index File"));
            fileTypes.Add(new FileTypeData(".pas", "Pascal Source File"));
            fileTypes.Add(new FileTypeData(".as", "ActionScript File"));
            fileTypes.Add(new FileTypeData(".exp", "Symbols Export File"));
            fileTypes.Add(new FileTypeData(".go", "Go Source Code File"));
            fileTypes.Add(new FileTypeData(".swc", "Flex Components Archive"));
            fileTypes.Add(new FileTypeData(".asc", "ActionScript Communication File"));
            fileTypes.Add(new FileTypeData(".au3", "AutoIt v3 Script"));
            fileTypes.Add(new FileTypeData(".ino", "Arduino Sketch File"));
            fileTypes.Add(new FileTypeData(".po", "Portable Object"));
            fileTypes.Add(new FileTypeData(".vcxproj", "Visual C++ Project"));
            fileTypes.Add(new FileTypeData(".patch", "Patch File"));
            fileTypes.Add(new FileTypeData(".rul", "InstallShield Rules File"));
            fileTypes.Add(new FileTypeData(".xbf", "XAML Binary File"));
            fileTypes.Add(new FileTypeData(".$01", "DOS Pipe File"));
            fileTypes.Add(new FileTypeData(".md", "Markdown Documentation File"));
            fileTypes.Add(new FileTypeData(".applet", "Eclipse Java Applet Policy File"));
            fileTypes.Add(new FileTypeData(".csproj", "Visual Studio C# Project"));
            fileTypes.Add(new FileTypeData(".capx", "Construct Compressed Project File"));
            fileTypes.Add(new FileTypeData(".w", "OpenEdge Architect Source Code File"));
            fileTypes.Add(new FileTypeData(".bpl", "Borland Package Library"));
            fileTypes.Add(new FileTypeData(".o", "Compiled Object File"));
            fileTypes.Add(new FileTypeData(".xsd", "XML Schema Definition"));
            fileTypes.Add(new FileTypeData(".aps", "Visual C++ Resource File"));
            fileTypes.Add(new FileTypeData(".c", "Lite-C Script"));
            fileTypes.Add(new FileTypeData(".caf", "CryENGINE Character Animation File"));
            fileTypes.Add(new FileTypeData(".am", "Automake Makefile Template"));
            fileTypes.Add(new FileTypeData(".nib", "Interface Builder User Interface File"));
            fileTypes.Add(new FileTypeData(".pro", "Qt Project File"));
            fileTypes.Add(new FileTypeData("0", "001	Multimedia Fusion Backup File"));
            fileTypes.Add(new FileTypeData(".aia", "MIT App Inventor Source Code File"));
            fileTypes.Add(new FileTypeData(".am7", "AutoPlay Media Studio 7 Project"));
            fileTypes.Add(new FileTypeData(".cu", "CUDA Source Code File"));
            fileTypes.Add(new FileTypeData(".dpl", "Delphi Package Library"));
            fileTypes.Add(new FileTypeData(".framework", "Mac OS X Application Framework"));
            fileTypes.Add(new FileTypeData(".frx", "Visual Basic Binary Form File"));
            fileTypes.Add(new FileTypeData(".gsproj", "GameSalad Windows Project File"));
            fileTypes.Add(new FileTypeData(".ymp", "YaST Metapackage File"));
            fileTypes.Add(new FileTypeData(".lrf", "Microsoft Linker Response File"));
            fileTypes.Add(new FileTypeData(".yml2", "YML Script"));
            fileTypes.Add(new FileTypeData(".dcr", "Delphi Component Resource File"));
            fileTypes.Add(new FileTypeData(".config", "Configuration File"));
            fileTypes.Add(new FileTypeData(".m", "Objective-C Implementation File"));
            fileTypes.Add(new FileTypeData(".vdm", "VDM Specification File"));
            fileTypes.Add(new FileTypeData(".iml", "IntelliJ IDEA Module"));
            fileTypes.Add(new FileTypeData(".ru", "Java Russian Font Properties File"));
            fileTypes.Add(new FileTypeData(".r", "Rez Source Code File"));
            fileTypes.Add(new FileTypeData(".resx", ".NET Managed Resources File"));
            fileTypes.Add(new FileTypeData(".cxp", "CX-Programmer Project File"));
            fileTypes.Add(new FileTypeData(".dbml", "Visual Studio OR Design File"));
            fileTypes.Add(new FileTypeData(".dec", "Declaration File"));
            fileTypes.Add(new FileTypeData(".fpm", "FPS Creator Map File"));
            fileTypes.Add(new FileTypeData(".gm81", "Game Maker 8.1 Project File"));
            fileTypes.Add(new FileTypeData(".idb", "Visual Studio Intermediate Debug File"));
            fileTypes.Add(new FileTypeData(".ipr", "IntelliJ IDEA Project File"));
            fileTypes.Add(new FileTypeData(".livecode", "LiveCode Stack File"));
            fileTypes.Add(new FileTypeData(".nxc", "Not eXactly C Source Code File"));
            fileTypes.Add(new FileTypeData(".oca", "Custom Control Library Type File"));
            fileTypes.Add(new FileTypeData(".ph", "Perl Header File"));
            fileTypes.Add(new FileTypeData(".pm", "Perl Module"));
            fileTypes.Add(new FileTypeData(".pot", "Portable Object File"));
            fileTypes.Add(new FileTypeData(".storyboard", "Interface Builder Storyboard Document"));
            fileTypes.Add(new FileTypeData(".t", "Turing Source Code File"));
            fileTypes.Add(new FileTypeData(".tds", "Turbo Debugger Symbols File"));
            fileTypes.Add(new FileTypeData(".uml", "UML Data Object Model"));
            fileTypes.Add(new FileTypeData(".yaml", "YAML Document"));
            fileTypes.Add(new FileTypeData(".ypr", "BYOB Project File"));
            fileTypes.Add(new FileTypeData(".actx", "DS Game Maker Action Description File"));
            fileTypes.Add(new FileTypeData(".alm", "Alpha Five Library"));
            fileTypes.Add(new FileTypeData(".alp", "AnyLogic Project File"));
            fileTypes.Add(new FileTypeData(".basex", "BaseX Data File"));
            fileTypes.Add(new FileTypeData(".btn", "AutoPlay Media Studio Button File"));
            fileTypes.Add(new FileTypeData(".ddm", "Alpha Five Data Dictionary Memo File"));
            fileTypes.Add(new FileTypeData(".dsk", "Borland Project Desktop File"));
            fileTypes.Add(new FileTypeData(".dsym", "Xcode Debug Symbols File"));
            fileTypes.Add(new FileTypeData(".el", "Emacs Lisp Code File"));
            fileTypes.Add(new FileTypeData(".fsl", "Form•Z Script"));
            fileTypes.Add(new FileTypeData(".gml", "Game Maker Language File"));
            fileTypes.Add(new FileTypeData(".i", "INTERCAL Source File"));
            fileTypes.Add(new FileTypeData(".jed", "Xilinx JEDEC Programming File"));
            fileTypes.Add(new FileTypeData(".lis", "VAX Program Listing"));
            fileTypes.Add(new FileTypeData(".nim", "Nimrod Source Code File"));
            fileTypes.Add(new FileTypeData(".pmq", "Microsoft Target Analyzer File"));
            fileTypes.Add(new FileTypeData(".project", "Eclipse Project Settings File"));
            fileTypes.Add(new FileTypeData(".rs", "Rust Source Code File"));
            fileTypes.Add(new FileTypeData(".tcc", "C++ Source Code File"));
            fileTypes.Add(new FileTypeData(".vdm", "VEDIT Macro File"));
            fileTypes.Add(new FileTypeData(".vic", "ViziGen Code Import Mappings File"));
            fileTypes.Add(new FileTypeData(".vpc", "ViziGen Configuration File"));
            fileTypes.Add(new FileTypeData(".vsct", "Visual Studio Command Table"));
            fileTypes.Add(new FileTypeData(".worksheet", "BBEdit Shell Worksheet File"));
            fileTypes.Add(new FileTypeData(".wowproj", "AddOn Studio Project File"));
            fileTypes.Add(new FileTypeData(".rb", "Ruby Source Code"));
            fileTypes.Add(new FileTypeData(".lol", "LOLCODE Source Code FIle"));
            fileTypes.Add(new FileTypeData(".h", "C/C++/Objective-C Header File"));
            fileTypes.Add(new FileTypeData(".pde", "Arduino Sketch"));
            fileTypes.Add(new FileTypeData(".pl", "Perl Script"));
            fileTypes.Add(new FileTypeData(".dpr", "Delphi Project"));
            fileTypes.Add(new FileTypeData(".fs", "Visual F# Source File"));
            fileTypes.Add(new FileTypeData(".gem", "RubyGems Package"));
            fileTypes.Add(new FileTypeData(".appxupload", "Windows 8 App Upload Package"));
            fileTypes.Add(new FileTypeData(".cls", "Program Class File"));
            fileTypes.Add(new FileTypeData(".dmd", "SQL Developer Data Modeler File"));
            fileTypes.Add(new FileTypeData(".mcp", "CodeWarrior Project"));
            fileTypes.Add(new FileTypeData(".mpr", "FoxPro Generated Menu Program"));
            fileTypes.Add(new FileTypeData(".sas", "SAS Program File"));
            fileTypes.Add(new FileTypeData(".swd", "Flash Debug File"));
            fileTypes.Add(new FileTypeData(".targets", "MSBuild Targets File"));
            fileTypes.Add(new FileTypeData(".y", "Yacc Source File"));
            fileTypes.Add(new FileTypeData(".cap", "Construct Game Development File"));
            fileTypes.Add(new FileTypeData(".frm", "Visual Basic Text Form"));
            fileTypes.Add(new FileTypeData(".lsp", "Lisp Program Source Code File"));
            fileTypes.Add(new FileTypeData(".cxt", "CX-Programmer Project Text File"));
            fileTypes.Add(new FileTypeData(".asm", "Visual Studio Assembler Source Code File"));
            fileTypes.Add(new FileTypeData(".gs", "Google Apps Script"));
            fileTypes.Add(new FileTypeData(".mm", "Objective-C++ Source File"));
            fileTypes.Add(new FileTypeData(".dfm", "Delphi Form"));
            fileTypes.Add(new FileTypeData(".mrt", "Stimulsoft Report File"));
            fileTypes.Add(new FileTypeData(".scc", "SourceSafe Source Code Control File"));
            fileTypes.Add(new FileTypeData(".dep", "Windows Dependency File"));
            fileTypes.Add(new FileTypeData(".x", "Lex Source Code File"));
            fileTypes.Add(new FileTypeData(".sc", "SuperCollider Source Code File"));
            fileTypes.Add(new FileTypeData(".cxx", "C++ Source Code File"));
            fileTypes.Add(new FileTypeData(".xsx", "Visual Studio XML Schema Layout File"));
            fileTypes.Add(new FileTypeData(".src", "Source Code"));
            fileTypes.Add(new FileTypeData(".aml", "Arc Macro Language File"));
            fileTypes.Add(new FileTypeData(".setup", "CryENGINE Character Setup File"));
            fileTypes.Add(new FileTypeData(".ple", "Messenger Plus! Live Encrypted Log File"));
            fileTypes.Add(new FileTypeData(".sb", "Small Basic Source Code File"));
            fileTypes.Add(new FileTypeData(".p", "Python Pickle File"));
            fileTypes.Add(new FileTypeData(".xcodeproj", "Xcode Project"));
            fileTypes.Add(new FileTypeData(".m", "MATLAB Source Code File"));
            fileTypes.Add(new FileTypeData(".4th", "Forth Language File"));
            fileTypes.Add(new FileTypeData(".a", "Static Library"));
            fileTypes.Add(new FileTypeData(".addin", "Visual Studio Add-in Definition File"));
            fileTypes.Add(new FileTypeData(".alb", "Alpha Five Library"));
            fileTypes.Add(new FileTypeData(".am4", "AutoPlay Media Studio 4 Project File"));
            fileTypes.Add(new FileTypeData(".am5", "AutoPlay Media Studio 5 Project File"));
            fileTypes.Add(new FileTypeData(".am6", "AutoPlay Media Studio 6 Project"));
            fileTypes.Add(new FileTypeData(".ane", "Adobe AIR Native Extension"));
            fileTypes.Add(new FileTypeData(".ap_", "ADT Android Developer Package"));
            fileTypes.Add(new FileTypeData(".artproj", "Artifacts Project"));
            fileTypes.Add(new FileTypeData(".as2proj", "FlashDevelop ActionScript 2 Project File"));
            fileTypes.Add(new FileTypeData(".asm", "Assembly Language Source Code File"));
            fileTypes.Add(new FileTypeData(".awk", "AWK Script"));
            fileTypes.Add(new FileTypeData(".bas", "BASIC Source Code File"));
            fileTypes.Add(new FileTypeData(".bb", "Blitz Source Code File"));
            fileTypes.Add(new FileTypeData(".bbproject", "BBEdit Project File"));
            fileTypes.Add(new FileTypeData(".bcp", "Borland C++ Makefile"));
            fileTypes.Add(new FileTypeData(".bdsproj", "Borland Developer Studio Project"));
            fileTypes.Add(new FileTypeData(".brx", "BREW Application Resource File"));
            fileTypes.Add(new FileTypeData(".buildsetting", "Twixl Publisher Builder Build Setting"));
            fileTypes.Add(new FileTypeData(".caproj", "Construct Project File"));
            fileTypes.Add(new FileTypeData(".cbp", "Code::Blocks Project File"));
            fileTypes.Add(new FileTypeData(".ccgame", "XNA Creators Club Game Package"));
            fileTypes.Add(new FileTypeData(".ccn", "Compressed Multimedia Fusion File"));
            fileTypes.Add(new FileTypeData(".ccp", "CodeCharge Studio Page File"));
            fileTypes.Add(new FileTypeData(".ccs", "CodeCharge Studio Project File"));
            fileTypes.Add(new FileTypeData(".cdf", "CryENGINE Character Definition File"));
            fileTypes.Add(new FileTypeData(".cfc", "ColdFusion Component File"));
            fileTypes.Add(new FileTypeData(".clips", "Coda Clips File"));
            fileTypes.Add(new FileTypeData(".clw", "Visual C++ ClassWizard File"));
            fileTypes.Add(new FileTypeData(".cob", "COBOL Source Code File"));
            fileTypes.Add(new FileTypeData(".csn", "Adobe Code Snippet Document"));
            fileTypes.Add(new FileTypeData(".csp", "Caché Server Page"));
            fileTypes.Add(new FileTypeData(".csx", "Visual C# Script"));
            fileTypes.Add(new FileTypeData(".ctl", "Visual Basic UserControl Object File"));
            fileTypes.Add(new FileTypeData(".ctxt", "BlueJ Context File"));
            fileTypes.Add(new FileTypeData(".cvsrc", "CVS Command File"));
            fileTypes.Add(new FileTypeData(".dbo", "DarkBASIC Object"));
            fileTypes.Add(new FileTypeData(".dbpro", "DarkBASIC Professional Project File"));
            fileTypes.Add(new FileTypeData(".dbproj", "Visual Studio Database Project File"));
            fileTypes.Add(new FileTypeData(".dcu", "Delphi Compiled Unit"));
            fileTypes.Add(new FileTypeData(".dcuil", "Delphi .NET Compiled Unit File"));
            fileTypes.Add(new FileTypeData(".deviceids", "Device Identification FIle"));
            fileTypes.Add(new FileTypeData(".df1", "Omnis Native Datafile"));
            fileTypes.Add(new FileTypeData(".dgml", "Visual Studio Directed Graph Document"));
            fileTypes.Add(new FileTypeData(".dgsl", "Visual Shader Graph File"));
            fileTypes.Add(new FileTypeData(".dm1", "ER/Studio Data Model File"));
            fileTypes.Add(new FileTypeData(".dob", "Visual Basic UserDocument"));
            fileTypes.Add(new FileTypeData(".dpkw", "Delphi Package"));
            fileTypes.Add(new FileTypeData(".dsgm", "DS Game Maker Project"));
            fileTypes.Add(new FileTypeData(".edml", "Adobe Extension Data Markup Language Document"));
            fileTypes.Add(new FileTypeData(".entitlements", "Mac App Sandboxing Entitlements File"));
            fileTypes.Add(new FileTypeData(".eql", "Embedded SQL File"));
            fileTypes.Add(new FileTypeData(".exw", "Euphoria Source code File"));
            fileTypes.Add(new FileTypeData(".f", "Fortran Source Code"));
            fileTypes.Add(new FileTypeData(".f90", "Fortran 90 Source Code File"));
            fileTypes.Add(new FileTypeData(".fbz7", "Compressed FinalBuilder 7 Project"));
            fileTypes.Add(new FileTypeData(".fgl", "Fifth Generation Language Source File"));
            fileTypes.Add(new FileTypeData(".forth", "Forth Language File"));
            fileTypes.Add(new FileTypeData(".fsi", "Visual F# Signature File"));
            fileTypes.Add(new FileTypeData(".fsproj", "FireStarter Project File"));
            fileTypes.Add(new FileTypeData(".fsscript", "Visual F# Script"));
            fileTypes.Add(new FileTypeData(".ftn", "Fortran Source Code File"));
            fileTypes.Add(new FileTypeData(".fxcproj", "FX Composer Project File"));
            fileTypes.Add(new FileTypeData(".fxl", "FaceFX Language File"));
            fileTypes.Add(new FileTypeData(".fxml", "FXML Source Code File"));
            fileTypes.Add(new FileTypeData(".fxpl", "Adobe Flash FXP Library"));
            fileTypes.Add(new FileTypeData(".gameproj", "GameSalad Project File"));
            fileTypes.Add(new FileTypeData(".gch", "Precompiled Header File"));
            fileTypes.Add(new FileTypeData(".gemspec", "Gem Specification File"));
            fileTypes.Add(new FileTypeData(".gitattributes", "Git Attributes File"));
            fileTypes.Add(new FileTypeData(".gld", "MPLAB C Compiler Linker Script File"));
            fileTypes.Add(new FileTypeData(".gm6", "Game Maker 6 Project File"));
            fileTypes.Add(new FileTypeData(".gmo", "GNU Machine Object File"));
            fileTypes.Add(new FileTypeData(".gorm", "Gorm Interface Resource File"));
            fileTypes.Add(new FileTypeData(".greenfoot", "Greenfoot Project Archive"));
            fileTypes.Add(new FileTypeData(".groovy", "Groovy Source Code File"));
            fileTypes.Add(new FileTypeData(".gs3", "GameStarter File"));
            fileTypes.Add(new FileTypeData(".gszip", "GameSalad Marketplace Asset File"));
            fileTypes.Add(new FileTypeData(".hal", "HansaWorld Application Language File"));
            fileTypes.Add(new FileTypeData(".haml", "Haml Source Code File"));
            fileTypes.Add(new FileTypeData(".has", "Haskell Script"));
            fileTypes.Add(new FileTypeData(".hpf", "High Performance Fortran File"));
            fileTypes.Add(new FileTypeData(".hxx", "C++ Source Code Header File"));
            fileTypes.Add(new FileTypeData(".iconset", "Mac OS X Icon Set Folder"));
            fileTypes.Add(new FileTypeData(".inl", "C++ Inline File"));
            fileTypes.Add(new FileTypeData(".ipch", "Intellisense Precompiled Header File"));
            fileTypes.Add(new FileTypeData(".ist", "InstallShield Project Template File"));
            fileTypes.Add(new FileTypeData(".iwb", "IWBasic Source Code File"));
            fileTypes.Add(new FileTypeData(".iws", "IntelliJ IDEA Web Page"));
            fileTypes.Add(new FileTypeData(".jcp", "JCreator Project File"));
            fileTypes.Add(new FileTypeData(".jic", "JTAG Indirect Configuration File"));
            fileTypes.Add(new FileTypeData(".jsfl", "Flash JavaScript File"));
            fileTypes.Add(new FileTypeData(".kdevelop", "KDevelop Project Data File"));
            fileTypes.Add(new FileTypeData(".kpl", "Kids Programming Language File"));
            fileTypes.Add(new FileTypeData(".lbi", "Dreamweaver Library Item"));
            fileTypes.Add(new FileTypeData(".lbs", "Omnis Library"));
            fileTypes.Add(new FileTypeData(".lds", "Binutils LD Linker Script"));
            fileTypes.Add(new FileTypeData(".lhs", "Literate Haskell Script"));
            fileTypes.Add(new FileTypeData(".licenses", "Visual Studio Licensed Classes File"));
            fileTypes.Add(new FileTypeData(".licx", "Visual Studio License File"));
            fileTypes.Add(new FileTypeData(".lit", "Literate Haskell Script"));
            fileTypes.Add(new FileTypeData(".lproj", "Localized Project Folder"));
            fileTypes.Add(new FileTypeData(".lsproj", "Visual Studio LightSwitch Project"));
            fileTypes.Add(new FileTypeData(".ltb", "LithTech Binary File"));
            fileTypes.Add(new FileTypeData(".luc", "Compiled Lua Source File"));
            fileTypes.Add(new FileTypeData(".lxsproj", "Liquid XML Studio Project File"));
            fileTypes.Add(new FileTypeData(".magik", "Magik Source Code File"));
            fileTypes.Add(new FileTypeData(".mdzip", "MagicDraw Project Archive"));
            fileTypes.Add(new FileTypeData(".mfa", "Multimedia Fusion Development File"));
            fileTypes.Add(new FileTypeData(".mod", "Fortran Module File"));
            fileTypes.Add(new FileTypeData(".msha", "Microsoft Help Asset File"));
            fileTypes.Add(new FileTypeData(".msl", "Mapping Specification Language File"));
            fileTypes.Add(new FileTypeData(".mv", "MivaScript File"));
            fileTypes.Add(new FileTypeData(".nbc", "Next Byte Codes Source Code File"));
            fileTypes.Add(new FileTypeData(".ncb", "Visual C++ IntelliSense Database"));
            fileTypes.Add(new FileTypeData(".ned", "OMNeT++ Network Description File"));
            fileTypes.Add(new FileTypeData(".neko", "Neko Source Code File"));
            fileTypes.Add(new FileTypeData(".nfm", "Delphi .NET Form File"));
            fileTypes.Add(new FileTypeData(".nk", "NUKE Script"));
            fileTypes.Add(new FileTypeData(".nqc", "Not Quite C Source Code File"));
            fileTypes.Add(new FileTypeData(".nsh", "NSIS Header File"));
            fileTypes.Add(new FileTypeData(".nupkg", "NuGet Package"));
            fileTypes.Add(new FileTypeData(".nvv", "NVIDIA Vertex Shader File"));
            fileTypes.Add(new FileTypeData(".nw", "Node-Webkit App Package"));
            fileTypes.Add(new FileTypeData(".octest", "Xcode Objective-C Unit Test Bundle"));
            fileTypes.Add(new FileTypeData(".odl", "Object Description Language File"));
            fileTypes.Add(new FileTypeData(".omo", "OMake Object File"));
            fileTypes.Add(new FileTypeData(".owl", "OWL Source Code File"));
            fileTypes.Add(new FileTypeData(".paw", "Paw Document"));
            fileTypes.Add(new FileTypeData(".pbg", "Pixel Bender Graph File"));
            fileTypes.Add(new FileTypeData(".pbk", "Pixel Bender Kernel File"));
            fileTypes.Add(new FileTypeData(".pbxbtree", "Xcode Auto-Complete File"));
            fileTypes.Add(new FileTypeData(".pcp", "Windows Installer Patch Creation Properties File"));
            fileTypes.Add(new FileTypeData(".pde", "Processing Development Environment Source Code File"));
            fileTypes.Add(new FileTypeData(".pdm", "VB Project Information File"));
            fileTypes.Add(new FileTypeData(".pjx", "FoxPro Project"));
            fileTypes.Add(new FileTypeData(".pkgdef", "Visual Studio Shell File"));
            fileTypes.Add(new FileTypeData(".pkgundef", "Visual Studio Shell File"));
            fileTypes.Add(new FileTypeData(".pl1", "PL/I Source Code"));
            fileTypes.Add(new FileTypeData(".plc", "PL/B Source File"));
            fileTypes.Add(new FileTypeData(".ppc", "Mobile Data Studio Project File"));
            fileTypes.Add(new FileTypeData(".prg", "RAPID Program File"));
            fileTypes.Add(new FileTypeData(".pri", "Qt Project Include File"));
            fileTypes.Add(new FileTypeData(".ptl", "Rational Rose Petal File"));
            fileTypes.Add(new FileTypeData(".pxd", "Pyrex Definition File"));
            fileTypes.Add(new FileTypeData(".pyx", "Pyrex Source Code File"));
            fileTypes.Add(new FileTypeData(".r", "REBOL Script"));
            fileTypes.Add(new FileTypeData(".rbc", "Rembo-C Script"));
            fileTypes.Add(new FileTypeData(".rbp", "Real Studio Project File"));
            fileTypes.Add(new FileTypeData(".rdlc", "Visual Studio Client Report Definition File"));
            fileTypes.Add(new FileTypeData(".refresh", "Visual Studio Refresh File"));
            fileTypes.Add(new FileTypeData(".resjson", "Windows JavaScript Resources File"));
            fileTypes.Add(new FileTypeData(".resw", "Windows Resources File"));
            fileTypes.Add(new FileTypeData(".rex", "Rexx Source File"));
            fileTypes.Add(new FileTypeData(".rise", "RISE Editor Model File"));
            fileTypes.Add(new FileTypeData(".rodl", "RemObjects Definition Language File"));
            fileTypes.Add(new FileTypeData(".rsrc", "Macintosh Resource File"));
            fileTypes.Add(new FileTypeData(".rss", "Symbian Application Resource File"));
            fileTypes.Add(new FileTypeData(".sbproj", "OpenGL Shader Builder Project"));
            fileTypes.Add(new FileTypeData(".scriptsuite", "AppleScript Script Suite File"));
            fileTypes.Add(new FileTypeData(".scriptterminology", "AppleScript Script Terminology File"));
            fileTypes.Add(new FileTypeData(".slogo", "StarLogo Project File"));
            fileTypes.Add(new FileTypeData(".sltng", "StarLogo TNG Project File"));
            fileTypes.Add(new FileTypeData(".sma", "AMX Mod Plugin Source File"));
            fileTypes.Add(new FileTypeData(".snippet", "Visual Studio IntelliSense Code Snippet"));
            fileTypes.Add(new FileTypeData(".spec", "RPM Specification File"));
            fileTypes.Add(new FileTypeData(".sqlproj", "Visual Studio SQL Server Project"));
            fileTypes.Add(new FileTypeData(".sr", ".rpm	Red Hat Package Manager Source File"));
            fileTypes.Add(new FileTypeData(".ssc", "SourceSafe Status File"));
            fileTypes.Add(new FileTypeData(".sv", "-base	Subversion Base File"));
            fileTypes.Add(new FileTypeData(".sym", "Symbols File"));
            fileTypes.Add(new FileTypeData(".tcl", "Tcl Script"));
            fileTypes.Add(new FileTypeData(".testrunconfig", "Visual Studio Test Run Configuration File"));
            fileTypes.Add(new FileTypeData(".testsettings", "Visual Studio Test Settings File"));
            fileTypes.Add(new FileTypeData(".textfactory", "BBEdit Text Factory"));
            fileTypes.Add(new FileTypeData(".tk", "Tk Script"));
            fileTypes.Add(new FileTypeData(".tld", "Tag Library Descriptor File"));
            fileTypes.Add(new FileTypeData(".tlh", "Typelib Generated C/C++ Header File"));
            fileTypes.Add(new FileTypeData(".tli", "Typelib Generated C/C++ Inline File"));
            fileTypes.Add(new FileTypeData(".tmlanguage", "TextMate Language Grammar File"));
            fileTypes.Add(new FileTypeData(".tmproj", "TextMate Project File"));
            fileTypes.Add(new FileTypeData(".tpu", "Turbo Pascal Unit"));
            fileTypes.Add(new FileTypeData(".tt", "Visual Studio Text Template"));
            fileTypes.Add(new FileTypeData(".tu", "Turing Source File"));
            fileTypes.Add(new FileTypeData(".twig", "Twig Template"));
            fileTypes.Add(new FileTypeData(".v1", ".suo	Visual Studio 2012 Solution User Options File"));
            fileTypes.Add(new FileTypeData(".v1", ".suo	Visual Studio 2013 Solution User Options File"));
            fileTypes.Add(new FileTypeData(".vbx", "Visual Basic Custom Control"));
            fileTypes.Add(new FileTypeData(".vbz", "Visual Basic Project Template"));
            fileTypes.Add(new FileTypeData(".vdp", "Visual Studio Deployment Project"));
            fileTypes.Add(new FileTypeData(".vgc", "ViziGen Code Generation Template"));
            fileTypes.Add(new FileTypeData(".vsmacros", "Visual Studio Binary Macro Project"));
            fileTypes.Add(new FileTypeData(".vsmdi", "Visual Studio Test Metadata File"));
            fileTypes.Add(new FileTypeData(".vsmproj", "Visual Studio Text Macro Project"));
            fileTypes.Add(new FileTypeData(".vsps", "Visual Studio Serialized Performance Report"));
            fileTypes.Add(new FileTypeData(".vspscc", "Visual Studio Project Source Control File"));
            fileTypes.Add(new FileTypeData(".vspx", "Visual Studio Performance Report Data File"));
            fileTypes.Add(new FileTypeData(".vssscc", "Visual Studio Solution Source Control File"));
            fileTypes.Add(new FileTypeData(".vsz", "Visual Studio Wizard File"));
            fileTypes.Add(new FileTypeData(".vtml", "Visual Tool Markup Language File"));
            fileTypes.Add(new FileTypeData(".wdgtproj", "Dashcode Widget Project"));
            fileTypes.Add(new FileTypeData(".wdl", "World Definition Language Script"));
            fileTypes.Add(new FileTypeData(".wdw", "WinDev Window File"));
            fileTypes.Add(new FileTypeData(".wixlib", "WiX Library File"));
            fileTypes.Add(new FileTypeData(".wixmsp", "WiX XML Patch File"));
            fileTypes.Add(new FileTypeData(".wixmst", "WiX Transform File"));
            fileTypes.Add(new FileTypeData(".wixobj", "WiX Object File"));
            fileTypes.Add(new FileTypeData(".wixout", "WiX XML Output File"));
            fileTypes.Add(new FileTypeData(".wixpdb", "WiX Debug File"));
            fileTypes.Add(new FileTypeData(".wpw", "WinDev Mobile Window File"));
            fileTypes.Add(new FileTypeData(".wsc", "Windows Script Component"));
            fileTypes.Add(new FileTypeData(".wsp", "SharePoint Solution Package"));
            fileTypes.Add(new FileTypeData(".wxi", "WiX Include File"));
            fileTypes.Add(new FileTypeData(".wxl", "WiX Localization File"));
            fileTypes.Add(new FileTypeData(".wxs", "WiX Source File"));
            fileTypes.Add(new FileTypeData(".xcarchive", "Xcode Archive"));
            fileTypes.Add(new FileTypeData(".xcconfig", "Xcode Configuration Settings File"));
            fileTypes.Add(new FileTypeData(".xcdatamodeld", "Xcode Core Data Model File"));
            fileTypes.Add(new FileTypeData(".xcsnapshots", "Xcode Snapshot"));
            fileTypes.Add(new FileTypeData(".xcworkspace", "Xcode Workspace File"));
            fileTypes.Add(new FileTypeData(".xib", "Interface Builder File"));
            fileTypes.Add(new FileTypeData(".xojo_binary_project", "Xojo Binary Project File"));
            fileTypes.Add(new FileTypeData(".xojo_menu", "Xojo Menu File"));
            fileTypes.Add(new FileTypeData(".xojo_project", "Xojo Project File"));
            fileTypes.Add(new FileTypeData(".xojo_xml_project", "Xojo Binary Project File"));
            fileTypes.Add(new FileTypeData(".xoml", "Windows Workflow File"));
            fileTypes.Add(new FileTypeData(".xpp", "X++ Source Code File"));
            fileTypes.Add(new FileTypeData(".xql", "XML Query Language File"));
            fileTypes.Add(new FileTypeData(".xqm", "XQuery Module"));
            fileTypes.Add(new FileTypeData(".buildpath", "Eclipse Build Path File"));
            fileTypes.Add(new FileTypeData(".bytes", "Binary Text Asset Data File"));
            fileTypes.Add(new FileTypeData(".mdown", "Markdown File"));
            fileTypes.Add(new FileTypeData(".pdl", "Perl Data Language File"));
            fileTypes.Add(new FileTypeData(".plg", "Visual Studio Build Log File"));
            fileTypes.Add(new FileTypeData(".pym", "PYM Macro Preprocessor File"));
            fileTypes.Add(new FileTypeData(".gnumakefile", "GNU Makefile"));
            fileTypes.Add(new FileTypeData(".kb", "C++ Keyboard Script"));
            fileTypes.Add(new FileTypeData(".kdmp", "Windows Crash Dump File"));
            fileTypes.Add(new FileTypeData(".ow", "Free Pascal 1.0.x Object File"));
            fileTypes.Add(new FileTypeData(".pickle", "Python Pickle File"));
            fileTypes.Add(new FileTypeData(".vac", "Oc2.316s Cakit File"));
            fileTypes.Add(new FileTypeData(".vm", "Velocity Template"));
            fileTypes.Add(new FileTypeData(".aml", "Abstract Markup Language"));
            fileTypes.Add(new FileTypeData(".j", "Java Source File"));
            fileTypes.Add(new FileTypeData(".pbxproj", "Xcode Project Data File"));
            fileTypes.Add(new FileTypeData(".acd", "RSLogix 5000 Program"));
            fileTypes.Add(new FileTypeData(".dsp", "Visual C++ 6 Project"));
            fileTypes.Add(new FileTypeData(".inc", "Include File"));
            fileTypes.Add(new FileTypeData(".ddd", "Alpha Five Data Dictionary File"));
            fileTypes.Add(new FileTypeData(".autoplay", "AutoPlay Media Studio Project File"));
            fileTypes.Add(new FileTypeData(".ent", "External Entity"));
            fileTypes.Add(new FileTypeData(".jpr", "JBuilder Project"));
            fileTypes.Add(new FileTypeData(".pl", "Prolog Source Code File"));
            fileTypes.Add(new FileTypeData(".pom", "Maven Build File"));
            fileTypes.Add(new FileTypeData(".qml", "QT Meta Language File"));
            fileTypes.Add(new FileTypeData(".reb", "REBOL Script File"));
            fileTypes.Add(new FileTypeData(".p3d", "Panda3D Multifile"));
            fileTypes.Add(new FileTypeData(".os", "ObjectScript Source File"));
            fileTypes.Add(new FileTypeData(".bsc", "Visual Studio Source Browser Information File"));
            fileTypes.Add(new FileTypeData(".cbl", "COBOL Source Code File"));
            fileTypes.Add(new FileTypeData(".ged", "Game Editor Project File"));
            fileTypes.Add(new FileTypeData(".hh", "C++ Header File"));
            fileTypes.Add(new FileTypeData(".lisp", "Lisp Source Code File"));
            fileTypes.Add(new FileTypeData(".mak", "Makefile"));
            fileTypes.Add(new FileTypeData(".mer", "RSView Development Runtime File"));
            fileTypes.Add(new FileTypeData(".pli", "PL/I Source Code File"));
            fileTypes.Add(new FileTypeData(".sup", "Super Project Definition File"));
            fileTypes.Add(new FileTypeData(".vsp", "Visual Studio Performance Report File"));
            fileTypes.Add(new FileTypeData(".vtv", "Adobe Dreamweaver Validator Configuration File"));
            fileTypes.Add(new FileTypeData(".wiq", "Visual Studio Work Item Query File"));
            fileTypes.Add(new FileTypeData(".bsh", "BeanShell Script"));
            fileTypes.Add(new FileTypeData(".dox", "Doxygen Documentation File"));
            fileTypes.Add(new FileTypeData(".jsxinc", "ExtendScript Included Script File"));
            fileTypes.Add(new FileTypeData(".makefile", "Makefile"));
            fileTypes.Add(new FileTypeData(".vala", "Vala Source Code File"));
            fileTypes.Add(new FileTypeData(".winmd", "Windows Metadata File"));
            fileTypes.Add(new FileTypeData(".gm", "GameMonkey Script"));
            fileTypes.Add(new FileTypeData(".a2w", "Alice World"));
            fileTypes.Add(new FileTypeData(".nsi", "NSIS Script"));
            fileTypes.Add(new FileTypeData(".p", "Pascal Source Code"));
            fileTypes.Add(new FileTypeData(".gbr", "Gameboy Tileset File"));
            fileTypes.Add(new FileTypeData(".m", "Mercury Source Code File"));
            fileTypes.Add(new FileTypeData(".arr", "MultiMedia Fusion Array File"));
            fileTypes.Add(new FileTypeData(".pod", "Perl POD File"));
            fileTypes.Add(new FileTypeData(".tns", "TI-Nspire Document"));
            fileTypes.Add(new FileTypeData(".csi", "EdLog Program Data File"));
            fileTypes.Add(new FileTypeData(".agi", "Asterisk Gateway Interface File"));
            fileTypes.Add(new FileTypeData(".bpg", "Borland Project Group"));
            fileTypes.Add(new FileTypeData(".bs2", "BASIC Stamp 2 Code File"));
            fileTypes.Add(new FileTypeData(".csi", "ContentServ Include File"));
            fileTypes.Add(new FileTypeData(".dba", "CryENGINE Animation Database File"));
            fileTypes.Add(new FileTypeData(".dba", "DarkBASIC Source Code File"));
            fileTypes.Add(new FileTypeData(".dpk", "Delphi Package"));
            fileTypes.Add(new FileTypeData(".gmd", "Game Maker Program Code"));
            fileTypes.Add(new FileTypeData(".idl", "Interface Definition Language File"));
            fileTypes.Add(new FileTypeData(".jpx", "JBuilder Project"));
            fileTypes.Add(new FileTypeData(".l", "Lex Source File"));
            fileTypes.Add(new FileTypeData(".lnt", "PC-lint/FlexeLint Configuration File"));
            fileTypes.Add(new FileTypeData(".lucidsnippet", "Lucid Snippet File"));
            fileTypes.Add(new FileTypeData(".msp", "MaxScript Page File"));
            fileTypes.Add(new FileTypeData(".prg", "Visual FoxPro Program File"));
            fileTypes.Add(new FileTypeData(".ss", "SilverStripe Source Code File"));
            fileTypes.Add(new FileTypeData(".sud", "Super Project Analyzer File"));
            fileTypes.Add(new FileTypeData(".tur", "Turing Program Source File"));
            fileTypes.Add(new FileTypeData(".v", "Coq Source Code File"));
            fileTypes.Add(new FileTypeData(".vcp", "eMbedded Visual C++ Project File"));
            fileTypes.Add(new FileTypeData(".xquery", "XQuery Source Code File"));
            fileTypes.Add(new FileTypeData(".a3x", "Compiled AutoIt v3 Script"));
            fileTypes.Add(new FileTypeData(".acp", "EditPlus Auto-Completion File"));
            fileTypes.Add(new FileTypeData(".act", "DS Game Maker Action File"));
            fileTypes.Add(new FileTypeData(".ada", "Ada Source Code"));
            fileTypes.Add(new FileTypeData(".aidl", "Android Interface Definition Language File"));
            fileTypes.Add(new FileTypeData(".alx", "Alpha Five Library Index File"));
            fileTypes.Add(new FileTypeData(".anjuta", "Anjuta IDE Project File"));
            fileTypes.Add(new FileTypeData(".apr", "Apadana Project File"));
            fileTypes.Add(new FileTypeData(".ascs", "ActionScript Communication Server File"));
            fileTypes.Add(new FileTypeData(".asdb", "Asphyre Sphinx Archive File"));
            fileTypes.Add(new FileTypeData(".aut", "AutoIt Script File"));
            fileTypes.Add(new FileTypeData(".axe", "Annotated XML Example File"));
            fileTypes.Add(new FileTypeData(".bpr", "Borland C++Builder Project File"));
            fileTypes.Add(new FileTypeData(".car", "Brew Component Application Resource File"));
            fileTypes.Add(new FileTypeData(".cba", "CryENGINE Resource Compiler Settings File"));
            fileTypes.Add(new FileTypeData(".ccs", "CCS Script File"));
            fileTypes.Add(new FileTypeData(".ccscc", "ClearCase Source Control Info File"));
            fileTypes.Add(new FileTypeData(".cdxml", "Cmdlet Definition XML File"));
            fileTypes.Add(new FileTypeData(".ckbx", "Cricket Audio XML Bank Description File"));
            fileTypes.Add(new FileTypeData(".cma", "OCaml Library"));
            fileTypes.Add(new FileTypeData(".cpb", "Comicino Studio Project File"));
            fileTypes.Add(new FileTypeData(".cst", "ContentServ Template"));
            fileTypes.Add(new FileTypeData(".ctc", "Visual Studio Command Table Configuration File"));
            fileTypes.Add(new FileTypeData(".cto", "Visual Studio Binary Command Table Output File"));
            fileTypes.Add(new FileTypeData(".ctsym", "Visual Studio Command Table Output File"));
            fileTypes.Add(new FileTypeData(".ctx", "Visual Basic Control Binary File"));
            fileTypes.Add(new FileTypeData(".dabriefcase", "RemObjects Data Abstract File Briefcase"));
            fileTypes.Add(new FileTypeData(".daconfig", "RemObjects Data Abstract Configuration File"));
            fileTypes.Add(new FileTypeData(".ddp", "Delphi Diagram Portfolio File"));
            fileTypes.Add(new FileTypeData(".defs", "BlueJ Settings File"));
            fileTypes.Add(new FileTypeData(".developerprofile", "Xcode Developer Profile"));
            fileTypes.Add(new FileTypeData(".dfk", "Dark Flow Project File"));
            fileTypes.Add(new FileTypeData(".docset", "Doxygen Document Set File"));
            fileTypes.Add(new FileTypeData(".dres", "Delphi Compiled Resource File"));
            fileTypes.Add(new FileTypeData(".dylib", "Mach-O Dynamic Library"));
            fileTypes.Add(new FileTypeData(".eba", "Emergence BASIC Source Code File"));
            fileTypes.Add(new FileTypeData(".ecp", "EasyC Project File"));
            fileTypes.Add(new FileTypeData(".edm", "Adobe Extension Data Markup Language File"));
            fileTypes.Add(new FileTypeData(".elc", "Emacs Compiled Lisp File"));
            fileTypes.Add(new FileTypeData(".fbp7", "FinalBuilder 7 Project"));
            fileTypes.Add(new FileTypeData(".fce", "ForeUI Custom Element File"));
            fileTypes.Add(new FileTypeData(".fcl", "ForeUI Custom Library File"));
            fileTypes.Add(new FileTypeData(".fd", "DataFlex Data File"));
            fileTypes.Add(new FileTypeData(".feature", "SharePoint Feature File"));
            fileTypes.Add(new FileTypeData(".fpt", "Alpha Five Table Memo File"));
            fileTypes.Add(new FileTypeData(".frj", "FreeForm-J Project File"));
            fileTypes.Add(new FileTypeData(".frx", "FoxPro Report"));
            fileTypes.Add(new FileTypeData(".gar", "GridGain Archive"));
            fileTypes.Add(new FileTypeData(".gbap", "GLBasic Project File"));
            fileTypes.Add(new FileTypeData(".gbas", "GLBasic Source File"));
            fileTypes.Add(new FileTypeData(".gbm", "Gameboy Map File"));
            fileTypes.Add(new FileTypeData(".gbs", "Generic Build Support Metadata File"));
            fileTypes.Add(new FileTypeData(".gdfmakerproject", "GDF Editor Project File"));
            fileTypes.Add(new FileTypeData(".glade", "Glade Project File"));
            fileTypes.Add(new FileTypeData(".gls", "GLScript Game Script"));
            fileTypes.Add(new FileTypeData(".gpj", "MULTI IDE Project File"));
            fileTypes.Add(new FileTypeData(".gvy", "Groovy Source Code File"));
            fileTypes.Add(new FileTypeData(".handlebars", "Handlebars Template"));
            fileTypes.Add(new FileTypeData(".hhh", "Power C Precompiled Header File"));
            fileTypes.Add(new FileTypeData(".hrl", "Erlang Header File"));
            fileTypes.Add(new FileTypeData(".hydra", "Hydra Image Filter Program File"));
            fileTypes.Add(new FileTypeData(".isc", "Xilinx Device Configuration File"));
            fileTypes.Add(new FileTypeData(".iwz", "InstallShield Express 2 Project File"));
            fileTypes.Add(new FileTypeData(".jl", "Julia Source Code File"));
            fileTypes.Add(new FileTypeData(".jnilib", "JNI Library"));
            fileTypes.Add(new FileTypeData(".jpd", "Java Process Definition"));
            fileTypes.Add(new FileTypeData(".jsh", "JAWS Script Header File"));
            fileTypes.Add(new FileTypeData(".jss", "JAWS Script"));
            fileTypes.Add(new FileTypeData(".list", "JAR Index File"));
            fileTypes.Add(new FileTypeData(".lrdb", "Photoshop Lightroom Database"));
            fileTypes.Add(new FileTypeData(".mako", "Mako Template"));
            fileTypes.Add(new FileTypeData(".md", "Machine Description File"));
            fileTypes.Add(new FileTypeData(".med", "RSView Development Project"));
            fileTypes.Add(new FileTypeData(".mfcribbo", "-ms	MFC Ribbon Definition XML File"));
            fileTypes.Add(new FileTypeData(".mlb", "Visual FoxPro Library"));
            fileTypes.Add(new FileTypeData(".mode2v3", "Xcode Project Data File"));
            fileTypes.Add(new FileTypeData(".mvx", "Multimedia Fusion Movement Extension"));
            fileTypes.Add(new FileTypeData(".orderedtest", "Visual Studio Ordered Test File"));
            fileTypes.Add(new FileTypeData(".osc", "Obix Source Code File"));
            fileTypes.Add(new FileTypeData(".oxygene", "Oxygene Project File"));
            fileTypes.Add(new FileTypeData(".pbproj", "Project Builder Project"));
            fileTypes.Add(new FileTypeData(".pc", "Pro*C Source Code File"));
            fileTypes.Add(new FileTypeData(".perspective", "Xcode Project Data File"));
            fileTypes.Add(new FileTypeData(".perspectivev3", "Xcode Project Data File"));
            fileTypes.Add(new FileTypeData(".pfg", "jEEPers Program Configuration File"));
            fileTypes.Add(new FileTypeData(".pkproj", "Visual CCScript Project"));
            fileTypes.Add(new FileTypeData(".pltsuite", "Safari Page Load Test Suite File"));
            fileTypes.Add(new FileTypeData(".ppl", "Free Pascal Dynamic Library"));
            fileTypes.Add(new FileTypeData(".prg", "RPG Toolkit Program File"));
            fileTypes.Add(new FileTypeData(".psess", "Visual Studio Performance Session File"));
            fileTypes.Add(new FileTypeData(".pxi", "Pyrex Include File"));
            fileTypes.Add(new FileTypeData(".qx", "Quexal Source Code"));
            fileTypes.Add(new FileTypeData(".r", "Ratfor Source Code File"));
            fileTypes.Add(new FileTypeData(".rb", "Real Studio Project"));
            fileTypes.Add(new FileTypeData(".rbm", "Real Studio Menu File"));
            fileTypes.Add(new FileTypeData(".rbw", "Real Studio Window File"));
            fileTypes.Add(new FileTypeData(".rbxs", "ROBLOX Script"));
            fileTypes.Add(new FileTypeData(".rdoc", "Ruby Document"));
            fileTypes.Add(new FileTypeData(".rls", "Symbian Localization File"));
            fileTypes.Add(new FileTypeData(".rotest", "RemObjects SDK Test File"));
            fileTypes.Add(new FileTypeData(".rotestresult", "RemObjects SDK Test Results File"));
            fileTypes.Add(new FileTypeData(".rwsnippet", "RapidWeaver Snippet File"));
            fileTypes.Add(new FileTypeData(".sbr", "Visual Studio Source Browser Intermediate File"));
            fileTypes.Add(new FileTypeData(".sdl", "Service Description Language File"));
            fileTypes.Add(new FileTypeData(".sed", "Sed Script"));
            fileTypes.Add(new FileTypeData(".sem", "Alpha Five Set Data Dictionary Memo File"));
            fileTypes.Add(new FileTypeData(".sgpbpr", "Baltie Program"));
            fileTypes.Add(new FileTypeData(".sgpsc", "Baltie Scene"));
            fileTypes.Add(new FileTypeData(".slogt", "StarLogo Project Template"));
            fileTypes.Add(new FileTypeData(".smf", "SkinMagic C/C++ Toolkit File"));
            fileTypes.Add(new FileTypeData(".spt", "ESPL Programming File"));
            fileTypes.Add(new FileTypeData(".spt", "Cypress Semiconductor Script"));
            fileTypes.Add(new FileTypeData(".sublim", "-build	Sublime Text Build File"));
            fileTypes.Add(new FileTypeData(".tiprogram", "TI-Basic Program File"));
            fileTypes.Add(new FileTypeData(".tmpl", "BlueJ Default Template"));
            fileTypes.Add(new FileTypeData(".tmproject", "TextMate Project"));
            fileTypes.Add(new FileTypeData(".umlclass", "UML Class Model"));
            fileTypes.Add(new FileTypeData(".var", "Variable Data"));
            fileTypes.Add(new FileTypeData(".vc4", "Visual C++ 4 File"));
            fileTypes.Add(new FileTypeData(".vcx", "Visual Fox Pro Class Library"));
            fileTypes.Add(new FileTypeData(".vsixmanifest", "VSIX Manifest"));
            fileTypes.Add(new FileTypeData(".vsl", "Velocity Template File"));
            fileTypes.Add(new FileTypeData(".vspf", "Visual Studio Performance Filter File"));
            fileTypes.Add(new FileTypeData(".wid", "Visual Studio Widget File"));
            fileTypes.Add(new FileTypeData(".xcdatamodel", "Xcode Core Data Model File"));
            fileTypes.Add(new FileTypeData(".xcode", "Xcode Project"));
            fileTypes.Add(new FileTypeData(".xojo_binary_menu", "Xojo Binary Menu File"));
            fileTypes.Add(new FileTypeData(".xojo_binary_toolbar", "Xojo Binary Toolbar File"));
            fileTypes.Add(new FileTypeData(".xojo_binary_window", "Xojo Binary Window File"));
            fileTypes.Add(new FileTypeData(".xojo_toolbar", "Xojo Toolbar File"));
            fileTypes.Add(new FileTypeData(".xojo_window", "Xojo Window File"));
            fileTypes.Add(new FileTypeData(".xojo_xml_menu", "Xojo XML Menu File"));
            fileTypes.Add(new FileTypeData(".xojo_xml_toolbar", "Xojo Toolbar File"));
            fileTypes.Add(new FileTypeData(".xojo_xml_window", "Xojo XML Window File"));
            fileTypes.Add(new FileTypeData(".xqy", "XQuery Source File"));
            fileTypes.Add(new FileTypeData(".yab", "Yabasic Source Code"));
            fileTypes.Add(new FileTypeData(".exl", "JSDAI Inclusion or Exclusion List"));
            fileTypes.Add(new FileTypeData(".rnc", "RELAX NG Compact Syntax File"));
            fileTypes.Add(new FileTypeData(".abc", "ABC Source File"));
            fileTypes.Add(new FileTypeData(".tpx", "Turbo Pascal 7 Unit"));
            fileTypes.Add(new FileTypeData(".adblock", "Alpha Five Library Temporary File"));
            fileTypes.Add(new FileTypeData(".asx", "Alpha Five Library Temporary Index File"));
            fileTypes.Add(new FileTypeData(".ddx", "Alpha Five Data Dictionary Index File"));
            fileTypes.Add(new FileTypeData(".ipp", "Inline Guard Macro File"));
            fileTypes.Add(new FileTypeData(".make", "Xcode Makefile Script"));
            fileTypes.Add(new FileTypeData(".mode1v3", "Xcode Project Data File"));
            fileTypes.Add(new FileTypeData(".ppu", "Free Pascal Unit File"));
            fileTypes.Add(new FileTypeData(".sll", "Static Link Library"));
            fileTypes.Add(new FileTypeData(".depend", "Code::Blocks Dependencies File"));
            fileTypes.Add(new FileTypeData(".lit", "Lit Source Code File"));
            fileTypes.Add(new FileTypeData(".sjava", "Synchronous Java File"));
            fileTypes.Add(new FileTypeData(".ab", "Applix Builder File"));
            fileTypes.Add(new FileTypeData(".art", "Artifacts Artifact File"));
            fileTypes.Add(new FileTypeData(".bur", "BuRg3r Source Code File"));
            fileTypes.Add(new FileTypeData(".cdx", "Alpha Five Table Index File"));
            fileTypes.Add(new FileTypeData(".cham", "Compiled HAM File"));
            fileTypes.Add(new FileTypeData(".chef", "Chef Source Code File"));
            fileTypes.Add(new FileTypeData(".ci", "PolySpace Preprocessed Code File"));
            fileTypes.Add(new FileTypeData(".dis", "DisSharp Project File"));
            fileTypes.Add(new FileTypeData(".drf", "Delphi Resource File"));
            fileTypes.Add(new FileTypeData(".fimpp", "FiM++ Source Code File"));
            fileTypes.Add(new FileTypeData(".global", "Global Makefile"));
            fileTypes.Add(new FileTypeData(".gpj", "jGRASP Project File"));
            fileTypes.Add(new FileTypeData(".hcf", "Compact Ham Library"));
            fileTypes.Add(new FileTypeData(".jsh", "Jsh Script"));
            fileTypes.Add(new FileTypeData(".kdevdlg", "KDevelop Dialog Box File"));
            fileTypes.Add(new FileTypeData(".markdn", "Markdown File"));
            fileTypes.Add(new FileTypeData(".pnt", "Panther Project"));
            fileTypes.Add(new FileTypeData(".prg", "xBase Program File"));
            fileTypes.Add(new FileTypeData(".pty", "Rational Property Set"));
            fileTypes.Add(new FileTypeData(".rbvcp", "Real Studio Version Controlled Project"));
            fileTypes.Add(new FileTypeData(".rdoc_options", "Ruby Document Options File"));
            fileTypes.Add(new FileTypeData(".sml", "ARC/INFO Simple Macro Language File"));


            return fileTypes;
        }
    }
}
