using DriveIndexer.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DriveIndexer.Database
{
    public class DefaultFileTypesVideo
    {
        // http://fileinfo.com/filetypes/video
        public static List<FileTypeData> DefaultTypes()
        {
            List<FileTypeData> fileTypes = new List<FileTypeData>();
            fileTypes.Add(new FileTypeData(".aep", "After Effects Project"));
            fileTypes.Add(new FileTypeData(".mp", ".infovid	Parrot AR Drone and Gyro Flyer Video"));
            fileTypes.Add(new FileTypeData(".dzp", "DirectorZone Particle Effect File"));
            fileTypes.Add(new FileTypeData(".mani", "Mine-imator Project File"));
            fileTypes.Add(new FileTypeData(".vro", "DVD Video Recording Format"));
            fileTypes.Add(new FileTypeData(".dir", "Adobe Director Movie"));
            fileTypes.Add(new FileTypeData(".wlmp", "Windows Live Movie Maker Project File"));
            fileTypes.Add(new FileTypeData(".scm", "ScreenCam Screen Recording"));
            fileTypes.Add(new FileTypeData(".rms", "Secure Real Media File"));
            fileTypes.Add(new FileTypeData(".mswmm", "Windows Movie Maker Project"));
            fileTypes.Add(new FileTypeData(".playlist", "CyberLink PowerDVD Playlist"));
            fileTypes.Add(new FileTypeData(".sfd", "Sofdec Dreamcast Movie"));
            fileTypes.Add(new FileTypeData(".dzm", "DirectorZone Menu Template"));
            fileTypes.Add(new FileTypeData(".wpl", "Windows Media Player Playlist"));
            fileTypes.Add(new FileTypeData(".bik", "Bink Video File"));
            fileTypes.Add(new FileTypeData(".3gp", "3GPP Multimedia File"));
            fileTypes.Add(new FileTypeData(".psh", "Photodex Slide Show"));
            fileTypes.Add(new FileTypeData(".dcr", "Liberty Video Recording File"));
            fileTypes.Add(new FileTypeData(".m2p", "MPEG-2 Program Stream File"));
            fileTypes.Add(new FileTypeData(".ntp", "Natron Project File"));
            fileTypes.Add(new FileTypeData(".prproj", "Premiere Pro Project"));
            fileTypes.Add(new FileTypeData(".trp", "HD Video Transport Stream"));
            fileTypes.Add(new FileTypeData(".veg", "Vegas Video Project"));
            fileTypes.Add(new FileTypeData(".aaf", "Advanced Authoring Format File"));
            fileTypes.Add(new FileTypeData(".amc", "AMC Video File"));
            fileTypes.Add(new FileTypeData(".bdmv", "Blu-ray Disc Movie Information File"));
            fileTypes.Add(new FileTypeData(".dck", "Resolume Deck File"));
            fileTypes.Add(new FileTypeData(".gcs", "Cineform Studio Video Project"));
            fileTypes.Add(new FileTypeData(".ivr", "Internet Video Recording"));
            fileTypes.Add(new FileTypeData(".m21", "AXMEDIS MPEG-21 File"));
            fileTypes.Add(new FileTypeData(".mk3d", "Matroska 3D Video File"));
            fileTypes.Add(new FileTypeData(".mproj", "Mine-imator Project"));
            fileTypes.Add(new FileTypeData(".rdb", "Wavelet Video Images File"));
            fileTypes.Add(new FileTypeData(".rmp", "RealPlayer Metadata Package File"));
            fileTypes.Add(new FileTypeData(".rv", "Real Video File"));
            fileTypes.Add(new FileTypeData(".screenflow", "ScreenFlow Document"));
            fileTypes.Add(new FileTypeData(".sec", "Samsung Security Video File"));
            fileTypes.Add(new FileTypeData(".swt", "Flash Generator Template"));
            fileTypes.Add(new FileTypeData(".usm", "USM Game Video File"));
            fileTypes.Add(new FileTypeData(".vcpf", "VideoConvert Project File"));
            fileTypes.Add(new FileTypeData(".viewlet", "Qarbon Viewlet"));
            fileTypes.Add(new FileTypeData(".wp3", "Microsoft Photo Story Project File"));
            fileTypes.Add(new FileTypeData(".xej", "Expression Encoder Job File"));
            fileTypes.Add(new FileTypeData(".dnc", "Windows Dancer File"));
            fileTypes.Add(new FileTypeData(".ivf", "Indeo Video Format File"));
            fileTypes.Add(new FileTypeData(".wm", "Windows Media File"));
            fileTypes.Add(new FileTypeData(".swf", "Shockwave Flash Movie"));
            fileTypes.Add(new FileTypeData(".webm", "WebM Video File"));
            fileTypes.Add(new FileTypeData(".meta", "RealPlayer Metafile"));
            fileTypes.Add(new FileTypeData(".avi", "Audio Video Interleave File"));
            fileTypes.Add(new FileTypeData(".mkv", "Matroska Video File"));
            fileTypes.Add(new FileTypeData(".kmv", "Mobile DJ Video File"));
            fileTypes.Add(new FileTypeData(".srt", "SubRip Subtitle File"));
            fileTypes.Add(new FileTypeData(".gfp", "GreenForce-Player Protected Media File"));
            fileTypes.Add(new FileTypeData(".msdvd", "Windows DVD Maker Project File"));
            fileTypes.Add(new FileTypeData(".piv", "Pivot Stickfigure Animation"));
            fileTypes.Add(new FileTypeData(".vob", "DVD Video Object File"));
            fileTypes.Add(new FileTypeData(".3gp2", "3GPP Multimedia File"));
            fileTypes.Add(new FileTypeData(".trec", "TechSmith Recording File"));
            fileTypes.Add(new FileTypeData(".bu", "Samsung CCTV Video File"));
            fileTypes.Add(new FileTypeData(".mpeg", "MPEG Movie"));
            fileTypes.Add(new FileTypeData(".scc", "ScreenFlow Screen Recording"));
            fileTypes.Add(new FileTypeData(".gvi", "Google Video File"));
            fileTypes.Add(new FileTypeData(".wmv", "Windows Media Video File"));
            fileTypes.Add(new FileTypeData(".m4v", "iTunes Video File"));
            fileTypes.Add(new FileTypeData(".fbr", "FlashBack Screen Recording"));
            fileTypes.Add(new FileTypeData(".ts", "Video Transport Stream File"));
            fileTypes.Add(new FileTypeData(".aepx", "After Effects XML Project"));
            fileTypes.Add(new FileTypeData(".dzt", "DirectorZone Title File"));
            fileTypes.Add(new FileTypeData(".bin", "Binary Video File"));
            fileTypes.Add(new FileTypeData(".ism", "IIS Smooth Streaming Manifest File"));
            fileTypes.Add(new FileTypeData(".swi", "SWiSH Project File"));
            fileTypes.Add(new FileTypeData(".amx", "Adobe Motion Exchange File"));
            fileTypes.Add(new FileTypeData(".m2ts", "Blu-ray BDAV Video File"));
            fileTypes.Add(new FileTypeData(".rmd", "RED Metadata File"));
            fileTypes.Add(new FileTypeData(".sbk", "SWiSH Project Backup File"));
            fileTypes.Add(new FileTypeData(".vpj", "VideoPad Video Editor Project File"));
            fileTypes.Add(new FileTypeData(".mmv", "MicroMV Video File"));
            fileTypes.Add(new FileTypeData(".cpi", "AVCHD Video Clip Information File"));
            fileTypes.Add(new FileTypeData(".mnv", "PlayStation Movie File"));
            fileTypes.Add(new FileTypeData(".vsp", "VideoStudio Project File"));
            fileTypes.Add(new FileTypeData(".ifo", "DVD-Video Disc Information File"));
            fileTypes.Add(new FileTypeData(".mpg", "MPEG Video File"));
            fileTypes.Add(new FileTypeData(".mov", "Apple QuickTime Movie"));
            fileTypes.Add(new FileTypeData(".hdmov", "QuickTime HD Movie File"));
            fileTypes.Add(new FileTypeData(".fcp", "Final Cut Project"));
            fileTypes.Add(new FileTypeData(".ogm", "Ogg Media File"));
            fileTypes.Add(new FileTypeData(".vc1", "VC-1 Video File"));
            fileTypes.Add(new FileTypeData(".vgz", "DigitalVDO Compressed Video File"));
            fileTypes.Add(new FileTypeData(".wmx", "Windows Media Redirector File"));
            fileTypes.Add(new FileTypeData(".xesc", "Expression Encoder Screen Capture File"));
            fileTypes.Add(new FileTypeData(".zm3", "ZSNES Movie #3 File"));
            fileTypes.Add(new FileTypeData(".bnp", "Sony Camcorder Video Data File"));
            fileTypes.Add(new FileTypeData(".k3g", "3GP Mobile Phone Video File"));
            fileTypes.Add(new FileTypeData(".lvix", "Lightworks Video Index File"));
            fileTypes.Add(new FileTypeData(".spl", "FutureSplash Animation"));
            fileTypes.Add(new FileTypeData(".viv", "VivoActive Video File"));
            fileTypes.Add(new FileTypeData(".vp3", "On2 Streaming Video File"));
            fileTypes.Add(new FileTypeData(".vp6", "TrueMotion VP6 Video File"));
            fileTypes.Add(new FileTypeData(".mp4", "MPEG-4 Video File"));
            fileTypes.Add(new FileTypeData(".rec", "Topfield PVR Recording"));
            fileTypes.Add(new FileTypeData(".mob", "MOBTV Video File"));
            fileTypes.Add(new FileTypeData(".flv", "Flash Video File"));
            fileTypes.Add(new FileTypeData(".dat", "VCD Video File"));
            fileTypes.Add(new FileTypeData(".wve", "Wondershare Video Editor Project File"));
            fileTypes.Add(new FileTypeData(".vid", "Generic Video File"));
            fileTypes.Add(new FileTypeData(".dcr", "Digital Court Recorder Video File"));
            fileTypes.Add(new FileTypeData(".tp", "Beyond TV Transport Stream File"));
            fileTypes.Add(new FileTypeData(".xvid", "Xvid-Encoded Video File"));
            fileTypes.Add(new FileTypeData(".mts", "AVCHD Video File"));
            fileTypes.Add(new FileTypeData(".rmvb", "RealMedia Variable Bit Rate File"));
            fileTypes.Add(new FileTypeData(".str", "PlayStation Video Stream"));
            fileTypes.Add(new FileTypeData(".asf", "Advanced Systems Format File"));
            fileTypes.Add(new FileTypeData(".bdm", "AVHCD Information File"));
            fileTypes.Add(new FileTypeData(".mxf", "Material Exchange Format File"));
            fileTypes.Add(new FileTypeData(".yuv", "YUV Video File"));
            fileTypes.Add(new FileTypeData("0", "89	Cavena Subtitles File"));
            fileTypes.Add(new FileTypeData(".avchd", "High Definition Video File"));
            fileTypes.Add(new FileTypeData(".dmx", "Source Filmmaker Project File"));
            fileTypes.Add(new FileTypeData(".m1pg", "iFinish Video Clip"));
            fileTypes.Add(new FileTypeData(".mvd", "Movie Edit Pro Movie File"));
            fileTypes.Add(new FileTypeData(".nvc", "NeroVision Express Project File"));
            fileTypes.Add(new FileTypeData(".roq", "Id Software Game Video"));
            fileTypes.Add(new FileTypeData(".tsp", "Digital TV DVR Recording"));
            fileTypes.Add(new FileTypeData(".ddat", "DivX Temporary Video File"));
            fileTypes.Add(new FileTypeData(".f4f", "Flash Video Fragment"));
            fileTypes.Add(new FileTypeData(".g64", "Genetec Video File"));
            fileTypes.Add(new FileTypeData(".imovielibrary", "iMovie Library File"));
            fileTypes.Add(new FileTypeData(".lsx", "Streaming Media Shortcut"));
            fileTypes.Add(new FileTypeData(".proqc", "ProPresenter Quartz Composition"));
            fileTypes.Add(new FileTypeData(".qt", "Apple QuickTime Movie"));
            fileTypes.Add(new FileTypeData(".sbt", "SBT Subtitle File"));
            fileTypes.Add(new FileTypeData(".vcr", "ATI Video Card Recording"));
            fileTypes.Add(new FileTypeData(".yog", "Outerra Captured Video File"));
            fileTypes.Add(new FileTypeData(".f4v", "Flash MP4 Video File"));
            fileTypes.Add(new FileTypeData(".3g2", "3GPP2 Multimedia File"));
            fileTypes.Add(new FileTypeData(".3mm", "3D Movie Maker Movie Project"));
            fileTypes.Add(new FileTypeData(".ogv", "Ogg Video File"));
            fileTypes.Add(new FileTypeData(".dav", "DVR365 Video File"));
            fileTypes.Add(new FileTypeData(".r3d", "REDCODE Video File"));
            fileTypes.Add(new FileTypeData(".smv", "VideoLink Mail Video File"));
            fileTypes.Add(new FileTypeData(".mpeg4", "MPEG-4 File"));
            fileTypes.Add(new FileTypeData(".dxr", "Protected Macromedia Director Movie"));
            fileTypes.Add(new FileTypeData(".dvdmedia", "RipIt DVD Package"));
            fileTypes.Add(new FileTypeData(".fcproject", "Final Cut Pro X Project File"));
            fileTypes.Add(new FileTypeData(".ismv", "IIS Smooth Streaming Video File"));
            fileTypes.Add(new FileTypeData(".sqz", "Squeeze Project File"));
            fileTypes.Add(new FileTypeData(".tix", "DivX Video Download Activation File"));
            fileTypes.Add(new FileTypeData(".3gpp", "3GPP Media File"));
            fileTypes.Add(new FileTypeData(".clpi", "Blu-ray Clip Information File"));
            fileTypes.Add(new FileTypeData(".f4p", "Adobe Flash Protected Media File"));
            fileTypes.Add(new FileTypeData(".fli", "FLIC Animation"));
            fileTypes.Add(new FileTypeData(".hdv", "High Definition Video Format"));
            fileTypes.Add(new FileTypeData(".mvp", "MAGIX Video Project File"));
            fileTypes.Add(new FileTypeData(".rsx", "RED Metadata XML File"));
            fileTypes.Add(new FileTypeData(".smk", "Smacker Compressed Movie File"));
            fileTypes.Add(new FileTypeData(".thp", "Wii/GameCube Video File"));
            fileTypes.Add(new FileTypeData(".ttxt", "MPEG-4 Timed Text Subtitles File"));
            fileTypes.Add(new FileTypeData(".inp", "Sony Camcorder Image Management File"));
            fileTypes.Add(new FileTypeData(".mvc", "Movie Collector Catalog"));
            fileTypes.Add(new FileTypeData(".par", "Dedicated Micros DVR Recording"));
            fileTypes.Add(new FileTypeData(".video", "aTube Catcher Video File"));
            fileTypes.Add(new FileTypeData(".m15", "MPEG Video"));
            fileTypes.Add(new FileTypeData("0", "264	Ripped Video Data File"));
            fileTypes.Add(new FileTypeData(".h264", "H.264 Encoded Video File"));
            fileTypes.Add(new FileTypeData(".pds", "PowerDirector Script File"));
            fileTypes.Add(new FileTypeData(".lrv", "Low Resolution Video File"));
            fileTypes.Add(new FileTypeData(".dv4", "Bosch Security Systems CCTV Video File"));
            fileTypes.Add(new FileTypeData(".mvp", "MoviePlus Project File"));
            fileTypes.Add(new FileTypeData(".wmd", "Windows Media Download Package"));
            fileTypes.Add(new FileTypeData(".camrec", "Camtasia Studio Screen Recording"));
            fileTypes.Add(new FileTypeData(".camproj", "Camtasia Studio Project"));
            fileTypes.Add(new FileTypeData(".divx", "DivX-Encoded Movie File"));
            fileTypes.Add(new FileTypeData(".stx", "Pinnacle Studio Project File"));
            fileTypes.Add(new FileTypeData(".aetx", "After Effects XML Project Template"));
            fileTypes.Add(new FileTypeData(".vep", "AVS Video Editor Project File"));
            fileTypes.Add(new FileTypeData(".db2", "Samsung CCTV Video Information File"));
            fileTypes.Add(new FileTypeData(".m2t", "HDV Video File"));
            fileTypes.Add(new FileTypeData(".mod", "Camcorder Recorded Video File"));
            fileTypes.Add(new FileTypeData(".aec", "Cinema 4D After Effects Composition"));
            fileTypes.Add(new FileTypeData(".dv", "Digital Video File"));
            fileTypes.Add(new FileTypeData(".sfera", "Sfera 360° File"));
            fileTypes.Add(new FileTypeData(".dvr", "Microsoft Recorded TV Show"));
            fileTypes.Add(new FileTypeData(".pmf", "PSP Movie File"));
            fileTypes.Add(new FileTypeData(".ced", "JVC Camera Video Data File"));
            fileTypes.Add(new FileTypeData(".dash", "MPEG-DASH Video File"));
            fileTypes.Add(new FileTypeData(".rm", "Real Media File"));
            fileTypes.Add(new FileTypeData(".ale", "Avid Log Exchange File"));
            fileTypes.Add(new FileTypeData(".avp", "Avid Project File"));
            fileTypes.Add(new FileTypeData(".bsf", "Blu-ray AVC Video File"));
            fileTypes.Add(new FileTypeData(".dmsm", "VideoWave Movie Project File"));
            fileTypes.Add(new FileTypeData(".dream", "Dream Animated Wallpaper File"));
            fileTypes.Add(new FileTypeData(".imovieproj", "iMovie Project File"));
            fileTypes.Add(new FileTypeData(".otrkey", "OnlineTvRecorder Encoded Video File"));
            fileTypes.Add(new FileTypeData(".3p2", "3GPP Multimedia File"));
            fileTypes.Add(new FileTypeData(".ajp", "CCTV Video File"));
            fileTypes.Add(new FileTypeData(".arcut", "Prelude Rough Cut File"));
            fileTypes.Add(new FileTypeData(".avb", "Avid Bin File"));
            fileTypes.Add(new FileTypeData(".avv", "Avid Volume Bin File"));
            fileTypes.Add(new FileTypeData(".bdt3", "BEEDOCS Timeline 3D 3 Document"));
            fileTypes.Add(new FileTypeData(".bmc", "Bolide Movie Creator Project File"));
            fileTypes.Add(new FileTypeData(".cine", "Phantom Digital Video File"));
            fileTypes.Add(new FileTypeData(".cip", "Cavena Subtitles File"));
            fileTypes.Add(new FileTypeData(".cmmp", "Camtasia MenuMaker Project"));
            fileTypes.Add(new FileTypeData(".cmmtpl", "Camtasia MenuMaker Template"));
            fileTypes.Add(new FileTypeData(".cmrec", "Camtasia Recording"));
            fileTypes.Add(new FileTypeData(".cst", "Director External Cast File"));
            fileTypes.Add(new FileTypeData(".d2v", "DVD2AVI File"));
            fileTypes.Add(new FileTypeData(".d3v", "Datel Video File"));
            fileTypes.Add(new FileTypeData(".dce", "DriveCam Video File"));
            fileTypes.Add(new FileTypeData(".dmsd", "Roxio MyDVD Project"));
            fileTypes.Add(new FileTypeData(".dmss", "VideoWave SlideShow Project File"));
            fileTypes.Add(new FileTypeData(".dpa", "DrawPlus Animation File"));
            fileTypes.Add(new FileTypeData(".evo", "SeeVogh Player Video Recording"));
            fileTypes.Add(new FileTypeData(".eyetv", "EyeTV Recording File"));
            fileTypes.Add(new FileTypeData(".fbz", "FlashBack Screen Recorder Movie"));
            fileTypes.Add(new FileTypeData(".flc", "FLIC Animation"));
            fileTypes.Add(new FileTypeData(".flh", "FLIC Animation File"));
            fileTypes.Add(new FileTypeData(".fpdx", "Utilius Fairplay Project"));
            fileTypes.Add(new FileTypeData(".ftc", "FluxTime Clip File"));
            fileTypes.Add(new FileTypeData(".gts", "CaptiveWorks PVR Video File"));
            fileTypes.Add(new FileTypeData(".hkm", "Havok Movie File"));
            fileTypes.Add(new FileTypeData(".imoviemobile", "iOS iMovie Project File"));
            fileTypes.Add(new FileTypeData(".imovieproject", "iMovie Project"));
            fileTypes.Add(new FileTypeData(".ircp", "SpeedGrade IRIDAS Composite File"));
            fileTypes.Add(new FileTypeData(".ismc", "Smooth Streaming Client Manifest File"));
            fileTypes.Add(new FileTypeData(".izz", "Isadora Media Control Project"));
            fileTypes.Add(new FileTypeData(".izzy", "Isadora Project"));
            fileTypes.Add(new FileTypeData(".jss", "JACOsub Subtitle File"));
            fileTypes.Add(new FileTypeData(".jts", "Cyberlink AVCHD Video File"));
            fileTypes.Add(new FileTypeData(".jtv", "JRiver TV File"));
            fileTypes.Add(new FileTypeData(".kdenlive", "Kdenlive Project File"));
            fileTypes.Add(new FileTypeData(".m21", "MPEG-21 File"));
            fileTypes.Add(new FileTypeData(".m2v", "MPEG-2 Video"));
            fileTypes.Add(new FileTypeData(".mgv", "PSP Video File"));
            fileTypes.Add(new FileTypeData(".mj2", "Motion JPEG 2000 Video Clip"));
            fileTypes.Add(new FileTypeData(".mp21", "MPEG-21 Multimedia File"));
            fileTypes.Add(new FileTypeData(".mpgindex", "Adobe MPEG Index File"));
            fileTypes.Add(new FileTypeData(".mpls", "Blu-ray Movie Playlist File"));
            fileTypes.Add(new FileTypeData(".mpv", "MPEG Elementary Stream Video File"));
            fileTypes.Add(new FileTypeData(".mse", "MediaShow Slideshow Project File"));
            fileTypes.Add(new FileTypeData(".mtv", "MTV Video Format File"));
            fileTypes.Add(new FileTypeData(".mve", "Infinity Engine Movie File"));
            fileTypes.Add(new FileTypeData(".mxv", "MAGIX Video File"));
            fileTypes.Add(new FileTypeData(".ncor", "Adobe Encore Project File"));
            fileTypes.Add(new FileTypeData(".nsv", "Nullsoft Streaming Video File"));
            fileTypes.Add(new FileTypeData(".nuv", "NuppelVideo File"));
            fileTypes.Add(new FileTypeData(".ogx", "Ogg Vorbis Multiplexed Media File"));
            fileTypes.Add(new FileTypeData(".pac", "PAC Subtitles File"));
            fileTypes.Add(new FileTypeData(".photoshow", "Roxio PhotoShow Project"));
            fileTypes.Add(new FileTypeData(".plproj", "Adobe Prelude Project File"));
            fileTypes.Add(new FileTypeData(".ppj", "Premiere 6 Project File"));
            fileTypes.Add(new FileTypeData(".prel", "Premiere Elements Project File"));
            fileTypes.Add(new FileTypeData(".prtl", "Premiere Pro Title File"));
            fileTypes.Add(new FileTypeData(".pxv", "Pixbend Media File"));
            fileTypes.Add(new FileTypeData(".qtl", "QuickTime Link File"));
            fileTypes.Add(new FileTypeData(".qtz", "Quartz Composer File"));
            fileTypes.Add(new FileTypeData(".rcd", "pcAnywhere Recorded Session File"));
            fileTypes.Add(new FileTypeData(".rum", "Bink Video Subtitle File"));
            fileTypes.Add(new FileTypeData(".rvid", "Snapz Pro X Recorded Video File"));
            fileTypes.Add(new FileTypeData(".rvl", "Muvee Reveal X Project File"));
            fileTypes.Add(new FileTypeData(".sdv", "Studio DV Project File"));
            fileTypes.Add(new FileTypeData(".sedprj", "Slideshow Studio Elements Project"));
            fileTypes.Add(new FileTypeData(".seq", "NorPix StreamPix Sequence"));
            fileTypes.Add(new FileTypeData(".sfvidcap", "Sonic Foundry Video Capture File"));
            fileTypes.Add(new FileTypeData(".siv", "Silicon Imaging Video File"));
            fileTypes.Add(new FileTypeData(".smi", "SMIL Presentation"));
            fileTypes.Add(new FileTypeData(".stl", "Spruce Technologies Subtitle File"));
            fileTypes.Add(new FileTypeData(".svi", "Samsung Video File"));
            fileTypes.Add(new FileTypeData(".tda3mt", "DivX Author Template File"));
            fileTypes.Add(new FileTypeData(".tivo", "TiVo Video File"));
            fileTypes.Add(new FileTypeData(".tod", "JVC Everio Video Capture File"));
            fileTypes.Add(new FileTypeData(".tp0", "Mascom PVR Video File"));
            fileTypes.Add(new FileTypeData(".tpd", "Cyberlink TOD Video File"));
            fileTypes.Add(new FileTypeData(".tpr", "TMPGEnc Project File"));
            fileTypes.Add(new FileTypeData(".tvlayer", "BoinxTV TV Layer"));
            fileTypes.Add(new FileTypeData(".tvshow", "BoinxTV TV Show"));
            fileTypes.Add(new FileTypeData(".usf", "Universal Subtitles Format File"));
            fileTypes.Add(new FileTypeData(".vbc", "VodBurner Crude Video File"));
            fileTypes.Add(new FileTypeData(".vcv", "ViewCave Video File"));
            fileTypes.Add(new FileTypeData(".vdo", "VDOLive Media File"));
            fileTypes.Add(new FileTypeData(".vdr", "VirtualDub Signpost File"));
            fileTypes.Add(new FileTypeData(".vfz", "Creative Webcam Video Effects File"));
            fileTypes.Add(new FileTypeData(".vlab", "VisionLab Studio Project File"));
            fileTypes.Add(new FileTypeData(".vtt", "Web Video Text Tracks File"));
            fileTypes.Add(new FileTypeData(".wcp", "WinDVD Creator Project File"));
            fileTypes.Add(new FileTypeData(".wmmp", "Windows Movie Maker Project File"));
            fileTypes.Add(new FileTypeData(".wvx", "Windows Media Video Redirector"));
            fileTypes.Add(new FileTypeData(".wxp", "Wax 2.0 Project"));
            fileTypes.Add(new FileTypeData(".xfl", "Flash Movie Archive"));
            fileTypes.Add(new FileTypeData(".xlmv", "Xunlei Movie File"));
            fileTypes.Add(new FileTypeData(".xml", "Cinelerra Video Project"));
            fileTypes.Add(new FileTypeData(".y4m", "YUV4MPEG2 Video File"));
            fileTypes.Add(new FileTypeData(".zm1", "ZSNES Movie #1 File"));
            fileTypes.Add(new FileTypeData(".zm2", "ZSNES Movie #2 File"));
            fileTypes.Add(new FileTypeData(".lrec", "Inter-Tel Web Conference Recording"));
            fileTypes.Add(new FileTypeData(".mp4v", "MPEG-4 Video"));
            fileTypes.Add(new FileTypeData(".mys", "Vineyard Captured Video File"));
            fileTypes.Add(new FileTypeData(".w32", "WinCAPs Subtitle File"));
            fileTypes.Add(new FileTypeData(".am", "Anark Media File"));
            fileTypes.Add(new FileTypeData(".aqt", "AQTitle Subtitles File"));
            fileTypes.Add(new FileTypeData(".cvc", "cVideo"));
            fileTypes.Add(new FileTypeData(".gom", "GOM Media File"));
            fileTypes.Add(new FileTypeData(".mpeg1", "MPEG-1 Video File"));
            fileTypes.Add(new FileTypeData(".mpv2", "MPEG-2 Video Stream"));
            fileTypes.Add(new FileTypeData(".orv", "Oracom Video File"));
            fileTypes.Add(new FileTypeData(".rmv", "The Simpsons Hit & Run Video File"));
            fileTypes.Add(new FileTypeData(".ssm", "Standard Streaming Metafile"));
            fileTypes.Add(new FileTypeData(".zeg", "ZeroG Subtitles File"));
            fileTypes.Add(new FileTypeData(".arf", "WebEx Advanced Recording File"));
            fileTypes.Add(new FileTypeData(".moi", "MOI Video File"));
            fileTypes.Add(new FileTypeData(".zmv", "ZSNES Movie File"));
            fileTypes.Add(new FileTypeData(".wtv", "Windows Recorded TV Show File"));
            fileTypes.Add(new FileTypeData(".mjp", "MJPEG Video File"));
            fileTypes.Add(new FileTypeData(".gifv", "GIF Video File"));
            fileTypes.Add(new FileTypeData(".mpe", "MPEG Movie File"));
            fileTypes.Add(new FileTypeData(".dpg", "Nintendo DS Movie File"));
            fileTypes.Add(new FileTypeData(".mpl", "AVCHD Playlist File"));
            fileTypes.Add(new FileTypeData(".rcproject", "iMovie '08 Project"));
            fileTypes.Add(new FileTypeData(".amv", "Anime Music Video File"));
            fileTypes.Add(new FileTypeData(".60d", "CCTV Video Clip"));
            fileTypes.Add(new FileTypeData(".moff", "Sony Video Analysis Index File"));
            fileTypes.Add(new FileTypeData(".mp2v", "MPEG-2 Video File"));
            fileTypes.Add(new FileTypeData(".tdt", "AVCHD Thumbnail File"));
            fileTypes.Add(new FileTypeData(".dv", "-ms	Microsoft Digital Video Recording"));
            fileTypes.Add(new FileTypeData(".bmk", "PowerDVD MovieMark File"));
            fileTypes.Add(new FileTypeData(".tvs", "TeamViewer Video Session File"));
            fileTypes.Add(new FileTypeData(".asx", "Microsoft ASF Redirector File"));
            fileTypes.Add(new FileTypeData(".edl", "Edit Decision List File"));
            fileTypes.Add(new FileTypeData(".smil", "SMIL Presentation File"));
            fileTypes.Add(new FileTypeData(".snagproj", "Snagit Project File"));
            fileTypes.Add(new FileTypeData(".d", "-avi	Microsoft DV-AVI Video File"));
            fileTypes.Add(new FileTypeData(".eye", "Eyemail Video Recording File"));
            fileTypes.Add(new FileTypeData(".mp21", "AXMEDIS MPEG-21 Object"));
            fileTypes.Add(new FileTypeData(".pgi", "Video Recording File"));
            fileTypes.Add(new FileTypeData(".pro", "ProPresenter Export File"));
            fileTypes.Add(new FileTypeData(".avs", "Application Visualization System File"));
            fileTypes.Add(new FileTypeData(".box", "Kodicom Video"));
            fileTypes.Add(new FileTypeData(".int", "Sony Camcorder Image Management File"));
            fileTypes.Add(new FileTypeData(".irf", "CCTV DVR H.264 Video File"));
            fileTypes.Add(new FileTypeData(".scn", "Pinnacle Studio Scene File"));
            fileTypes.Add(new FileTypeData(".ismclip", "iStopMotion Animation Clip"));
            fileTypes.Add(new FileTypeData(".avs", "AviSynth Script File"));
            fileTypes.Add(new FileTypeData(".evo", "HD DVD Video File"));
            fileTypes.Add(new FileTypeData(".smi", "SAMI Subtitles File"));
            fileTypes.Add(new FileTypeData(".m4e", "MPEG-4 Video File"));
            fileTypes.Add(new FileTypeData(".mpg2", "MPEG-2 Video File"));
            fileTypes.Add(new FileTypeData(".tdx", "D-TEG CCTV Video Information File"));
            fileTypes.Add(new FileTypeData(".vivo", "VivoActive Video File"));
            fileTypes.Add(new FileTypeData(".movie", "QuickTime Movie File"));
            fileTypes.Add(new FileTypeData(".vf", "Vegas Movie Studio Project File"));
            fileTypes.Add(new FileTypeData(".3gpp2", "3GPP2 Multimedia File"));
            fileTypes.Add(new FileTypeData(".psb", "PowerDivX Subtitles File"));
            fileTypes.Add(new FileTypeData(".axm", "AXMEDIS Object"));
            fileTypes.Add(new FileTypeData(".cmproj", "Camtasia Project File"));
            fileTypes.Add(new FileTypeData(".dmsd3d", "Roxio MyDVD 3D Project"));
            fileTypes.Add(new FileTypeData(".dvx", "DivX Video File"));
            fileTypes.Add(new FileTypeData(".ezt", "EZTitles Subtitles File"));
            fileTypes.Add(new FileTypeData(".ffm", "FFmpeg Stream File"));
            fileTypes.Add(new FileTypeData(".mqv", "Sony Movie Format File"));
            fileTypes.Add(new FileTypeData(".mvy", "Video easy Project File"));
            fileTypes.Add(new FileTypeData(".vp7", "TrueMotion VP7 Video File"));
            fileTypes.Add(new FileTypeData(".xel", "Expression Encoder Live Encoding File"));
            fileTypes.Add(new FileTypeData(".aet", "After Effects Project Template"));
            fileTypes.Add(new FileTypeData(".anx", "Annodex Exchange Format File"));
            fileTypes.Add(new FileTypeData(".avc", "Avid Media Composer Script"));
            fileTypes.Add(new FileTypeData(".avd", "Movie Edit Pro Video Information File"));
            fileTypes.Add(new FileTypeData(".awlive", "Active Webcam Video File"));
            fileTypes.Add(new FileTypeData(".axv", "Annodex Video File"));
            fileTypes.Add(new FileTypeData(".bdt2", "BEEDOCS Timeline 3D 2 Document"));
            fileTypes.Add(new FileTypeData(".bs4", "Mikogo Session Video Recording"));
            fileTypes.Add(new FileTypeData(".bvr", "Blue Iris Video"));
            fileTypes.Add(new FileTypeData(".byu", "Brigham Young University Movie File"));
            fileTypes.Add(new FileTypeData(".camv", "Camtasia Video File"));
            fileTypes.Add(new FileTypeData(".clk", "ClickView Video File"));
            fileTypes.Add(new FileTypeData(".cmv", "CorelMOVE Animation"));
            fileTypes.Add(new FileTypeData(".cx3", "CMS Recorded Video File"));
            fileTypes.Add(new FileTypeData(".dlx", "Sony VDU Video File"));
            fileTypes.Add(new FileTypeData(".dmb", "Digital Multimedia Broadcasting File"));
            fileTypes.Add(new FileTypeData(".dmsm3d", "VideoWave 3D Movie Project File"));
            fileTypes.Add(new FileTypeData(".exo", "YouTube Video Chunk File"));
            fileTypes.Add(new FileTypeData(".fbr", "Mercury Screen Recording"));
            fileTypes.Add(new FileTypeData(".fcarch", "Final Cut Pro Archive"));
            fileTypes.Add(new FileTypeData(".ffd", "ffDiaporama Project File"));
            fileTypes.Add(new FileTypeData(".flx", "FLIC Animation"));
            fileTypes.Add(new FileTypeData(".gvp", "Google Video Pointer"));
            fileTypes.Add(new FileTypeData(".iva", "Surveillance Video File"));
            fileTypes.Add(new FileTypeData(".jmv", "Jnes Movie File"));
            fileTypes.Add(new FileTypeData(".ktn", "KTooN Animation Project File"));
            fileTypes.Add(new FileTypeData(".m1v", "MPEG-1 Video File"));
            fileTypes.Add(new FileTypeData(".m2a", "MPEG-1 Layer 2 Audio File"));
            fileTypes.Add(new FileTypeData(".m4u", "MPEG-4 Playlist"));
            fileTypes.Add(new FileTypeData(".mjpg", "Motion JPEG Video File"));
            fileTypes.Add(new FileTypeData(".mpsub", "MPlayer Subtitles File"));
            fileTypes.Add(new FileTypeData(".mvex", "Muvee autoProducer 6 Project File"));
            fileTypes.Add(new FileTypeData(".osp", "OpenShot Project File"));
            fileTypes.Add(new FileTypeData(".pns", "Pelco CCTV Video File"));
            fileTypes.Add(new FileTypeData(".pro4dvd", "ProPresenter DVD Clips Document"));
            fileTypes.Add(new FileTypeData(".pro5dvd", "ProPresenter DVD Clips Document"));
            fileTypes.Add(new FileTypeData(".pssd", "PhotoSuite Slide Show File"));
            fileTypes.Add(new FileTypeData(".pva", "PVA Video File"));
            fileTypes.Add(new FileTypeData(".qtch", "QuickTime Cache File"));
            fileTypes.Add(new FileTypeData(".qtindex", "Adobe QTIndex File"));
            fileTypes.Add(new FileTypeData(".qtm", "Apple QuickTime Movie File"));
            fileTypes.Add(new FileTypeData(".rp", "RealPix Clip"));
            fileTypes.Add(new FileTypeData(".rts", "RealPlayer Streaming Media"));
            fileTypes.Add(new FileTypeData(".sml", "SMIL Slideshow Presentation"));
            fileTypes.Add(new FileTypeData(".theater", "iMovie Theater File"));
            fileTypes.Add(new FileTypeData(".tid", "AVCHD Thumbnail File"));
            fileTypes.Add(new FileTypeData(".tvrecording", "BoinxTV TV recording"));
            fileTypes.Add(new FileTypeData(".vem", "Meta Media Video E-Mail File"));
            fileTypes.Add(new FileTypeData(".vfw", "Video for Windows"));
            fileTypes.Add(new FileTypeData(".vix", "Lightworks Video Index File"));
            fileTypes.Add(new FileTypeData(".vs4", "AVTECH CCTV Video Surveillance File"));
            fileTypes.Add(new FileTypeData(".vse", "AVTECH CCTV Video"));
            fileTypes.Add(new FileTypeData(".wot", "WebEx Recording File"));
            fileTypes.Add(new FileTypeData(".mvb", "Multimedia Viewer Book Source File"));
            fileTypes.Add(new FileTypeData(".nut", "NUT Video File"));
            fileTypes.Add(new FileTypeData(".pjs", "Phoenix Subtitles File"));
            fileTypes.Add(new FileTypeData(".sec", "GuinXell Video File"));
            fileTypes.Add(new FileTypeData(".ssf", "Structured Subtitle Format File"));
            fileTypes.Add(new FileTypeData(".mpl", "MPL2 Subtitles File"));
            fileTypes.Add(new FileTypeData(".dif", "Digital Interface Format"));
            fileTypes.Add(new FileTypeData(".vft", "VideoStudio Filter File"));
            fileTypes.Add(new FileTypeData(".vmlt", "VAIO Video File"));
            fileTypes.Add(new FileTypeData(".xmv", "Xbox Media Video File"));
            fileTypes.Add(new FileTypeData(".anim", "Amiga Animation File"));
            fileTypes.Add(new FileTypeData(".grasp", "GRASP Animation"));
            fileTypes.Add(new FileTypeData(".modd", "Sony Video Analysis File"));
            fileTypes.Add(new FileTypeData(".moov", "Apple QuickTime Movie"));
            fileTypes.Add(new FileTypeData(".pvr", "Wintal PVR Video File"));
            fileTypes.Add(new FileTypeData(".vmlf", "VAIO Video File"));
            fileTypes.Add(new FileTypeData(".bix", "Kodicom Video File"));
            fileTypes.Add(new FileTypeData(".cel", "FLIC Animation"));
            fileTypes.Add(new FileTypeData(".dsy", "Besta Video File"));
            fileTypes.Add(new FileTypeData(".gl", "GRASP Animation"));
            fileTypes.Add(new FileTypeData(".ivs", "Internet Streaming Video"));
            fileTypes.Add(new FileTypeData(".lsf", "Streaming Media Format"));
            fileTypes.Add(new FileTypeData(".m75", "MPEG Video"));
            fileTypes.Add(new FileTypeData(".mpf", "MainActor Project File"));
            fileTypes.Add(new FileTypeData(".msh", "Visual Communicator Project File"));
            fileTypes.Add(new FileTypeData(".pmv", "Return to Zork Video File"));
            fileTypes.Add(new FileTypeData(".rmd", "RealPlayer Media File"));
            fileTypes.Add(new FileTypeData(".rts", "QuickTime Real-Time Streaming Format"));
            fileTypes.Add(new FileTypeData(".scm", "Super Chain Media File"));
            fileTypes.Add(new FileTypeData(".vdx", "The 7th Guest Video File"));

            return fileTypes;
        }
    }
}
