using DriveIndexer.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DriveIndexer.Database
{
    public class DefaultFileTypesImage
    {
        // http://fileinfo.com/filetypes/video
        public static List<FileTypeData> DefaultTypes()
        {
            List<FileTypeData> fileTypes = new List<FileTypeData>();

            //fileTypes.Add(new FileTypeData(".2bp", "Pocket PC Bitmap Image File"));
            //fileTypes.Add(new FileTypeData("0", "36	360desktop Panorama File"));
            //fileTypes.Add(new FileTypeData("0", "411	Mavica Thumbnail Image"));
            //fileTypes.Add(new FileTypeData(".73i", "TI-73 Screenshot File"));
            //fileTypes.Add(new FileTypeData(".8pbs", "Adobe Photoshop Macintosh File"));
            //fileTypes.Add(new FileTypeData(".8xi", "TI-83/84 Plus Picture File"));
            //fileTypes.Add(new FileTypeData(".", ".png	NinePatchDrawable Image"));
            //fileTypes.Add(new FileTypeData(".abm", "Photo Album"));
            //fileTypes.Add(new FileTypeData(".accountpictur", "-ms	Windows 8 Account Picture File"));
            //fileTypes.Add(new FileTypeData(".acorn", "Acorn Image"));
            //fileTypes.Add(new FileTypeData(".acr", "American College of Radiology File"));
            //fileTypes.Add(new FileTypeData(".adc", "Scanstudio 16 Color Image"));
            //fileTypes.Add(new FileTypeData(".afx", "Auto FX Photo/Graphic Edges Image"));
            //fileTypes.Add(new FileTypeData(".agif", "Active GIF Creator Project"));
            //fileTypes.Add(new FileTypeData(".agp", "ArtGem Project File"));
            //fileTypes.Add(new FileTypeData(".aic", "Advanced Image Coding File"));
            //fileTypes.Add(new FileTypeData(".ais", "ACDSee Image Sequence File"));
            //fileTypes.Add(new FileTypeData(".albm", "HP Photo Printing Software Album File"));
            //fileTypes.Add(new FileTypeData(".apd", "ACDSee Photo Document"));
            //fileTypes.Add(new FileTypeData(".apm", "Aldus Placeable Metafile Image"));
            //fileTypes.Add(new FileTypeData(".apng", "Animated Portable Network Graphic"));
            //fileTypes.Add(new FileTypeData(".aps", "Greeting Card Studio Project File"));
            //fileTypes.Add(new FileTypeData(".apx", "Ability Photopaint Studio Image"));
            //fileTypes.Add(new FileTypeData(".arr", "Amber Graphic File"));
            //fileTypes.Add(new FileTypeData(".art", "AOL Compressed Image File"));
            //fileTypes.Add(new FileTypeData(".artwork", "ArtStudio Image"));
            //fileTypes.Add(new FileTypeData(".arw", "ArtStudio Image"));
            //fileTypes.Add(new FileTypeData(".asw", "ACDSee Slideshow Wizard File"));
            //fileTypes.Add(new FileTypeData(".avatar", "Google Talk Avatar File"));
            //fileTypes.Add(new FileTypeData(".avb", "Microsoft Comic Chat Character"));
            //fileTypes.Add(new FileTypeData(".awd", "Microsoft Fax Document"));
            //fileTypes.Add(new FileTypeData(".awd", "Artweaver Document"));
            //fileTypes.Add(new FileTypeData(".blkrt", "Block Artist Image File"));
            //fileTypes.Add(new FileTypeData(".blz", "Compressed Bitmap Image"));
            //fileTypes.Add(new FileTypeData(".bm2", "Subspace Bitmap File"));
            //fileTypes.Add(new FileTypeData(".bmc", "Bitmap Cache File"));
            //fileTypes.Add(new FileTypeData(".bmf", "Binary Material File"));
            //fileTypes.Add(new FileTypeData(".bmp", "Bitmap Image File"));
            //fileTypes.Add(new FileTypeData(".bmq", "Re-Volt Mipmap File"));
            //fileTypes.Add(new FileTypeData(".bmx", "Siemens Mobile Animations File"));
            //fileTypes.Add(new FileTypeData(".bmz", "Compressed Bitmap Image"));
            //fileTypes.Add(new FileTypeData(".bpg", "BPG Image"));
            //fileTypes.Add(new FileTypeData(".brk", "Brooktrout Fax Document"));
            //fileTypes.Add(new FileTypeData(".brn", "Cube Graphics File"));
            //fileTypes.Add(new FileTypeData(".brt", "Bryce Textures File"));
            //fileTypes.Add(new FileTypeData(".bss", "Resident Evil Background Images File"));
            //fileTypes.Add(new FileTypeData(".bti", "Nintendo Texture File"));
            //fileTypes.Add(new FileTypeData(".c4", "JEDMICS Image File"));
            //fileTypes.Add(new FileTypeData(".cal", "CALS Raster Graphic"));
            //fileTypes.Add(new FileTypeData(".cals", "CALS Raster Graphic File"));
            //fileTypes.Add(new FileTypeData(".cam", "CASIO Digital Camera Picture File"));
            //fileTypes.Add(new FileTypeData(".can", "Canon Navigator Fax Document"));
            //fileTypes.Add(new FileTypeData(".cd5", "Chasys Draw Image File"));
            //fileTypes.Add(new FileTypeData(".cdc", "AutoCAD DesignCenter Preview Cache File"));
            //fileTypes.Add(new FileTypeData(".cdg", "Compact Disc Plus Graphics Image"));
            //fileTypes.Add(new FileTypeData(".ce", "ComputerEyes Image"));
            //fileTypes.Add(new FileTypeData(".cimg", "CImg Image File"));
            //fileTypes.Add(new FileTypeData(".cin", "Kodak Cineon Bitmap File"));
            //fileTypes.Add(new FileTypeData(".cit", "Intergraph Bitmap Image File"));
            //fileTypes.Add(new FileTypeData(".colz", "Adobe Collage File"));
            //fileTypes.Add(new FileTypeData(".cpbitmap", "iOS Wallpaper Image"));
            //fileTypes.Add(new FileTypeData(".cpc", "CPC Compressed Image File"));
            //fileTypes.Add(new FileTypeData(".cpd", "Compressed PhotoDefiner Image File"));
            //fileTypes.Add(new FileTypeData(".cpg", "Manga Studio Page File"));
            //fileTypes.Add(new FileTypeData(".cps", "Corel Photo House File"));
            //fileTypes.Add(new FileTypeData(".cpt", "Corel Photo-Paint Document"));
            //fileTypes.Add(new FileTypeData(".cpx", "Corel CMX Compressed File"));
            //fileTypes.Add(new FileTypeData(".csf", "Content Sealed Format"));
            //fileTypes.Add(new FileTypeData(".ct", "Scitex Continuous Tone File"));
            //fileTypes.Add(new FileTypeData(".cut", "Dr. Halo Bitmap Image File"));
            //fileTypes.Add(new FileTypeData(".dc2", "Kodak Photo-Enhancer File"));
            //fileTypes.Add(new FileTypeData(".dcm", "DICOM Image"));
            //fileTypes.Add(new FileTypeData(".dcx", "Zsoft Multi-Page Paintbrush File"));
            //fileTypes.Add(new FileTypeData(".ddb", "Device Dependent Bitmap"));
            //fileTypes.Add(new FileTypeData(".dds", "DirectDraw Surface"));
            //fileTypes.Add(new FileTypeData(".ddt", "Age of Mythology Textures File"));
            //fileTypes.Add(new FileTypeData(".dgt", "DST Thumbnail File"));
            //fileTypes.Add(new FileTypeData(".dib", "Device Independent Bitmap File"));
            //fileTypes.Add(new FileTypeData(".dicom", "DICOM Image File"));
            //fileTypes.Add(new FileTypeData(".djv", "DjVu Image"));
            //fileTypes.Add(new FileTypeData(".djvu", "DjVu Image"));
            //fileTypes.Add(new FileTypeData(".dm3", "DigitalMicrograph Image"));
            //fileTypes.Add(new FileTypeData(".dmi", "BYOND Dream Maker Icon File"));
            //fileTypes.Add(new FileTypeData(".dpx", "Digital Picture Exchange File"));
            //fileTypes.Add(new FileTypeData(".drz", "Draz Paint File"));
            //fileTypes.Add(new FileTypeData(".dt2", "Windows Live Messenger Emoticon Image File"));
            //fileTypes.Add(new FileTypeData(".dtw", "Desktop Wallpaper"));
            //fileTypes.Add(new FileTypeData(".dvl", "Virtual Library File"));
            //fileTypes.Add(new FileTypeData(".ecw", "Enhanced Compression Wavelet Image"));
            //fileTypes.Add(new FileTypeData(".epp", "Canon Easy-PhotoPrint Image File"));
            //fileTypes.Add(new FileTypeData(".exr", "OpenEXR Image"));
            //fileTypes.Add(new FileTypeData(".fac", "FACE Image File"));
            //fileTypes.Add(new FileTypeData(".face", "FACE Graphic File"));
            //fileTypes.Add(new FileTypeData(".fal", "Bitmap Graphic Header Information"));
            //fileTypes.Add(new FileTypeData(".fax", "Fax Document"));
            //fileTypes.Add(new FileTypeData(".fbm", "Fuzzy Bitmap Image"));
            //fileTypes.Add(new FileTypeData(".fil", "Symbian Application Logo File"));
            //fileTypes.Add(new FileTypeData(".fits", "Flexible Image Transport System File"));
            //fileTypes.Add(new FileTypeData(".fpg", "Fenix Graphics Collection File"));
            //fileTypes.Add(new FileTypeData(".fpos", "Photo Pos Pro Image"));
            //fileTypes.Add(new FileTypeData(".fpx", "FlashPix Bitmap Image File"));
            //fileTypes.Add(new FileTypeData(".frm", "Painter Frame Stack File"));
            //fileTypes.Add(new FileTypeData(".g3", "CCITT Group 3 Fax Image"));
            //fileTypes.Add(new FileTypeData(".gbr", "GIMP Brush File"));
            //fileTypes.Add(new FileTypeData(".gcdp", "Greeting Card Studio Design Project"));
            //fileTypes.Add(new FileTypeData(".gfb", "GIFBlast Compressed Image File"));
            //fileTypes.Add(new FileTypeData(".gfie", "Greenfish Icon Editor Pro Graphic"));
            //fileTypes.Add(new FileTypeData(".ggr", "GIMP Gradient File"));
            fileTypes.Add(new FileTypeData(".gif", "Graphical Interchange Format File"));
            //fileTypes.Add(new FileTypeData(".gih", "GIMP Image Hose File"));
            //fileTypes.Add(new FileTypeData(".gim", "PlayStation Portable Image File"));
            //fileTypes.Add(new FileTypeData(".gmbck", "Game Maker Background Image File"));
            //fileTypes.Add(new FileTypeData(".gmspr", "Game Maker Sprite File"));
            //fileTypes.Add(new FileTypeData(".gp4", "CCITT Group 4 Fax File"));
            //fileTypes.Add(new FileTypeData(".gpd", "Graphic PhotoDefiner Image File"));
            //fileTypes.Add(new FileTypeData(".gro", "Graphic Object Bitmap"));
            //fileTypes.Add(new FileTypeData(".grob", "Graphic Object Bitmap File"));
            //fileTypes.Add(new FileTypeData(".gry", "Grayscale Image"));
            //fileTypes.Add(new FileTypeData(".hdp", "HD Photo File"));
            //fileTypes.Add(new FileTypeData(".hdr", "High Dynamic Range Image File"));
            //fileTypes.Add(new FileTypeData(".hdrp", "HDRtist Pro Document"));
            //fileTypes.Add(new FileTypeData(".hf", "HF Image"));
            //fileTypes.Add(new FileTypeData(".hpi", "Hemera Photo Objects Image File"));
            //fileTypes.Add(new FileTypeData(".hr", "TRS-80 Image"));
            //fileTypes.Add(new FileTypeData(".hrf", "Hitachi Raster Format File"));
            //fileTypes.Add(new FileTypeData(".i3d", "Houdini Image 3D File"));
            //fileTypes.Add(new FileTypeData(".ic1", "Low Resolution Imagic Graphics File"));
            //fileTypes.Add(new FileTypeData(".ic2", "Medium Resolution Imagic Graphics File"));
            //fileTypes.Add(new FileTypeData(".ic3", "High Resolution Imagic Graphics File"));
            //fileTypes.Add(new FileTypeData(".ica", "Image Object Content Architecture File"));
            //fileTypes.Add(new FileTypeData(".icb", "Targa ICB Bitmap Image"));
            //fileTypes.Add(new FileTypeData(".icn", "Windows Icon File"));
            //fileTypes.Add(new FileTypeData(".icon", "Icon Image File"));
            //fileTypes.Add(new FileTypeData(".icpr", "IconUtils Project File"));
            //fileTypes.Add(new FileTypeData(".ilbm", "Interleaved Bitmap Image"));
            //fileTypes.Add(new FileTypeData(".img", "GEM Image"));
            //fileTypes.Add(new FileTypeData(".imj", "JFIF Bitmap Image"));
            //fileTypes.Add(new FileTypeData(".info", "ZoomBrowser Image Index File"));
            //fileTypes.Add(new FileTypeData(".ink", "Pantone Reference File"));
            //fileTypes.Add(new FileTypeData(".int", "SGI Integer Image"));
            //fileTypes.Add(new FileTypeData(".iphotoproject", "iPhoto Print Project"));
            //fileTypes.Add(new FileTypeData(".ipick", "iPick Football Image"));
            //fileTypes.Add(new FileTypeData(".ipx", "IPIX Image"));
            //fileTypes.Add(new FileTypeData(".itc2", "iTunes Cover Flow Data File 2"));
            //fileTypes.Add(new FileTypeData(".ithmb", "iPod and iPhone Photo Thumbnails File"));
            //fileTypes.Add(new FileTypeData(".ivr", "Image Worlds File"));
            //fileTypes.Add(new FileTypeData(".ivue", "Live Picture IVUE Image"));
            //fileTypes.Add(new FileTypeData(".iwi", "Infinity Ward Texture File"));
            //fileTypes.Add(new FileTypeData(".j", "JPEG Image"));
            //fileTypes.Add(new FileTypeData(".j2c", "JPEG 2000 Code Stream"));
            //fileTypes.Add(new FileTypeData(".j2k", "JPEG 2000 Image"));
            //fileTypes.Add(new FileTypeData(".jas", "Paint Shop Pro Compressed Graphic"));
            //fileTypes.Add(new FileTypeData(".jb2", "JBIG2 Image"));
            //fileTypes.Add(new FileTypeData(".jbf", "Paint Shop Pro Browser Cache File"));
            //fileTypes.Add(new FileTypeData(".jbg", "Joint Bi-level Image Group File"));
            //fileTypes.Add(new FileTypeData(".jbig", "Joint Bi-level Image Group File"));
            //fileTypes.Add(new FileTypeData(".jbig2", "JBIG2"));
            //fileTypes.Add(new FileTypeData(".jbmp", "JAmes OS Bitmap Image"));
            //fileTypes.Add(new FileTypeData(".jbr", "Paint Shop Pro Brushes File"));
            //fileTypes.Add(new FileTypeData(".jfi", "JPEG File Interchange Image"));
            //fileTypes.Add(new FileTypeData(".jfif", "JPEG File Interchange Format"));
            //fileTypes.Add(new FileTypeData(".jia", "Digital Photo Navigator Album"));
            fileTypes.Add(new FileTypeData(".jif", "JPEG Image File"));
            fileTypes.Add(new FileTypeData(".jiff", "JPEG Image File Format"));
            fileTypes.Add(new FileTypeData(".jng", "JPEG Network Graphic"));
            fileTypes.Add(new FileTypeData(".jp2", "JPEG 2000 Core Image File"));
            fileTypes.Add(new FileTypeData(".jpc", "JPEG 2000 Code Stream File"));
            fileTypes.Add(new FileTypeData(".jpd", "Joint PhotoDefiner Image"));
            fileTypes.Add(new FileTypeData(".jpe", "JPEG Image"));
            fileTypes.Add(new FileTypeData(".jpeg", "JPEG Image"));
            fileTypes.Add(new FileTypeData(".jpf", "JPEG 2000 Image"));
            fileTypes.Add(new FileTypeData(".jpg", "JPEG Image"));
            fileTypes.Add(new FileTypeData(".jpg2", "JPEG 2000 Image"));
            fileTypes.Add(new FileTypeData(".jps", "Stereo JPEG Image"));
            //fileTypes.Add(new FileTypeData(".jpx", "JPEG 2000 Image File"));
            //fileTypes.Add(new FileTypeData(".jtf", "JPEG Tagged Interchange Format"));
            //fileTypes.Add(new FileTypeData(".jwl", "Roxio Jewel Case File"));
            //fileTypes.Add(new FileTypeData(".jxr", "JPEG XR Image"));
            //fileTypes.Add(new FileTypeData(".kdi", "KD Player Skin Image File"));
            //fileTypes.Add(new FileTypeData(".kdk", "Kodak Proprietary Decimated TIFF File"));
            //fileTypes.Add(new FileTypeData(".kfx", "Kofax Image File"));
            //fileTypes.Add(new FileTypeData(".kic", "Kodak Compressed Image File"));
            fileTypes.Add(new FileTypeData(".kodak", "Kodak Photo CD File"));
            //fileTypes.Add(new FileTypeData(".kpg", "Kai's Power Goo Graphic"));
            //fileTypes.Add(new FileTypeData(".lb", "Lens Blur Project File"));
            //fileTypes.Add(new FileTypeData(".lbm", "Deluxe Paint Bitmap Image"));
            //fileTypes.Add(new FileTypeData(".lif", "Leica Image File"));
            //fileTypes.Add(new FileTypeData(".ljp", "Lossless JPEG Image"));
            //fileTypes.Add(new FileTypeData(".lrpreview", "Adobe Photoshop Lightroom Preview File"));
            //fileTypes.Add(new FileTypeData(".lzp", "LazPaint Image"));
            //fileTypes.Add(new FileTypeData(".mac", "MacPaint Image"));
            //fileTypes.Add(new FileTypeData(".mat", "Vue Material File"));
            //fileTypes.Add(new FileTypeData(".max", "PaperPort Scanned Document"));
            //fileTypes.Add(new FileTypeData(".mbm", "Kerbal Space Program Texture File"));
            //fileTypes.Add(new FileTypeData(".mbm", "Multi Bitmap File"));
            //fileTypes.Add(new FileTypeData(".mcs", "Mathcad Image"));
            //fileTypes.Add(new FileTypeData(".met", "Presentation Manager Metafile"));
            //fileTypes.Add(new FileTypeData(".mic", "Image Composer File"));
            //fileTypes.Add(new FileTypeData(".miff", "Magick Image File"));
            //fileTypes.Add(new FileTypeData(".mip", "Multiple Image Print File"));
            //fileTypes.Add(new FileTypeData(".mix", "Microsoft Image Exchange File"));
            //fileTypes.Add(new FileTypeData(".mng", "Multiple Network Graphic"));
            //fileTypes.Add(new FileTypeData(".mnr", "AutoCAD Menu Resource File"));
            //fileTypes.Add(new FileTypeData(".mpf", "Microsoft Media Package FIle"));
            //fileTypes.Add(new FileTypeData(".mpo", "Multi Picture Object File"));
            //fileTypes.Add(new FileTypeData(".mrb", "Multiple Resolution Bitmap File"));
            //fileTypes.Add(new FileTypeData(".mrxs", "MIRAX Virtual Slide File"));
            //fileTypes.Add(new FileTypeData(".msk", "Paint Shop Pro Mask File"));
            //fileTypes.Add(new FileTypeData(".msp", "Microsoft Paint Bitmap Image"));
            //fileTypes.Add(new FileTypeData(".mxi", "Maxwell Image"));
            //fileTypes.Add(new FileTypeData(".myl", "MyLogo Maker Image"));
            //fileTypes.Add(new FileTypeData(".ncd", "Nero CoverDesigner File"));
            //fileTypes.Add(new FileTypeData(".ncr", "NCR Image"));
            //fileTypes.Add(new FileTypeData(".nct", "Nero CoverDesigner Template"));
            //fileTypes.Add(new FileTypeData(".neo", "NeoChrome Bitmap Image"));
            //fileTypes.Add(new FileTypeData(".nlm", "Nokia Logo File"));
            //fileTypes.Add(new FileTypeData(".oc3", "openCanvas 3 Event File"));
            //fileTypes.Add(new FileTypeData(".oc4", "openCanvas 4 Event File"));
            //fileTypes.Add(new FileTypeData(".oc5", "openCanvas 5 Event File"));
            //fileTypes.Add(new FileTypeData(".oci", "openCanvas Image"));
            //fileTypes.Add(new FileTypeData(".odi", "OpenDocument Image"));
            //fileTypes.Add(new FileTypeData(".omf", "OMF Interchange Image File"));
            //fileTypes.Add(new FileTypeData(".oplc", "Nokia Operator Logo File"));
            //fileTypes.Add(new FileTypeData(".ora", "OpenRaster Image File"));
            //fileTypes.Add(new FileTypeData(".ota", "OTA Bitmap Image"));
            //fileTypes.Add(new FileTypeData(".otb", "Nokia Over The Air Bitmap Image"));
            //fileTypes.Add(new FileTypeData(".oti", "OpenDocument Image Template"));
            //fileTypes.Add(new FileTypeData(".ozb", "MU Online Image File"));
            //fileTypes.Add(new FileTypeData(".ozj", "MU Online Image File"));
            //fileTypes.Add(new FileTypeData(".ozt", "MU Online Image File"));
            //fileTypes.Add(new FileTypeData(".pac", "STAD Graphic File"));
            //fileTypes.Add(new FileTypeData(".pal", "Dr. Halo Color Palette File"));
            //fileTypes.Add(new FileTypeData(".pano", "Camera Panoramic Picture"));
            //fileTypes.Add(new FileTypeData(".pap", "PanoramaStudio Project File"));
            //fileTypes.Add(new FileTypeData(".pat", "Pattern File"));
            //fileTypes.Add(new FileTypeData(".pbm", "Portable Bitmap Image"));
            //fileTypes.Add(new FileTypeData(".pc1", "Degas Elite Low Res Image File"));
            //fileTypes.Add(new FileTypeData(".pc2", "Degas Elite Medium Res Image File"));
            //fileTypes.Add(new FileTypeData(".pc3", "Degas Elite High Res Image File"));
            //fileTypes.Add(new FileTypeData(".pcd", "Kodak Photo CD Image File"));
            //fileTypes.Add(new FileTypeData(".pcx", "Paintbrush Bitmap Image File"));
            //fileTypes.Add(new FileTypeData(".pdd", "Adobe PhotoDeluxe Image"));
            //fileTypes.Add(new FileTypeData(".pdn", "paint.net Image File"));
            //fileTypes.Add(new FileTypeData(".pe4", "PhotoImpact Image Archive"));
            //fileTypes.Add(new FileTypeData(".pe4", "Photo Explorer Thumbnail Archive"));
            //fileTypes.Add(new FileTypeData(".pfi", "PhotoFiltre Studio Image"));
            //fileTypes.Add(new FileTypeData(".pfr", "Paint Shop Pro Picture Frame File"));
            //fileTypes.Add(new FileTypeData(".pgf", "Progressive Graphics File"));
            //fileTypes.Add(new FileTypeData(".pgm", "Portable Gray Map Image"));
            //fileTypes.Add(new FileTypeData(".pi1", "Degas Low Resolution Image File"));
            //fileTypes.Add(new FileTypeData(".pi2", "Portrait Innovations Photo"));
            //fileTypes.Add(new FileTypeData(".pi2", "Degas Medium Resolution Image File"));
            //fileTypes.Add(new FileTypeData(".pi3", "Degas High Resolution Image File"));
            //fileTypes.Add(new FileTypeData(".pi4", "DEGAS Image"));
            //fileTypes.Add(new FileTypeData(".pi5", "DEGAS Bitmap Image"));
            //fileTypes.Add(new FileTypeData(".pi6", "DEGAS Bitmap Image File"));
            //fileTypes.Add(new FileTypeData(".pic", "Generic Picture File"));
            //fileTypes.Add(new FileTypeData(".pic", "Houdini Raster Image"));
            //fileTypes.Add(new FileTypeData(".pic", "QuickTime PICT Image"));
            //fileTypes.Add(new FileTypeData(".picnc", "Houdini 3D Compositing Image"));
            //fileTypes.Add(new FileTypeData(".pict", "Picture File"));
            //fileTypes.Add(new FileTypeData(".pictclipping", "Picture Clipping File"));
            //fileTypes.Add(new FileTypeData(".pix", "BRL-CAD Raw Image File"));
            //fileTypes.Add(new FileTypeData(".pix", "Alias PIX Image"));
            //fileTypes.Add(new FileTypeData(".pixadex", "Pixadex Icon"));
            //fileTypes.Add(new FileTypeData(".pjpeg", "Progressive JPEG Image"));
            //fileTypes.Add(new FileTypeData(".pjpg", "Progressive JPEG Image"));
            //fileTypes.Add(new FileTypeData(".pm", "Unix XV Graphic File"));
            //fileTypes.Add(new FileTypeData(".pm3", "PageMaker 3 Document"));
            //fileTypes.Add(new FileTypeData(".pmg", "Adobe Photoshop Photomerge Panoramic Composition File"));
            fileTypes.Add(new FileTypeData(".png", "Portable Network Graphic"));
            //fileTypes.Add(new FileTypeData(".pni", "Popnoggin Image File"));
            //fileTypes.Add(new FileTypeData(".pnm", "Portable Any Map Image"));
            //fileTypes.Add(new FileTypeData(".pns", "PNG Stereo Image"));
            //fileTypes.Add(new FileTypeData(".pnt", "MacPaint File"));
            //fileTypes.Add(new FileTypeData(".pntg", "MacPaint Graphic File"));
            //fileTypes.Add(new FileTypeData(".pop", "Samsung Popcon Character File"));
            //fileTypes.Add(new FileTypeData(".pov", "POV-Ray Raytracing Format"));
            //fileTypes.Add(new FileTypeData(".pov", "Prolab Object File"));
            //fileTypes.Add(new FileTypeData(".pp4", "Picture Publisher Bitmap File"));
            //fileTypes.Add(new FileTypeData(".pp5", "Picture Publisher 5 Image File"));
            //fileTypes.Add(new FileTypeData(".ppf", "Picture Publisher Image File"));
            //fileTypes.Add(new FileTypeData(".ppm", "Portable Pixmap Image File"));
            //fileTypes.Add(new FileTypeData(".prw", "Artlantis Shader Preview File"));
            //fileTypes.Add(new FileTypeData(".psb", "Photoshop Large Document Format"));
            //fileTypes.Add(new FileTypeData(".psd", "Adobe Photoshop Document"));
            //fileTypes.Add(new FileTypeData(".psdx", "Photoshop Touch Document"));
            //fileTypes.Add(new FileTypeData(".pse", "Photoshop Elements Photo Project"));
            //fileTypes.Add(new FileTypeData(".psf", "PhotoStudio File"));
            //fileTypes.Add(new FileTypeData(".psp", "Paint Shop Pro Image File"));
            //fileTypes.Add(new FileTypeData(".pspbrush", "Paint Shop Photo Pro Brush File"));
            //fileTypes.Add(new FileTypeData(".pspimage", "PaintShop Pro Image"));
            //fileTypes.Add(new FileTypeData(".ptg", "ArtRage Painting"));
            //fileTypes.Add(new FileTypeData(".ptk", "Puntotek Embroidery Design File"));
            //fileTypes.Add(new FileTypeData(".pts", "PTGui Project File"));
            //fileTypes.Add(new FileTypeData(".ptx", "Pentax RAW Image File"));
            //fileTypes.Add(new FileTypeData(".ptx", "Paint Shop Pro Texture File"));
            //fileTypes.Add(new FileTypeData(".pvr", "POWERVR Texture File"));
            //fileTypes.Add(new FileTypeData(".pwp", "PhotoWorks Image File"));
            //fileTypes.Add(new FileTypeData(".px", "Pixel Image File"));
            //fileTypes.Add(new FileTypeData(".pxd", "Pixlr Layered Image"));
            //fileTypes.Add(new FileTypeData(".pxicon", "CandyBar Icon"));
            //fileTypes.Add(new FileTypeData(".pxm", "Pixelmator Image File"));
            //fileTypes.Add(new FileTypeData(".pxr", "Pixar Image File"));
            //fileTypes.Add(new FileTypeData(".pza", "PhotoSuite Album File"));
            //fileTypes.Add(new FileTypeData(".pzp", "PhotoSuite Project File"));
            //fileTypes.Add(new FileTypeData(".pzs", "PhotoSuite Slide Show File"));
            //fileTypes.Add(new FileTypeData(".qif", "QuickTime Image File"));
            //fileTypes.Add(new FileTypeData(".qmg", "Samsung Theme Graphics File"));
            //fileTypes.Add(new FileTypeData(".qti", "QuickTime Image File"));
            //fileTypes.Add(new FileTypeData(".qtif", "QuickTime Image File"));
            //fileTypes.Add(new FileTypeData(".ras", "Sun Raster Graphic"));
            //fileTypes.Add(new FileTypeData(".rcl", "Recolored Project File"));
            //fileTypes.Add(new FileTypeData(".rcu", "RealWorld Layered Cursor Image"));
            //fileTypes.Add(new FileTypeData(".rgb", "RGB Bitmap"));
            //fileTypes.Add(new FileTypeData(".rgb", "Q0 Image File"));
            //fileTypes.Add(new FileTypeData(".rgf", "LEGO MINDSTORMS EV3 Robot Graphics File"));
            //fileTypes.Add(new FileTypeData(".ric", "NXT Image File"));
            //fileTypes.Add(new FileTypeData(".rif", "Painter Raster Image File"));
            //fileTypes.Add(new FileTypeData(".riff", "Painter Raster Image"));
            //fileTypes.Add(new FileTypeData(".rix", "ColoRIX Image"));
            //fileTypes.Add(new FileTypeData(".rle", "Run Length Encoded Bitmap"));
            //fileTypes.Add(new FileTypeData(".rli", "RealWorld Graphics Layered Image"));
            //fileTypes.Add(new FileTypeData(".rpf", "Rich Pixel Format File"));
            //fileTypes.Add(new FileTypeData(".rri", "RealWorld Image"));
            //fileTypes.Add(new FileTypeData(".rs", "Sun Raster Graphic"));
            //fileTypes.Add(new FileTypeData(".rsb", "Red Storm Bitmap File"));
            //fileTypes.Add(new FileTypeData(".rsr", "Poser Model Preview File"));
            //fileTypes.Add(new FileTypeData(".rvg", "RVG X-ray Image"));
            //fileTypes.Add(new FileTypeData(".s2mv", "StarCraft 2 Map Preview File"));
            //fileTypes.Add(new FileTypeData(".sai", "PaintTool SAI Image"));
            //fileTypes.Add(new FileTypeData(".sar", "Saracen Paint Image"));
            //fileTypes.Add(new FileTypeData(".sbp", "Sketchbook Express iCloud Image"));
            //fileTypes.Add(new FileTypeData(".scg", "ColoRIX Image File"));
            //fileTypes.Add(new FileTypeData(".sci", "ColoRIX Graphics Image"));
            //fileTypes.Add(new FileTypeData(".scn", "TreePaint Image"));
            //fileTypes.Add(new FileTypeData(".scp", "ColoRIX Bitmap Graphic File"));
            //fileTypes.Add(new FileTypeData(".sct", "Scitex Continuous Tone File"));
            //fileTypes.Add(new FileTypeData(".scu", "ColoRIX Bitmap Image"));
            //fileTypes.Add(new FileTypeData(".sdr", "SmartDraw Drawing"));
            //fileTypes.Add(new FileTypeData(".sep", "Separated Image File"));
            //fileTypes.Add(new FileTypeData(".sfc", "Motic Microscope Image"));
            //fileTypes.Add(new FileTypeData(".sff", "Structured Fax File"));
            //fileTypes.Add(new FileTypeData(".sfw", "Seattle FilmWorks Image"));
            //fileTypes.Add(new FileTypeData(".sgi", "Silicon Graphics Image File"));
            //fileTypes.Add(new FileTypeData(".shg", "Segmented Hyper-Graphic"));
            //fileTypes.Add(new FileTypeData(".sid", "MrSID Image"));
            //fileTypes.Add(new FileTypeData(".sig", "Broderbund Sign File"));
            //fileTypes.Add(new FileTypeData(".sig", "QuickTac SIG File"));
            //fileTypes.Add(new FileTypeData(".sim", "Aurora Image"));
            //fileTypes.Add(new FileTypeData(".skitch", "Skitch Image"));
            //fileTypes.Add(new FileTypeData(".skm", "SketchUp Materials File"));
            //fileTypes.Add(new FileTypeData(".skypeemoticonset", "Skype Emoticon Set File"));
            //fileTypes.Add(new FileTypeData(".sld", "AutoCAD Slide File"));
            //fileTypes.Add(new FileTypeData(".smp", "Xionics SMP Image"));
            //fileTypes.Add(new FileTypeData(".sob", "OpenOffice.org Impress Bimap Styles File"));
            //fileTypes.Add(new FileTypeData(".spa", "MikuMikuDance Sphere Mapping File"));
            //fileTypes.Add(new FileTypeData(".spc", "Spectrum 512 Compressed Image"));
            //fileTypes.Add(new FileTypeData(".spe", "WinSpec CCD Capture File"));
            //fileTypes.Add(new FileTypeData(".sph", "MikuMikuDance Sphere Mapping File"));
            //fileTypes.Add(new FileTypeData(".spiff", "Still Picture Interchange File Format"));
            //fileTypes.Add(new FileTypeData(".spj", "Microsoft ICE Panorama Project"));
            //fileTypes.Add(new FileTypeData(".spp", "Serif PhotoPlus Picture File"));
            //fileTypes.Add(new FileTypeData(".spr", "Half-Life Sprite File"));
            //fileTypes.Add(new FileTypeData(".sprite", "Scratch Sprite File"));
            //fileTypes.Add(new FileTypeData(".sprite2", "Scratch 2.0 Sprite File"));
            //fileTypes.Add(new FileTypeData(".spu", "Spectrum 512 Image"));
            //fileTypes.Add(new FileTypeData(".sr", "Sun Raster Image File"));
            //fileTypes.Add(new FileTypeData(".ste", "Samsung IPOLIS Image File"));
            //fileTypes.Add(new FileTypeData(".sumo", "Sumo Paint Image"));
            //fileTypes.Add(new FileTypeData(".sun", "Sun Raster Graphic File"));
            //fileTypes.Add(new FileTypeData(".suniff", "Sun TAAC Image"));
            //fileTypes.Add(new FileTypeData(".sup", "Subtitle Bitmap File"));
            //fileTypes.Add(new FileTypeData(".sva", "Manga Browser Comic File"));
            //fileTypes.Add(new FileTypeData(".svm", "StarView Metafile"));
            //fileTypes.Add(new FileTypeData(".t2b", "CyBook Thumbnail Image"));
            //fileTypes.Add(new FileTypeData(".taac", "Sun TAAC Image File"));
            //fileTypes.Add(new FileTypeData(".tb0", "Adobe Photoshop Thumbnail Cache File"));
            //fileTypes.Add(new FileTypeData(".tbn", "Kodi Thumbnail Image"));
            //fileTypes.Add(new FileTypeData(".tex", "Texture File"));
            //fileTypes.Add(new FileTypeData(".tfc", "Unreal Engine 3 Texture File Cache"));
            //fileTypes.Add(new FileTypeData(".tg4", "Tiled Group 4 Raster Image File"));
            //fileTypes.Add(new FileTypeData(".tga", "Targa Graphic"));
            //fileTypes.Add(new FileTypeData(".thm", "Video Thumbnail File"));
            //fileTypes.Add(new FileTypeData(".thm", "Thumbnail Image File"));
            //fileTypes.Add(new FileTypeData(".thumb", "JAlbum Thumbnail File"));
            //fileTypes.Add(new FileTypeData(".tif", "Tagged Image File"));
            //fileTypes.Add(new FileTypeData(".tif", "GeoTIFF Image"));
            //fileTypes.Add(new FileTypeData(".tiff", "Tagged Image File Format"));
            //fileTypes.Add(new FileTypeData(".tjp", "Tiled JPEG File"));
            //fileTypes.Add(new FileTypeData(".tm2", "PlayStation 2 Graphic"));
            //fileTypes.Add(new FileTypeData(".tn", "LG Phone Image"));
            //fileTypes.Add(new FileTypeData(".tn1", "Tiny Low Resolution Image"));
            //fileTypes.Add(new FileTypeData(".tn2", "Tiny Medium Resolution Image"));
            //fileTypes.Add(new FileTypeData(".tn3", "Tiny High Resolution Image"));
            //fileTypes.Add(new FileTypeData(".tny", "Atari Tiny Image"));
            //fileTypes.Add(new FileTypeData(".tpf", "TexMod Package File"));
            //fileTypes.Add(new FileTypeData(".tpi", "TrueVision Bitmap Image"));
            //fileTypes.Add(new FileTypeData(".tps", "TexturePacker Sprite Sheet File"));
            //fileTypes.Add(new FileTypeData(".trif", "Tiled Raster Interchange Format"));
            //fileTypes.Add(new FileTypeData(".tsr", "TIFF Simple Rare File"));
            //fileTypes.Add(new FileTypeData(".tub", "Paint Shop Pro Picture Tube"));
            //fileTypes.Add(new FileTypeData(".u", "Subsampled Raw YUV Image"));
            //fileTypes.Add(new FileTypeData(".ufo", "Ulead File Object"));
            //fileTypes.Add(new FileTypeData(".uga", "Ulead GIF Animator File"));
            //fileTypes.Add(new FileTypeData(".urt", "Utah Raster Toolkit File"));
            //fileTypes.Add(new FileTypeData(".usertil", "-ms	Windows 8 User Tile File"));
            //fileTypes.Add(new FileTypeData(".v", "Subsampled Raw YUV Image"));
            //fileTypes.Add(new FileTypeData(".vda", "Targa Bitmap Image File"));
            //fileTypes.Add(new FileTypeData(".vff", "Sun TAAC Graphic File"));
            //fileTypes.Add(new FileTypeData(".vic", "VICAR Image"));
            //fileTypes.Add(new FileTypeData(".viff", "Visualization Image File Format"));
            //fileTypes.Add(new FileTypeData(".vna", "JVC JLIP Image"));
            //fileTypes.Add(new FileTypeData(".vpe", "Photoshop Vanishing Point Export File"));
            //fileTypes.Add(new FileTypeData(".vrimg", "V-Ray Image File"));
            //fileTypes.Add(new FileTypeData(".vrphoto", "VR Photo Image"));
            //fileTypes.Add(new FileTypeData(".vss", "Visio Stencil File"));
            //fileTypes.Add(new FileTypeData(".vst", "Targa Bitmap Image"));
            //fileTypes.Add(new FileTypeData(".wb0", "Webshots Picture File"));
            //fileTypes.Add(new FileTypeData(".wb1", "Webshots Picture File"));
            //fileTypes.Add(new FileTypeData(".wb2", "Webshots Picture File"));
            //fileTypes.Add(new FileTypeData(".wbc", "Webshots Collection File"));
            //fileTypes.Add(new FileTypeData(".wbd", "Webshots Picture File"));
            //fileTypes.Add(new FileTypeData(".wbm", "Wireless Bitmap Image"));
            //fileTypes.Add(new FileTypeData(".wbmp", "Wireless Bitmap Image File"));
            //fileTypes.Add(new FileTypeData(".wbp", "Webshots Collection File"));
            //fileTypes.Add(new FileTypeData(".wbz", "Webshots Download Picture File"));
            //fileTypes.Add(new FileTypeData(".wdp", "Windows Media Photo File"));
            //fileTypes.Add(new FileTypeData(".webp", "WebP Image"));
            //fileTypes.Add(new FileTypeData(".wi", "Wavelet Image"));
            //fileTypes.Add(new FileTypeData(".wic", "J Wavelet Image"));
            //fileTypes.Add(new FileTypeData(".wmp", "Windows Media Photo File"));
            //fileTypes.Add(new FileTypeData(".wpb", "openCanvas 1.1 Image"));
            //fileTypes.Add(new FileTypeData(".wpe", "openCanvas 1.1 Event File"));
            //fileTypes.Add(new FileTypeData(".wvl", "Wavelet Image"));
            //fileTypes.Add(new FileTypeData(".xbm", "X11 Bitmap Graphic"));
            //fileTypes.Add(new FileTypeData(".xcf", "GIMP Image File"));
            //fileTypes.Add(new FileTypeData(".xpm", "X11 Pixmap Graphic"));
            //fileTypes.Add(new FileTypeData(".xwd", "X Windows Dump Image"));
            //fileTypes.Add(new FileTypeData(".y", "Subsampled Raw YUV Image"));
            //fileTypes.Add(new FileTypeData(".ysp", "BYOB Sprite File"));
            //fileTypes.Add(new FileTypeData(".yuv", "YUV Encoded Image File"));
            //fileTypes.Add(new FileTypeData(".zif", "Zooming Image Format File"));

            //fileTypes.Add(new FileTypeData(".vsdx", "Visio Drawing"));
            //fileTypes.Add(new FileTypeData(".fh11", "FreeHand 11 Drawing File"));
            //fileTypes.Add(new FileTypeData(".cddz", "ConceptDraw PRO Document"));
            //fileTypes.Add(new FileTypeData(".fxg", "Flash XML Graphics File"));
            //fileTypes.Add(new FileTypeData(".cdd", "ConceptDraw PRO Document"));
            //fileTypes.Add(new FileTypeData(".dpp", "DrawPlus Drawing File"));
            //fileTypes.Add(new FileTypeData(".svg", "Scalable Vector Graphics File"));
            //fileTypes.Add(new FileTypeData(".pmg", "PageMaker Group File"));
            //fileTypes.Add(new FileTypeData(".asy", "Asymptote Module"));
            //fileTypes.Add(new FileTypeData(".cdmm", "ConceptDraw MINDMAP Document"));
            //fileTypes.Add(new FileTypeData(".hpl", "HP-GL Plotter File"));
            //fileTypes.Add(new FileTypeData(".hpg", "HPGL Plot File"));
            //fileTypes.Add(new FileTypeData(".hpgl", "HP Graphics Language Plotter File"));
            //fileTypes.Add(new FileTypeData(".igx", "iGrafx Document"));
            //fileTypes.Add(new FileTypeData(".lmk", "Sothink Logo Maker Image"));
            //fileTypes.Add(new FileTypeData(".slddrt", "SolidWorks Sheet File"));
            //fileTypes.Add(new FileTypeData(".sxd", "StarOffice Drawing"));
            //fileTypes.Add(new FileTypeData(".ai", "Adobe Illustrator File"));
            //fileTypes.Add(new FileTypeData(".plt", "AutoCAD Plotter Document"));
            //fileTypes.Add(new FileTypeData(".vsd", "Visio Drawing File"));
            //fileTypes.Add(new FileTypeData(".std", "Apache OpenOffice Drawing Template"));
            //fileTypes.Add(new FileTypeData(".fh9", "FreeHand 9 Drawing File"));
            //fileTypes.Add(new FileTypeData(".scv", "ScanVec CASmate Sign File"));
            //fileTypes.Add(new FileTypeData(".fig", "Xfig Drawing"));
            //fileTypes.Add(new FileTypeData(".eps", "Encapsulated PostScript File"));
            //fileTypes.Add(new FileTypeData(".svgz", "Compressed SVG File"));
            //fileTypes.Add(new FileTypeData(".cdr", "CorelDRAW Image File"));
            //fileTypes.Add(new FileTypeData(".gdraw", "Google Drive Drawing"));
            //fileTypes.Add(new FileTypeData(".pat", "CorelDRAW Pattern File"));
            //fileTypes.Add(new FileTypeData(".wmf", "Windows Metafile"));
            //fileTypes.Add(new FileTypeData(".ac5", "ArtCut 5 Document"));
            //fileTypes.Add(new FileTypeData(".glox", "Microsoft Office SmartArt Graphics Layout File"));
            //fileTypes.Add(new FileTypeData(".mgc", "Microsoft Clip Organizer Media Catalog"));
            //fileTypes.Add(new FileTypeData(".sk1", "sK1 Vector Graphic File"));
            //fileTypes.Add(new FileTypeData(".xmind", "XMind Workbook File"));
            //fileTypes.Add(new FileTypeData(".cvx", "Canvas Drawing File"));
            //fileTypes.Add(new FileTypeData(".graffle", "OmniGraffle Drawing"));
            //fileTypes.Add(new FileTypeData(".xar", "Xara Xtreme Drawing"));
            //fileTypes.Add(new FileTypeData(".cmx", "Corel Metafile Exchange Image File"));
            //fileTypes.Add(new FileTypeData(".pfd", "Micrografx Optima! File"));
            //fileTypes.Add(new FileTypeData(".tpl", "Canvas Template"));
            //fileTypes.Add(new FileTypeData(".emz", "Windows Compressed Enhanced Metafile"));
            //fileTypes.Add(new FileTypeData(".ps", "PostScript File"));
            //fileTypes.Add(new FileTypeData(".drw", "Drawing File"));
            //fileTypes.Add(new FileTypeData(".afdesign", "Affinity Design Document"));
            //fileTypes.Add(new FileTypeData(".artb", "Artboard Document"));
            //fileTypes.Add(new FileTypeData(".cdmt", "ConceptDraw MINDMAP Template"));
            //fileTypes.Add(new FileTypeData(".cdmtz", "Compressed ConceptDraw MINDMAP Template"));
            //fileTypes.Add(new FileTypeData(".cdmz", "Compressed ConceptDraw MINDMAP Document"));
            //fileTypes.Add(new FileTypeData(".cil", "Clip Gallery Packaged File"));
            //fileTypes.Add(new FileTypeData(".clarify", "Clarify Document"));
            //fileTypes.Add(new FileTypeData(".cv5", "Canvas 5 Drawing File"));
            //fileTypes.Add(new FileTypeData(".cvg", "Calamus Vector Graphic File"));
            //fileTypes.Add(new FileTypeData(".cvi", "Canvas Image File"));
            //fileTypes.Add(new FileTypeData(".dcs", "Desktop Color Separation File"));
            //fileTypes.Add(new FileTypeData(".design", "Microsoft Expression Design Drawing"));
            //fileTypes.Add(new FileTypeData(".dhs", "HyperSnap Drawing"));
            //fileTypes.Add(new FileTypeData(".dpr", "Digital InterPlot File"));
            //fileTypes.Add(new FileTypeData(".drawing", "Artboard Drawing"));
            //fileTypes.Add(new FileTypeData(".drw", "DESIGNER Drawing"));
            //fileTypes.Add(new FileTypeData(".dxb", "Drawing Exchange Binary"));
            //fileTypes.Add(new FileTypeData(".egc", "EximiousSoft GIF Creator Document"));
            //fileTypes.Add(new FileTypeData(".epsf", "Encapsulated PostScript Format File"));
            //fileTypes.Add(new FileTypeData(".gstencil", "OmniGraffle Stencil"));
            //fileTypes.Add(new FileTypeData(".idea", "Adobe Ideas Document"));
            //fileTypes.Add(new FileTypeData(".mgcb", "Equation Illustrator Project File"));
            //fileTypes.Add(new FileTypeData(".mgmf", "MindGenius Map File"));
            //fileTypes.Add(new FileTypeData(".mgmx", "MindGenius XML Map File"));
            //fileTypes.Add(new FileTypeData(".mp", "LaTeX MetaPost File"));
            //fileTypes.Add(new FileTypeData(".plt", "HPGL Plot File"));
            //fileTypes.Add(new FileTypeData(".rdl", "MicroStation Redline File"));
            //fileTypes.Add(new FileTypeData(".sk2", "ChemSketch Drawing"));
            //fileTypes.Add(new FileTypeData(".snagitstamps", "Snagit Stamp Archive"));
            //fileTypes.Add(new FileTypeData(".snagstyles", "Snagit Style Archive"));
            //fileTypes.Add(new FileTypeData(".tlc", "The Logo Creator File"));
            //fileTypes.Add(new FileTypeData(".tne", "Manga Studio Tone File"));
            //fileTypes.Add(new FileTypeData(".ufr", "Ultra Fractal File"));
            //fileTypes.Add(new FileTypeData(".vbr", "GIMP Parametric Brush File"));
            //fileTypes.Add(new FileTypeData(".vml", "Vector Markup Language File"));
            //fileTypes.Add(new FileTypeData(".vst", "Visio Drawing Template"));
            //fileTypes.Add(new FileTypeData(".vstm", "Visio Macro-Enabled Drawing Template"));
            //fileTypes.Add(new FileTypeData(".vstx", "Visio Drawing Template"));
            //fileTypes.Add(new FileTypeData(".wpg", "WordPerfect Graphic File"));
            //fileTypes.Add(new FileTypeData(".wpi", "Inkling Sketch Binary File"));
            //fileTypes.Add(new FileTypeData(".xmmap", "MindManager XML Map File"));
            //fileTypes.Add(new FileTypeData(".fh7", "FreeHand 7 Drawing File"));
            //fileTypes.Add(new FileTypeData(".fif", "Fractal Image File"));
            //fileTypes.Add(new FileTypeData(".ink", "InkML Image"));
            //fileTypes.Add(new FileTypeData(".ovr", "The Overlay Maker Overlay File"));
            //fileTypes.Add(new FileTypeData(".pobj", "Photo Pos Pro Vector Object File"));
            //fileTypes.Add(new FileTypeData(".pd", "FlexiSIGN 5 Plotter Document"));
            //fileTypes.Add(new FileTypeData(".art", "Art Document"));
            //fileTypes.Add(new FileTypeData(".sda", "StarOffice Drawing"));
            //fileTypes.Add(new FileTypeData(".cgm", "Computer Graphics Metafile"));
            //fileTypes.Add(new FileTypeData(".ep", "Pencil Document"));
            //fileTypes.Add(new FileTypeData(".odg", "OpenDocument Graphic File"));
            //fileTypes.Add(new FileTypeData(".cds", "ConceptDraw SlideShow"));
            //fileTypes.Add(new FileTypeData(".csy", "Canvas Symbol File"));
            //fileTypes.Add(new FileTypeData(".fs", "FlexiSIGN Document"));
            //fileTypes.Add(new FileTypeData(".vsdm", "Visio Macro-Enabled Drawing"));
            //fileTypes.Add(new FileTypeData(".psid", "PostScript Image Data File"));
            //fileTypes.Add(new FileTypeData(".vec", "CX-Designer Shape File"));
            //fileTypes.Add(new FileTypeData(".emf", "Enhanced Windows Metafile"));
            //fileTypes.Add(new FileTypeData(".sketch", "Sketch Drawing"));
            //fileTypes.Add(new FileTypeData(".fh10", "FreeHand 10 Drawing File"));
            //fileTypes.Add(new FileTypeData(".mvg", "Magick Vector Graphics File"));
            //fileTypes.Add(new FileTypeData(".gem", "GEM Metafile"));
            //fileTypes.Add(new FileTypeData(".fh5", "FreeHand 5 Drawing File"));
            //fileTypes.Add(new FileTypeData(".dia", "Dia Diagram File"));
            //fileTypes.Add(new FileTypeData(".ezdraw", "EazyDraw Graphic"));
            //fileTypes.Add(new FileTypeData(".hgl", "HP Graphics Language File"));
            //fileTypes.Add(new FileTypeData(".pen", "Logitech io2 Drawing"));
            //fileTypes.Add(new FileTypeData(".wmz", "Compressed Windows Metafile"));
            //fileTypes.Add(new FileTypeData(".abc", "Micrografx ABC FlowCharter 6 File"));
            //fileTypes.Add(new FileTypeData(".af3", "Micrografx ABC FlowCharter 3/4 File"));
            //fileTypes.Add(new FileTypeData(".awg", "Ability Draw Document"));
            //fileTypes.Add(new FileTypeData(".cag", "ClipArt Gallery Package"));
            //fileTypes.Add(new FileTypeData(".ccx", "Corel Clipart File"));
            //fileTypes.Add(new FileTypeData(".cdlx", "ConceptDraw PRO XML Library File"));
            //fileTypes.Add(new FileTypeData(".cdsx", "ConceptDraw PRO XML SlideShow File"));
            //fileTypes.Add(new FileTypeData(".cdt", "ConceptDraw PRO Template"));
            //fileTypes.Add(new FileTypeData(".cdtx", "ConceptDraw PRO XML Template"));
            //fileTypes.Add(new FileTypeData(".cdx", "ConceptDraw PRO XML Document"));
            //fileTypes.Add(new FileTypeData(".cdx", "CorelDRAW Compressed File"));
            //fileTypes.Add(new FileTypeData(".cnv", "Canvas 6-8 Drawing File"));
            //fileTypes.Add(new FileTypeData(".cvs", "Canvas 3 Drawing File"));
            //fileTypes.Add(new FileTypeData(".ddrw", "ClarisDraw Drawing"));
            //fileTypes.Add(new FileTypeData(".ded", "Dr. Engrave Document"));
            //fileTypes.Add(new FileTypeData(".drawit", "DrawIt Drawing"));
            //fileTypes.Add(new FileTypeData(".dsf", "Designer File"));
            //fileTypes.Add(new FileTypeData(".fh6", "FreeHand 6 Drawing File"));
            //fileTypes.Add(new FileTypeData(".fh8", "FreeHand 8 Drawing File"));
            //fileTypes.Add(new FileTypeData(".fhd", "FreeHand Drawing File"));
            //fileTypes.Add(new FileTypeData(".ft11", "FreeHand 11 Drawing Template"));
            //fileTypes.Add(new FileTypeData(".ftn", "Flowton Diagram File"));
            //fileTypes.Add(new FileTypeData(".gls", "Sothink SWF Easy Shape File"));
            //fileTypes.Add(new FileTypeData(".gsd", "Graphtec Vector Graphics File"));
            //fileTypes.Add(new FileTypeData(".gtemplate", "OmniGraffle Template"));
            //fileTypes.Add(new FileTypeData(".mgmt", "MindGenius 2-3 Template"));
            //fileTypes.Add(new FileTypeData(".mgs", "MGCSoft Vector Shapes File"));
            //fileTypes.Add(new FileTypeData(".mgtx", "MindGenius XML Template File"));
            //fileTypes.Add(new FileTypeData(".mmat", "MindManager Map Template"));
            //fileTypes.Add(new FileTypeData(".otg", "OpenDocument Graphic Template"));
            //fileTypes.Add(new FileTypeData(".ovp", "The Overlay Maker Package File"));
            //fileTypes.Add(new FileTypeData(".smf", "Serif Metafile"));
            //fileTypes.Add(new FileTypeData(".ssk", "SmartSketch 95 Document"));
            //fileTypes.Add(new FileTypeData(".stn", "Genuine Fractals Image"));
            //fileTypes.Add(new FileTypeData(".svf", "Simple Vector Format Graphic"));
            //fileTypes.Add(new FileTypeData(".xpr", "Microsoft Expression Design Graphic"));
            //fileTypes.Add(new FileTypeData(".yal", "Arts & Letters Clipart Library"));
            //fileTypes.Add(new FileTypeData(".pfv", "PhotoFiltre Studio Vectorial Path"));
            //fileTypes.Add(new FileTypeData(".pl", "Unix Color Plot File"));
            //fileTypes.Add(new FileTypeData(".ac6", "ArtCut 6 Document"));
            //fileTypes.Add(new FileTypeData(".cor", "CorelDRAW Drawing"));
            //fileTypes.Add(new FileTypeData(".cwt", "ClarisWorks Texture File"));
            //fileTypes.Add(new FileTypeData(".fmv", "Frame Vector Metafile"));
            //fileTypes.Add(new FileTypeData(".igt", "iGrafx Document Template"));
            //fileTypes.Add(new FileTypeData(".dpx", "DrawPlus Template"));
            //fileTypes.Add(new FileTypeData(".zgm", "Zenographics Image File"));
            //fileTypes.Add(new FileTypeData(".af2", "Micrografx ABC FlowCharter 2 File"));
            //fileTypes.Add(new FileTypeData(".cxf", "Coordinates Export Format"));
            //fileTypes.Add(new FileTypeData(".fh3", "FreeHand 3 Drawing File"));
            //fileTypes.Add(new FileTypeData(".fh4", "FreeHand 4 Drawing File"));
            //fileTypes.Add(new FileTypeData(".ft10", "FreeHand 10 Drawing Template"));
            //fileTypes.Add(new FileTypeData(".ft7", "FreeHand 7 Drawing Template"));
            //fileTypes.Add(new FileTypeData(".ft8", "FreeHand 8 Template"));
            //fileTypes.Add(new FileTypeData(".ft9", "FreeHand 9 Drawing Template"));
            //fileTypes.Add(new FileTypeData(".gks", "Graphics Kernel System File"));
            //fileTypes.Add(new FileTypeData(".imd", "Microsoft VisioModeler File"));
            //fileTypes.Add(new FileTypeData(".ink", "Pocket PC Handwritten Note"));
            //fileTypes.Add(new FileTypeData(".nap", "NAP Metafile"));
            //fileTypes.Add(new FileTypeData(".pcs", "Microsoft Office ClipArt File"));
            //fileTypes.Add(new FileTypeData(".pws", "Print Workshop Image"));

            //fileTypes.Add(new FileTypeData(".raw", "Raw Image Data File"));
            //fileTypes.Add(new FileTypeData(".dcr", "Kodak RAW Image File"));
            //fileTypes.Add(new FileTypeData(".nef", "Nikon Electronic Format RAW Image"));
            //fileTypes.Add(new FileTypeData(".dng", "Digital Negative Image File"));
            //fileTypes.Add(new FileTypeData(".arw", "Sony Digital Camera Image"));
            //fileTypes.Add(new FileTypeData(".cr2", "Canon Raw Image File"));
            //fileTypes.Add(new FileTypeData(".srf", "Sony RAW Image"));
            //fileTypes.Add(new FileTypeData(".k25", "Kodak K25 Image"));
            //fileTypes.Add(new FileTypeData(".nrw", "Nikon Raw Image File"));
            //fileTypes.Add(new FileTypeData(".raf", "Fuji RAW Image File"));
            //fileTypes.Add(new FileTypeData(".rwz", "Rawzor Compressed Image"));
            //fileTypes.Add(new FileTypeData(".crw", "Canon Raw CIFF Image File"));
            //fileTypes.Add(new FileTypeData(".3fr", "Hasselblad 3F RAW Image"));
            //fileTypes.Add(new FileTypeData(".mos", "Leaf Camera RAW File"));
            //fileTypes.Add(new FileTypeData(".bay", "Casio RAW Image"));
            //fileTypes.Add(new FileTypeData(".x3f", "SIGMA X3F Camera RAW File"));
            //fileTypes.Add(new FileTypeData(".fff", "Hasselblad RAW Image"));
            //fileTypes.Add(new FileTypeData(".orf", "Olympus RAW File"));
            //fileTypes.Add(new FileTypeData(".rwl", "Leica RAW Image"));
            //fileTypes.Add(new FileTypeData(".mfw", "Mamiya Camera Raw File"));
            //fileTypes.Add(new FileTypeData(".ari", "ARRIRAW Image"));
            //fileTypes.Add(new FileTypeData(".j6i", "Ricoh Camera Image File"));
            //fileTypes.Add(new FileTypeData(".cxi", "FMAT RAW Image"));
            //fileTypes.Add(new FileTypeData(".erf", "Epson RAW File"));
            //fileTypes.Add(new FileTypeData(".kdc", "Kodak Photo-Enhancer File"));
            //fileTypes.Add(new FileTypeData(".mef", "Mamiya RAW Image"));
            //fileTypes.Add(new FileTypeData(".sr2", "Sony RAW Image"));
            //fileTypes.Add(new FileTypeData(".mrw", "Minolta Raw Image File"));
            //fileTypes.Add(new FileTypeData(".pef", "Pentax Electronic File"));
            //fileTypes.Add(new FileTypeData(".rw2", "Panasonic RAW Image"));
            //fileTypes.Add(new FileTypeData(".eip", "Enhanced Image Package File"));
            //fileTypes.Add(new FileTypeData(".srw", "Samsung RAW Image"));
            //fileTypes.Add(new FileTypeData(".iiq", "Phase One RAW Image"));



            return fileTypes;
        }
    }
}
