using DriveIndexer.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DriveIndexer.Database
{
    public class DefaultFileTypesWeb
    {
        // http://fileinfo.com/filetypes/video
        public static List<FileTypeData> DefaultTypes()
        {
            List<FileTypeData> fileTypes = new List<FileTypeData>();

            //fileTypes.Add(new FileTypeData(".crt", "Security Certificate"));
            //fileTypes.Add(new FileTypeData(".cer", "Internet Security Certificate"));
            //fileTypes.Add(new FileTypeData(".dwt", "Dreamweaver Web Page Template"));
            //fileTypes.Add(new FileTypeData(".wsdl", "Web Services Description Language File"));
            //fileTypes.Add(new FileTypeData(".a4p", "A4Desk Pro Project File"));
            fileTypes.Add(new FileTypeData(".css", "Cascading Style Sheet"));
            //fileTypes.Add(new FileTypeData(".dcr", "Shockwave Media File"));
            //fileTypes.Add(new FileTypeData(".ucf", "WebEx Media File"));
            //fileTypes.Add(new FileTypeData(".ascx", "ASP.NET User Control File"));
            //fileTypes.Add(new FileTypeData(".zul", "ZK User Interface File"));
            //fileTypes.Add(new FileTypeData(".crl", "Certificate Revocation List File"));
            //fileTypes.Add(new FileTypeData(".dhtml", "Dynamic HTML file"));
            //fileTypes.Add(new FileTypeData(".kit", "CodeKit File"));
            //fileTypes.Add(new FileTypeData(".shtm", "HTML Server Side Include File"));
            //fileTypes.Add(new FileTypeData(".vrml", "VRML File"));
            //fileTypes.Add(new FileTypeData(".xht", "XHTML File"));
            //fileTypes.Add(new FileTypeData(".sdb", "SocialDecks Blog File"));
            //fileTypes.Add(new FileTypeData(".vrt", "Virtual World"));
            //fileTypes.Add(new FileTypeData(".rss", "Rich Site Summary"));
            //fileTypes.Add(new FileTypeData(".website", "Internet Explorer Pinned Site Shortcut"));
            //fileTypes.Add(new FileTypeData(".browser", "ASP.NET Browser Definition File"));
            //fileTypes.Add(new FileTypeData(".pro", "Adobe Proto Design File"));
            //fileTypes.Add(new FileTypeData(".site", "GoLive Website Project File"));
            //fileTypes.Add(new FileTypeData(".dll", "DLL Dynamic Web Page"));
            //fileTypes.Add(new FileTypeData(".csr", "Certificate Signing Request File"));
            //fileTypes.Add(new FileTypeData(".alx", "ActiveX Layout Control File"));
            //fileTypes.Add(new FileTypeData(".gsp", "IMail Error Message File"));
            //fileTypes.Add(new FileTypeData(".htm", "Hypertext Markup Language File"));
            //fileTypes.Add(new FileTypeData(".cshtml", "ASP.NET Razor Web Page"));
            //fileTypes.Add(new FileTypeData(".htaccess", "Apache HTACCESS File"));
            //fileTypes.Add(new FileTypeData(".xul", "XML User Interface Language File"));
            //fileTypes.Add(new FileTypeData(".download", "Partially Downloaded File"));
            //fileTypes.Add(new FileTypeData(".dap", "Access Data Access Page"));
            //fileTypes.Add(new FileTypeData(".axd", "ASP.NET Web Handler File"));
            //fileTypes.Add(new FileTypeData(".php", "PHP Source Code File"));
            //fileTypes.Add(new FileTypeData(".json", "JavaScript Object Notation File"));
            //fileTypes.Add(new FileTypeData(".cfm", "ColdFusion Markup File"));
            //fileTypes.Add(new FileTypeData(".asax", "ASP.NET Server Application File"));
            //fileTypes.Add(new FileTypeData(".asmx", "ASP.NET Web Service File"));
            //fileTypes.Add(new FileTypeData(".atom", "Atom Syndication Format"));
            //fileTypes.Add(new FileTypeData(".fcgi", "FastCGI File"));
            //fileTypes.Add(new FileTypeData(".hype", "Hype Document"));
            //fileTypes.Add(new FileTypeData(".opml", "Outline Processor Markup Language File"));
            //fileTypes.Add(new FileTypeData(".xhtm", "Extensible Hypertext Markup Language Document"));
            //fileTypes.Add(new FileTypeData(".appcache", "HTML5 Cache Manifest File"));
            //fileTypes.Add(new FileTypeData(".asa", "ASP Configuration File"));
            //fileTypes.Add(new FileTypeData(".asr", "ActionScript Remote Document"));
            //fileTypes.Add(new FileTypeData(".awm", "AllWebMenus Project File"));
            //fileTypes.Add(new FileTypeData(".bml", "Bean Markup Language File"));
            //fileTypes.Add(new FileTypeData(".codasite", "Coda Site File"));
            //fileTypes.Add(new FileTypeData(".epibrw", "Web File Location"));
            //fileTypes.Add(new FileTypeData(".fwp", "Microsoft Expression Web Package"));
            //fileTypes.Add(new FileTypeData(".gne", "Flickr Web Page"));
            //fileTypes.Add(new FileTypeData(".idc", "Internet Database Connector File"));
            //fileTypes.Add(new FileTypeData(".oam", "Adobe Edge Animate Widget File"));
            //fileTypes.Add(new FileTypeData(".ognc", "Dynamic Web Page"));
            //fileTypes.Add(new FileTypeData(".rhtml", "Ruby HTML Web Page"));
            //fileTypes.Add(new FileTypeData(".rjs", "Ruby Javascript File"));
            //fileTypes.Add(new FileTypeData(".shtml", "Server Side Include HTML File"));
            //fileTypes.Add(new FileTypeData(".sites", "iWeb Site Design Project"));
            //fileTypes.Add(new FileTypeData(".sites2", "iWeb Site Design Project"));
            //fileTypes.Add(new FileTypeData(".srf", "Server Response File"));
            //fileTypes.Add(new FileTypeData(".vbd", "Visual Basic ActiveX Document"));
            //fileTypes.Add(new FileTypeData(".vsdisco", "DISCO Dynamic Discovery Document"));
            //fileTypes.Add(new FileTypeData(".xpd", "XML Pipeline Document"));
            //fileTypes.Add(new FileTypeData(".prf", "PICS Rules File"));
            //fileTypes.Add(new FileTypeData(".cms", "Content Management System"));
            fileTypes.Add(new FileTypeData(".js", "JavaScript File"));
            //fileTypes.Add(new FileTypeData(".maff", "Mozilla Archive Format File"));
            //fileTypes.Add(new FileTypeData(".asp", "Active Server Page"));
            //fileTypes.Add(new FileTypeData(".chm", "Compiled HTML Help File"));
            //fileTypes.Add(new FileTypeData(".spc", "Software Publisher Certificate File"));
            //fileTypes.Add(new FileTypeData(".url", "Internet Shortcut"));
            //fileTypes.Add(new FileTypeData(".a5w", "Alpha Five Webpage File"));
            //fileTypes.Add(new FileTypeData(".ap", "Active Page"));
            //fileTypes.Add(new FileTypeData(".svr", "Compressed Virtual World"));
            //fileTypes.Add(new FileTypeData(".aspx", "Active Server Page Extended File"));
            //fileTypes.Add(new FileTypeData(".pac", "Proxy Auto-Config File"));
            //fileTypes.Add(new FileTypeData(".xhtml", "Extensible Hypertext Markup Language File"));
            //fileTypes.Add(new FileTypeData(".nzb", "NewzBin Usenet Index File"));
            //fileTypes.Add(new FileTypeData(".muse", "Adobe Muse Website Project"));
            //fileTypes.Add(new FileTypeData(".p7c", "PKCS #7 Certificate File"));
            //fileTypes.Add(new FileTypeData(".scss", "Sass Cascading Style Sheet"));
            //fileTypes.Add(new FileTypeData(".stc", "Contribute Connection Key File"));
            //fileTypes.Add(new FileTypeData(".swz", "Adobe Flash Player Cache File"));
            //fileTypes.Add(new FileTypeData(".wdgt", "Opera Widget"));
            //fileTypes.Add(new FileTypeData(".widget", "HybridJava Widget"));
            //fileTypes.Add(new FileTypeData(".xws", "Xara Web Designer Graphic"));
            //fileTypes.Add(new FileTypeData(".compressed", "WordCompress Compacted Web File"));
            //fileTypes.Add(new FileTypeData(".dothtml", "Microsoft Word HTML Document Template"));
            //fileTypes.Add(new FileTypeData(".webarchive", "Safari Web Archive"));
            //fileTypes.Add(new FileTypeData(".do", "Java Servlet"));
            //fileTypes.Add(new FileTypeData(".ashx", "ASP.NET Web Handler File"));
            fileTypes.Add(new FileTypeData(".html", "Hypertext Markup Language File"));
            //fileTypes.Add(new FileTypeData(".wml", "Wireless Markup Language File"));
            //fileTypes.Add(new FileTypeData(".mspx", "Microsoft ASP.NET Web Page"));
            //fileTypes.Add(new FileTypeData(".jnlp", "Java Web Start File"));
            //fileTypes.Add(new FileTypeData(".jsp", "Java Server Page"));
            //fileTypes.Add(new FileTypeData(".obml", "Opera Mini Saved Web Page"));
            //fileTypes.Add(new FileTypeData(".dbm", "ColdFusion Server File"));
            //fileTypes.Add(new FileTypeData(".dml", "DynaScript File"));
            //fileTypes.Add(new FileTypeData(".fmp", "123 Flash Menu Project"));
            //fileTypes.Add(new FileTypeData(".master", "ASP.NET Master Page"));
            //fileTypes.Add(new FileTypeData(".phtml", "PHP Web Page"));
            //fileTypes.Add(new FileTypeData(".sht", "HTML File with Server Side Includes"));
            //fileTypes.Add(new FileTypeData(".svc", "WCF Web Service File"));
            //fileTypes.Add(new FileTypeData(".wbs", "WebBlender Project File"));
            //fileTypes.Add(new FileTypeData(".webarchivexml", "Android Web Browser Archive"));
            //fileTypes.Add(new FileTypeData(".wgp", "Web Gallery Project"));
            //fileTypes.Add(new FileTypeData(".xbl", "Extensible Binding Language File"));
            //fileTypes.Add(new FileTypeData(".xss", "XML Style Sheet"));
            //fileTypes.Add(new FileTypeData(".php4", "PHP 4 Web Page"));
            //fileTypes.Add(new FileTypeData(".wpp", "WebPlus Project File"));
            //fileTypes.Add(new FileTypeData(".webloc", "Mac OS X Website Location"));
            //fileTypes.Add(new FileTypeData(".jspx", "XML Java Server Page"));
            //fileTypes.Add(new FileTypeData(".web", "Xara Web Document"));
            //fileTypes.Add(new FileTypeData(".seam", "Seam Framework Java Servlet File"));
            //fileTypes.Add(new FileTypeData(".con", "Concept Application Source File"));
            //fileTypes.Add(new FileTypeData(".pem", "Privacy Enhanced Mail Certificate"));
            //fileTypes.Add(new FileTypeData(".att", "Web Form Post Data File"));
            //fileTypes.Add(new FileTypeData(".qbo", "QuickBooks Online Bank Statement File"));
            //fileTypes.Add(new FileTypeData(".chat", "IRC Chat Configuration File"));
            //fileTypes.Add(new FileTypeData(".tvpi", "TitanTV Television Listing File"));
            //fileTypes.Add(new FileTypeData(".hdml", "Handheld Device Markup Language File"));
            //fileTypes.Add(new FileTypeData(".jsf", "Java Script Command File"));
            //fileTypes.Add(new FileTypeData(".p12", "Personal Information Exchange File"));
            //fileTypes.Add(new FileTypeData(".adr", "Opera Bookmarks File"));
            //fileTypes.Add(new FileTypeData(".xfdl", "XFDL File"));
            //fileTypes.Add(new FileTypeData(".htc", "HTML Component File"));
            //fileTypes.Add(new FileTypeData(".mht", "MHTML Web Archive"));
            //fileTypes.Add(new FileTypeData(".wrf", "WebEx Recording"));
            //fileTypes.Add(new FileTypeData(".an", "Adobe Edge Animate Project File"));
            //fileTypes.Add(new FileTypeData(".aro", "SteelArrow Web Application File"));
            //fileTypes.Add(new FileTypeData(".btapp", "uTorrent App"));
            //fileTypes.Add(new FileTypeData(".cha", "IRC Chat Configuration File"));
            //fileTypes.Add(new FileTypeData(".der", "DER Certificate File"));
            //fileTypes.Add(new FileTypeData(".disco", "DISCO Discovery Document"));
            //fileTypes.Add(new FileTypeData(".discomap", "DISCO Discovery Output File"));
            //fileTypes.Add(new FileTypeData(".edge", "Adobe Edge Project File"));
            //fileTypes.Add(new FileTypeData(".esproj", "Espresso Project File"));
            //fileTypes.Add(new FileTypeData(".ewp", "Ewisoft Website Project File"));
            //fileTypes.Add(new FileTypeData(".hxs", "Help 2 Compiled Help File"));
            //fileTypes.Add(new FileTypeData(".hyperesources", "Hype Resources Folder"));
            //fileTypes.Add(new FileTypeData(".hypesymbol", "Hype Symbol File"));
            //fileTypes.Add(new FileTypeData(".hypetemplate", "Hype Document Template"));
            //fileTypes.Add(new FileTypeData(".iwdgt", "iWeb Widget File"));
            //fileTypes.Add(new FileTypeData(".jws", "Java Web Services File"));
            //fileTypes.Add(new FileTypeData(".lasso", "Lasso Database-Driven Web Page"));
            //fileTypes.Add(new FileTypeData(".lbc", "Cloaked Affiliate Link Builder Saved Link"));
            //fileTypes.Add(new FileTypeData(".mvc", "MivaScript Compiled File"));
            //fileTypes.Add(new FileTypeData(".nod", "NetObjects Fusion File"));
            //fileTypes.Add(new FileTypeData(".olp", "Office Live Package"));
            //fileTypes.Add(new FileTypeData(".oth", "OpenDocument HTML Template"));
            //fileTypes.Add(new FileTypeData(".p7b", "PKCS #7 Certificate File"));
            //fileTypes.Add(new FileTypeData(".qf", "Qompose Web Page Template"));
            //fileTypes.Add(new FileTypeData(".rflw", "Edge Reflow Data File"));
            //fileTypes.Add(new FileTypeData(".rwsw", "RapidWeaver Site File"));
            //fileTypes.Add(new FileTypeData(".saveddeck", "Nokia Saved Web Page"));
            //fileTypes.Add(new FileTypeData(".suck", "SiteSucker Website File"));
            //fileTypes.Add(new FileTypeData(".vbhtml", "ASP.NET Razor Web Page"));
            //fileTypes.Add(new FileTypeData(".webbookmark", "Safari Web Bookmark File"));
            //fileTypes.Add(new FileTypeData(".whtt", "HTTrack Website Copier File"));
            //fileTypes.Add(new FileTypeData(".xbel", "XBEL Bookmarks File"));
            //fileTypes.Add(new FileTypeData(".zhtml", "RabbitWeb Webpage"));
            //fileTypes.Add(new FileTypeData(".zhtml", "Secure IE Zipped HTML File"));
            //fileTypes.Add(new FileTypeData(".zvz", "Possible Virus File"));
            //fileTypes.Add(new FileTypeData(".csp", "Concept Server Page"));
            //fileTypes.Add(new FileTypeData(".phtm", "PHP-Based Web Page"));
            //fileTypes.Add(new FileTypeData(".ppthtml", "PowerPoint HTML Presentation"));
            //fileTypes.Add(new FileTypeData(".pptmhtml", "Microsoft PowerPoint MIME HTML Presentation"));
            //fileTypes.Add(new FileTypeData(".stml", "SSI HTML File"));
            //fileTypes.Add(new FileTypeData(".bok", "ProStores Dynamic Web Page"));
            //fileTypes.Add(new FileTypeData(".uhtml", "UC Browser Saved Webpage"));
            //fileTypes.Add(new FileTypeData(".aex", "Alpha Five Compiled Global Functions File"));
            //fileTypes.Add(new FileTypeData(".htx", "HTML Extension File"));
            //fileTypes.Add(new FileTypeData(".mhtml", "MIME HTML File"));
            //fileTypes.Add(new FileTypeData(".tvvi", "TitanTV Television Listing File"));
            //fileTypes.Add(new FileTypeData(".dochtml", "Microsoft Word HTML Document"));
            //fileTypes.Add(new FileTypeData(".jhtml", "Java HTML Web Page"));
            //fileTypes.Add(new FileTypeData(".vdw", "Visio Web Drawing"));
            //fileTypes.Add(new FileTypeData(".webhistory", "Safari Web History File"));
            //fileTypes.Add(new FileTypeData(".vlp", "LiveSite Project"));
            //fileTypes.Add(new FileTypeData(".wgt", "Opera Widget File"));
            //fileTypes.Add(new FileTypeData(".pub", "Public Key File"));
            //fileTypes.Add(new FileTypeData(".stl", "Certificate Trust List"));
            //fileTypes.Add(new FileTypeData(".rt", "RealText Streaming Text File"));
            //fileTypes.Add(new FileTypeData(".docmhtml", "Microsoft Word MIME HTML Document"));
            //fileTypes.Add(new FileTypeData(".less", "LESS Style Sheet"));
            //fileTypes.Add(new FileTypeData(".rwp", "RapidWeaver Package"));
            //fileTypes.Add(new FileTypeData(".sitemap", "ASP.NET Site Map File"));
            //fileTypes.Add(new FileTypeData(".woa", "WebObjects Application"));
            //fileTypes.Add(new FileTypeData(".ccbjs", "CopperCube JavaScript File"));
            //fileTypes.Add(new FileTypeData(".cfml", "ColdFusion Markup Language File"));
            //fileTypes.Add(new FileTypeData(".ece", "Escenic Dynamic Web Page"));
            //fileTypes.Add(new FileTypeData(".iqy", "Internet Query"));
            //fileTypes.Add(new FileTypeData(".itms", "iTunes Music Store Link File"));
            //fileTypes.Add(new FileTypeData(".itpc", "iTunes Podcast Link File"));
            //fileTypes.Add(new FileTypeData(".jcz", "Liquid Motion Animation"));
            //fileTypes.Add(new FileTypeData(".jspa", "Java Servlet Alias"));
            //fileTypes.Add(new FileTypeData(".jss", "JavaScript Style Sheet File"));
            //fileTypes.Add(new FileTypeData(".jst", "JavaServer Page Document"));
            //fileTypes.Add(new FileTypeData(".mapx", "Mapjects Client Webparts File"));
            //fileTypes.Add(new FileTypeData(".nxg", "eSite Builder NXG Web Page"));
            //fileTypes.Add(new FileTypeData(".p7", "PKCS #7 Digital Certificate File"));
            //fileTypes.Add(new FileTypeData(".page", "HybridJava Web Page"));
            //fileTypes.Add(new FileTypeData(".ptw", "AutoCAD Publish To Web File"));
            //fileTypes.Add(new FileTypeData(".qrm", "Qworum Message File"));
            //fileTypes.Add(new FileTypeData(".rw3", "RapidWeaver 3 Site File"));
            //fileTypes.Add(new FileTypeData(".rwtheme", "RapidWeaver Theme"));
            //fileTypes.Add(new FileTypeData(".ssp", "Scala Server Page"));
            //fileTypes.Add(new FileTypeData(".stm", "SSI Web Page"));
            //fileTypes.Add(new FileTypeData(".stp", "SharePoint Template"));
            //fileTypes.Add(new FileTypeData(".wbxml", "WAP Binary XML File"));
            //fileTypes.Add(new FileTypeData(".wn", "WN Web File"));
            //fileTypes.Add(new FileTypeData(".wpx", "WebPlus Project Template"));
            //fileTypes.Add(new FileTypeData(".psp", "PL/SQL Server Page"));
            //fileTypes.Add(new FileTypeData(".zfo", "XSL-FO Online Form"));
            //fileTypes.Add(new FileTypeData(".cpg", "Cool Page Project File"));
            //fileTypes.Add(new FileTypeData(".php3", "PHP 3 Web Page"));
            //fileTypes.Add(new FileTypeData(".php5", "PHP 5 Web Page"));
            //fileTypes.Add(new FileTypeData(".bwp", "BuRg3r Web Page"));
            //fileTypes.Add(new FileTypeData(".cdf", "Channel Definition Format"));
            //fileTypes.Add(new FileTypeData(".hdm", "HDML File"));
            //fileTypes.Add(new FileTypeData(".jvs", "JavaScript Proxy Autoconfig File"));
            //fileTypes.Add(new FileTypeData(".map", "Image Map"));
            //fileTypes.Add(new FileTypeData(".moz", "Mozilla Cache File"));
            //fileTypes.Add(new FileTypeData(".mvr", "IBM HotMedia Multimedia File"));


            return fileTypes;
        }
    }
}
