using DriveIndexer.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DriveIndexer.Database
{
    public class DefaultFileTypesExecutable
    {
        public static List<FileTypeData> AllKnownTypes()
        {
            List<FileTypeData> fileTypes = new List<FileTypeData>();

            fileTypes.Add(new FileTypeData(".ac", "Autoconf Script"));
            fileTypes.Add(new FileTypeData(".0xe", "F-Secure Renamed Virus File"));
            fileTypes.Add(new FileTypeData(".ex_", "Renamed Windows Executable File"));
            fileTypes.Add(new FileTypeData(".scar", "SCAR Script"));
            fileTypes.Add(new FileTypeData(".widget", "Microsoft Windows Mobile Widget"));
            fileTypes.Add(new FileTypeData(".celx", "Celestia Script"));
            fileTypes.Add(new FileTypeData(".ahk", "AutoHotkey Script"));
            fileTypes.Add(new FileTypeData(".ebs2", "E-Run 2.0 Script File"));
            fileTypes.Add(new FileTypeData(".icd", "SafeDisc Encrypted Program"));
            fileTypes.Add(new FileTypeData(".mrp", "Mobile Application File"));
            fileTypes.Add(new FileTypeData(".rgs", "Registry Script"));
            fileTypes.Add(new FileTypeData(".gadget", "Windows Gadget"));
            fileTypes.Add(new FileTypeData(".73k", "TI-73 Application"));
            fileTypes.Add(new FileTypeData(".isu", "InstallShield Uninstaller Script"));
            fileTypes.Add(new FileTypeData(".widget", "Yahoo! Widget"));
            fileTypes.Add(new FileTypeData(".rxe", "Lego Mindstorms NXT Executable Program"));
            fileTypes.Add(new FileTypeData(".ear", "Java Enterprise Archive File"));
            fileTypes.Add(new FileTypeData(".cof", "MPLAB COFF File"));
            fileTypes.Add(new FileTypeData(".run", "Linux Executable File"));
            fileTypes.Add(new FileTypeData(".scr", "Script File"));
            fileTypes.Add(new FileTypeData(".xap", "Silverlight Application Package"));
            fileTypes.Add(new FileTypeData(".cel", "Celestia Script File"));
            fileTypes.Add(new FileTypeData(".pa", ".exe	PortableApps.com Program File"));
            fileTypes.Add(new FileTypeData(".xbap", "XAML Browser Application File"));
            fileTypes.Add(new FileTypeData(".a6p", "Authorware 6 Program"));
            fileTypes.Add(new FileTypeData(".csh", "C Shell Script"));
            fileTypes.Add(new FileTypeData(".dld", "EdLog Compiled Program"));
            fileTypes.Add(new FileTypeData(".fas", "Compiled Fast-Load AutoLISP File"));
            fileTypes.Add(new FileTypeData(".hms", "HostMonitor Script File"));
            fileTypes.Add(new FileTypeData(".mcr", "3ds Max Macroscript File"));
            fileTypes.Add(new FileTypeData(".ms", "Maxwell Script"));
            fileTypes.Add(new FileTypeData(".qit", "QIT Trojan Horse File"));
            fileTypes.Add(new FileTypeData(".seed", "Linux Preseed File"));
            fileTypes.Add(new FileTypeData(".exe1", "Renamed EXE File"));
            fileTypes.Add(new FileTypeData(".air", "Adobe AIR Installation Package"));
            fileTypes.Add(new FileTypeData(".fxp", "FoxPro Compiled Program"));
            fileTypes.Add(new FileTypeData(".scb", "Scala Published Script"));
            fileTypes.Add(new FileTypeData(".zl9", "ZoneAlarm Quarantined EXE File"));
            fileTypes.Add(new FileTypeData(".prg", "Program File"));
            fileTypes.Add(new FileTypeData(".app", "Mac OS X Application"));
            fileTypes.Add(new FileTypeData(".phar", "PHP Archive"));
            fileTypes.Add(new FileTypeData(".command", "Terminal Command File"));
            fileTypes.Add(new FileTypeData(".mm", "NeXtMidas Macro File"));
            fileTypes.Add(new FileTypeData(".ex_", "Compressed Executable File"));
            fileTypes.Add(new FileTypeData(".vxp", "Mobile Application File"));
            fileTypes.Add(new FileTypeData(".ecf", "SageCRM Component File"));
            fileTypes.Add(new FileTypeData(".mel", "Maya Embedded Language File"));
            fileTypes.Add(new FileTypeData(".ws", "Windows Script"));
            fileTypes.Add(new FileTypeData(".ebm", "EXTRA! Basic Macro"));
            fileTypes.Add(new FileTypeData(".nexe", "Chrome Native Client Executable"));
            fileTypes.Add(new FileTypeData(".pyo", "Python Optimized Code"));
            fileTypes.Add(new FileTypeData(".gs", "Geosoft Script"));
            fileTypes.Add(new FileTypeData(".applescript", "AppleScript File"));
            fileTypes.Add(new FileTypeData(".prc", "Palm Resource Code File"));
            fileTypes.Add(new FileTypeData(".wsf", "Windows Script File"));
            fileTypes.Add(new FileTypeData(".app", "Symbian OS Application"));
            fileTypes.Add(new FileTypeData(".jse", "JScript Encoded File"));
            fileTypes.Add(new FileTypeData(".sbs", "SPSS Script"));
            fileTypes.Add(new FileTypeData(".scpt", "AppleScript Script File"));
            fileTypes.Add(new FileTypeData(".script", "Generic Script File"));
            fileTypes.Add(new FileTypeData(".e_e", "Renamed EXE File"));
            fileTypes.Add(new FileTypeData(".m3g", "Mobile 3D Graphics Program"));
            fileTypes.Add(new FileTypeData(".mcr", "Tecplot Macro"));
            fileTypes.Add(new FileTypeData(".rbx", "Rembo-C Compiled Script"));
            fileTypes.Add(new FileTypeData(".rpj", "Real Pac Batch Job File"));
            fileTypes.Add(new FileTypeData(".sct", "Windows Scriptlet"));
            fileTypes.Add(new FileTypeData(".upx", "Ultimate Packer for eXecutables File"));
            fileTypes.Add(new FileTypeData(".vexe", "Virus Executable File"));
            fileTypes.Add(new FileTypeData(".pif", "Program Information File"));
            fileTypes.Add(new FileTypeData(".osx", "PowerPC Executable File"));
            fileTypes.Add(new FileTypeData(".vbs", "VBScript File"));
            fileTypes.Add(new FileTypeData(".wiz", "Microsoft Wizard File"));
            fileTypes.Add(new FileTypeData(".plsc", "Messenger Plus! Live Script File"));
            fileTypes.Add(new FileTypeData(".pyc", "Python Compiled File"));
            fileTypes.Add(new FileTypeData(".x86", "Linux Executable File"));
            fileTypes.Add(new FileTypeData(".ex4", "MetaTrader Program File"));
            fileTypes.Add(new FileTypeData(".iim", "iMacro Macro File"));
            fileTypes.Add(new FileTypeData(".coffee", "CoffeeScript JavaScript File"));
            fileTypes.Add(new FileTypeData(".elf", "Nintendo Wii Game File"));
            fileTypes.Add(new FileTypeData(".89k", "TI-89 Application"));
            fileTypes.Add(new FileTypeData(".a7r", "Authorware 7 Runtime File"));
            fileTypes.Add(new FileTypeData(".acr", "ACRobot Script"));
            fileTypes.Add(new FileTypeData(".action", "Automator Action"));
            fileTypes.Add(new FileTypeData(".azw2", "Kindle Active Content App File"));
            fileTypes.Add(new FileTypeData(".beam", "Compiled Erlang File"));
            fileTypes.Add(new FileTypeData(".btm", "4DOS Batch File"));
            fileTypes.Add(new FileTypeData(".fky", "FoxPro Macro"));
            fileTypes.Add(new FileTypeData(".fpi", "FPS Creator Intelligence Script"));
            fileTypes.Add(new FileTypeData(".frs", "Flash Renamer Script"));
            fileTypes.Add(new FileTypeData(".gpe", "GP2X Video Game"));
            fileTypes.Add(new FileTypeData(".gpu", "GP2X Utility Program"));
            fileTypes.Add(new FileTypeData(".ipf", "SMS Installer Script"));
            fileTypes.Add(new FileTypeData(".jsx", "ExtendScript Script File"));
            fileTypes.Add(new FileTypeData(".kix", "KiXtart Script File"));
            fileTypes.Add(new FileTypeData(".ls", "LightWave LScript File"));
            fileTypes.Add(new FileTypeData(".mio", "MioEngine Application File"));
            fileTypes.Add(new FileTypeData(".mpx", "FoxPro Compiled Menu Program"));
            fileTypes.Add(new FileTypeData(".mrc", "mIRC Script File"));
            fileTypes.Add(new FileTypeData(".msl", "Magick Scripting Language File"));
            fileTypes.Add(new FileTypeData(".mxe", "Macro Express Playable Macro"));
            fileTypes.Add(new FileTypeData(".otm", "Outlook Macro File"));
            fileTypes.Add(new FileTypeData(".pex", "ProBoard Executable File"));
            fileTypes.Add(new FileTypeData(".pwc", "PictureTaker File"));
            fileTypes.Add(new FileTypeData(".rfu", "Remote Firmware Update"));
            fileTypes.Add(new FileTypeData(".rox", "Actuate Report Object Executable File"));
            fileTypes.Add(new FileTypeData(".sca", "Scala Script File"));
            fileTypes.Add(new FileTypeData(".scptd", "AppleScript Script Bundle"));
            fileTypes.Add(new FileTypeData(".u3p", "U3 Smart Application"));
            fileTypes.Add(new FileTypeData(".vbe", "VBScript Encoded Script File"));
            fileTypes.Add(new FileTypeData(".vdo", "Heathen Virus File"));
            fileTypes.Add(new FileTypeData(".vlx", "Compiled AutoLISP File"));
            fileTypes.Add(new FileTypeData(".wcm", "WordPerfect Macro"));
            fileTypes.Add(new FileTypeData(".workflow", "Automator Workflow"));
            fileTypes.Add(new FileTypeData(".wpm", "WordPerfect Macro File"));
            fileTypes.Add(new FileTypeData(".wsh", "Windows Script Host Settings"));
            fileTypes.Add(new FileTypeData(".xlm", "Excel Macro"));
            fileTypes.Add(new FileTypeData(".xqt", "SuperCalc Macro File"));
            fileTypes.Add(new FileTypeData(".xys", "XYplorer Script File"));
            fileTypes.Add(new FileTypeData(".n", "Neko Bytecode File"));
            fileTypes.Add(new FileTypeData(".shb", "Windows Document Shortcut"));
            fileTypes.Add(new FileTypeData(".thm", "Thermwood Macro File"));
            fileTypes.Add(new FileTypeData(".ba_", "Renamed BAT File"));
            fileTypes.Add(new FileTypeData(".ds", "TWAIN Data Source"));
            fileTypes.Add(new FileTypeData(".tms", "Telemate Script"));
            fileTypes.Add(new FileTypeData(".paf", "Portable Application Installer File"));
            fileTypes.Add(new FileTypeData(".app", "FoxPro Generated Application"));
            fileTypes.Add(new FileTypeData(".ksh", "Unix Korn Shell Script"));
            fileTypes.Add(new FileTypeData(".ms", "3ds Max Script File"));
            fileTypes.Add(new FileTypeData(".eham", "ExtraHAM Executable File"));
            fileTypes.Add(new FileTypeData(".spr", "FoxPro Generated Screen File"));
            fileTypes.Add(new FileTypeData(".mem", "Macro Editor Macro"));
            fileTypes.Add(new FileTypeData(".out", "Compiled Executable File"));
            fileTypes.Add(new FileTypeData(".plx", "Perl Executable File"));
            fileTypes.Add(new FileTypeData(".actm", "AutoCAD Action Macro File"));
            fileTypes.Add(new FileTypeData(".arscript", "ArtRage Script"));
            fileTypes.Add(new FileTypeData(".asb", "Alphacam Stone VB Macro File"));
            fileTypes.Add(new FileTypeData(".dxl", "Rational DOORS Script"));
            fileTypes.Add(new FileTypeData(".ebs", "E-Run 1.x Script"));
            fileTypes.Add(new FileTypeData(".es", "SageCRM Script File"));
            fileTypes.Add(new FileTypeData(".exopc", "ExoPC Application"));
            fileTypes.Add(new FileTypeData(".ezt", "EZT Malicious Worm File"));
            fileTypes.Add(new FileTypeData(".fas", "QuickSilver Fast Save Lisp File"));
            fileTypes.Add(new FileTypeData(".ita", "VTech InnoTab Application File"));
            fileTypes.Add(new FileTypeData(".mam", "Microsoft Access Macro"));
            fileTypes.Add(new FileTypeData(".qpx", "FoxPro Compiled Query Program"));
            fileTypes.Add(new FileTypeData(".tcp", "Tally Compiled Program File"));
            fileTypes.Add(new FileTypeData(".vpm", "Vox Proxy Macro File"));
            fileTypes.Add(new FileTypeData(".acc", "GEM Accessory File"));
            fileTypes.Add(new FileTypeData(".caction", "Automator Converter Action"));
            fileTypes.Add(new FileTypeData(".cyw", "Rbot.CYW Worm File"));
            fileTypes.Add(new FileTypeData(".dek", "Eavesdropper Batch File"));
            fileTypes.Add(new FileTypeData(".dmc", "Medical Manager Script"));
            fileTypes.Add(new FileTypeData(".esh", "Extended Shell Batch File"));
            fileTypes.Add(new FileTypeData(".ezs", "EZ-R Stats Batch Script"));
            fileTypes.Add(new FileTypeData(".ham", "HAM Executable File"));
            fileTypes.Add(new FileTypeData(".hpf", "HP9100A Program File"));
            fileTypes.Add(new FileTypeData(".lo", "Interleaf Compiled Lisp File"));
            fileTypes.Add(new FileTypeData(".ore", "Ore Executable File"));
            fileTypes.Add(new FileTypeData(".prg", "GEM Application"));
            fileTypes.Add(new FileTypeData(".pvd", "Instalit Script"));
            fileTypes.Add(new FileTypeData(".s2a", "SEAL2 Application"));
            fileTypes.Add(new FileTypeData(".smm", "Ami Pro Macro"));
            fileTypes.Add(new FileTypeData(".udf", "Excel User Defined Function"));
            fileTypes.Add(new FileTypeData(".wpk", "WordPerfect Macro"));

            return fileTypes;
        }

        // http://fileinfo.com/filetypes/video
        public static List<FileTypeData> DefaultTypes()
        {
            List<FileTypeData> fileTypes = new List<FileTypeData>();

            fileTypes.Add(new FileTypeData(".cmd", "Windows Command File"));
            fileTypes.Add(new FileTypeData(".exe", "Windows Executable File"));
            fileTypes.Add(new FileTypeData(".hta", "HTML Application"));
            fileTypes.Add(new FileTypeData(".apk", "Android Package File"));
            fileTypes.Add(new FileTypeData(".ps1", "Windows PowerShell Cmdlet File"));
            fileTypes.Add(new FileTypeData(".jar", "Java Archive File"));
            fileTypes.Add(new FileTypeData(".com", "DOS Command File"));
            fileTypes.Add(new FileTypeData(".ipa", "iOS Application"));
            fileTypes.Add(new FileTypeData(".vb", "VBScript File"));
            fileTypes.Add(new FileTypeData(".js", "JScript Executable Script"));
            fileTypes.Add(new FileTypeData(".bin", "Generic Binary Executable File"));
            fileTypes.Add(new FileTypeData(".cgi", "Common Gateway Interface Script"));
            fileTypes.Add(new FileTypeData(".vbscript", "Visual Basic Script"));
            fileTypes.Add(new FileTypeData(".bin", "Unix Executable File"));
            fileTypes.Add(new FileTypeData(".exe", "PortableApps.com Application"));
            fileTypes.Add(new FileTypeData(".bat", "DOS Batch File"));

            return fileTypes;
        }
    }
}
