using DriveIndexer.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DriveIndexer.Database
{
    public class DefaulFileTypesAudio
    {
        // http://fileinfo.com/filetypes/audio
        public static List<FileTypeData> DefaultTypes()
        {
            List<FileTypeData> fileTypes = new List<FileTypeData>();

            fileTypes.Add(new FileTypeData(".omf", "Open Media Framework File"));
            fileTypes.Add(new FileTypeData(".vag", "PlayStation Compressed Sound File"));
            fileTypes.Add(new FileTypeData(".sng", "MIDI Song File"));
            fileTypes.Add(new FileTypeData(".act", "ADPCM Compressed Audio File"));
            fileTypes.Add(new FileTypeData(".vdj", "VirtualDJ Audio Sample File"));
            fileTypes.Add(new FileTypeData(".nra", "Nero Audio Compilation"));
            fileTypes.Add(new FileTypeData(".abm", "Music Album"));
            fileTypes.Add(new FileTypeData(".bnk", "Adlib Instrument Bank"));
            fileTypes.Add(new FileTypeData(".copy", "Sony Ericsson Protected Content File"));
            fileTypes.Add(new FileTypeData(".hsb", "HALion Sound Bank File"));
            fileTypes.Add(new FileTypeData(".mscz", "MuseScore Compressed Score File"));
            fileTypes.Add(new FileTypeData(".rfl", "Reason ReFill Sound Bank"));
            fileTypes.Add(new FileTypeData(".sma", "SmartMusic Accompaniment File"));
            fileTypes.Add(new FileTypeData(".vyf", "Samsung Digital Voice Recorder File"));
            fileTypes.Add(new FileTypeData(".ang", "Anghami Audio File"));
            fileTypes.Add(new FileTypeData(".acm", "Interplay Audio File"));
            fileTypes.Add(new FileTypeData(".at3", "ATRAC3 Audio File"));
            fileTypes.Add(new FileTypeData(".aob", "DVD-Audio Audio Object File"));
            fileTypes.Add(new FileTypeData(".syx", "MIDI System Exclusive Message"));
            fileTypes.Add(new FileTypeData(".aimppl", "AIMP Playlist File"));
            fileTypes.Add(new FileTypeData(".nvf", "Creative Labs NVF Audio File"));
            fileTypes.Add(new FileTypeData(".saf", "Secure Audio File"));
            fileTypes.Add(new FileTypeData(".xfs", "eRacer Sound File"));
            fileTypes.Add(new FileTypeData(".mod", "Amiga Music Module File"));
            fileTypes.Add(new FileTypeData(".sfk", "Sound Forge Audio Peak File"));
            fileTypes.Add(new FileTypeData(".als", "Ableton Live Set File"));
            fileTypes.Add(new FileTypeData(".gp5", "Guitar Pro 5 Tablature File"));
            fileTypes.Add(new FileTypeData(".caf", "Core Audio File"));
            fileTypes.Add(new FileTypeData(".mp3", "MP3 Audio File"));
            fileTypes.Add(new FileTypeData(".pla", "Sansa Playlist File"));
            fileTypes.Add(new FileTypeData(".wav", "WAVE Audio File"));
            fileTypes.Add(new FileTypeData(".sf2", "SoundFont 2 Sound Bank"));
            fileTypes.Add(new FileTypeData(".mid", "MIDI File"));
            fileTypes.Add(new FileTypeData(".wma", "Windows Media Audio File"));
            fileTypes.Add(new FileTypeData(".afc", "Mass Effect 2 Audio File"));
            fileTypes.Add(new FileTypeData(".amxd", "Ableton Max Patch File"));
            fileTypes.Add(new FileTypeData(".dmsa", "Music Disc Creator Project File"));
            fileTypes.Add(new FileTypeData(".dmse", "Sound Editor Project File"));
            fileTypes.Add(new FileTypeData(".emp", "eMusic Music Download File"));
            fileTypes.Add(new FileTypeData(".logicx", "Logic Pro Project"));
            fileTypes.Add(new FileTypeData(".m4r", "iPhone Ringtone File"));
            fileTypes.Add(new FileTypeData(".midi", "MIDI File"));
            fileTypes.Add(new FileTypeData(".ptx", "Pro Tools Session File"));
            fileTypes.Add(new FileTypeData(".rns", "Reason Song File"));
            fileTypes.Add(new FileTypeData(".rx2", "REX2 Audio File"));
            fileTypes.Add(new FileTypeData(".sib", "Sibelius Score"));
            fileTypes.Add(new FileTypeData(".slp", "SpectraLayers Pro Project"));
            fileTypes.Add(new FileTypeData(".trak", "Traktor Content Pack File"));
            fileTypes.Add(new FileTypeData(".5xb", "Line 6 POD HD500X Edit Bundle"));
            fileTypes.Add(new FileTypeData(".a2b", "Adlib Tracker II Instrument Bank"));
            fileTypes.Add(new FileTypeData(".a2i", "Adlib Tracker II Instrument File"));
            fileTypes.Add(new FileTypeData(".agr", "Ableton Groove File"));
            fileTypes.Add(new FileTypeData(".akp", "Akai Sampler File"));
            fileTypes.Add(new FileTypeData(".asd", "Ableton Live Sample Analysis File"));
            fileTypes.Add(new FileTypeData(".aup", "Audacity Project File"));
            fileTypes.Add(new FileTypeData(".bun", "Cakewalk Bundle File"));
            fileTypes.Add(new FileTypeData(".bww", "Bagpipe Player File"));
            fileTypes.Add(new FileTypeData(".csh", "Cubase Waveform File"));
            fileTypes.Add(new FileTypeData(".dfc", "Defractor Instrument"));
            fileTypes.Add(new FileTypeData(".drg", "I-Doser Audio Drug File"));
            fileTypes.Add(new FileTypeData(".dsm", "Digital Sound Module"));
            fileTypes.Add(new FileTypeData(".dtm", "DigiTrakker Module"));
            fileTypes.Add(new FileTypeData(".fev", "FMOD Audio Events File"));
            fileTypes.Add(new FileTypeData(".frg", "Sony Sound Forge Pro Project File"));
            fileTypes.Add(new FileTypeData(".g726", "G.726 Audio File"));
            fileTypes.Add(new FileTypeData(".ins", "Adlib Tracker Instrument File"));
            fileTypes.Add(new FileTypeData(".isma", "IIS Smooth Streaming Audio File"));
            fileTypes.Add(new FileTypeData(".krz", "Kurzweil K2000 File"));
            fileTypes.Add(new FileTypeData(".mbr", "Zune Smooth Streaming File"));
            fileTypes.Add(new FileTypeData(".mpga", "MPEG-1 Layer 3 Audio File"));
            fileTypes.Add(new FileTypeData(".mtp", "MadTracker 2 Pattern"));
            fileTypes.Add(new FileTypeData(".musx", "Finale Notation File"));
            fileTypes.Add(new FileTypeData(".nkc", "Kontakt Library Data File"));
            fileTypes.Add(new FileTypeData(".nkm", "Kontakt Multi Instrument File"));
            fileTypes.Add(new FileTypeData(".omg", "OpenMG Audio File"));
            fileTypes.Add(new FileTypeData(".pkf", "Audition Peak File"));
            fileTypes.Add(new FileTypeData(".rex", "ReCycle Loop File"));
            fileTypes.Add(new FileTypeData(".rip", "Hit'n'Mix Audio Mashup File"));
            fileTypes.Add(new FileTypeData(".rol", "Ad Lib Synthesized Instrument"));
            fileTypes.Add(new FileTypeData(".sbi", "Sound Blaster Instrument"));
            fileTypes.Add(new FileTypeData(".sfpack", "Packed SoundFont File"));
            fileTypes.Add(new FileTypeData(".smf", "Standard MIDI File"));
            fileTypes.Add(new FileTypeData(".smp", "SmartMusic Performance File"));
            fileTypes.Add(new FileTypeData(".sseq", "Nintendo DS Sound File"));
            fileTypes.Add(new FileTypeData(".svd", "Roland Patch File"));
            fileTypes.Add(new FileTypeData(".syh", "Synchomatic Instrument"));
            fileTypes.Add(new FileTypeData(".syw", "Yamaha SY99/SY85 Audio File"));
            fileTypes.Add(new FileTypeData(".tg", "TuxGuitar Document"));
            fileTypes.Add(new FileTypeData(".u", "AU Audio File"));
            fileTypes.Add(new FileTypeData(".uax", "Unreal Audio Package"));
            fileTypes.Add(new FileTypeData(".vmd", "Covox Raw Sample"));
            fileTypes.Add(new FileTypeData(".vpl", "Karaoke Player Playlist"));
            fileTypes.Add(new FileTypeData(".zvd", "ZyXEL Voice File"));
            fileTypes.Add(new FileTypeData("0", "669	UNIS Composer 669 Module"));
            fileTypes.Add(new FileTypeData(".eop", "EveryonePiano Music Score File"));
            fileTypes.Add(new FileTypeData(".zab", "Zipped Audio Book"));
            fileTypes.Add(new FileTypeData(".oga", "Ogg Vorbis Audio File"));
            fileTypes.Add(new FileTypeData(".xspf", "XSPF Playlist File"));
            fileTypes.Add(new FileTypeData(".sty", "Yamaha/Korg Keyboard Style"));
            fileTypes.Add(new FileTypeData(".dig", "Digilink Audio File"));
            fileTypes.Add(new FileTypeData(".ogg", "Ogg Vorbis Audio File"));
            fileTypes.Add(new FileTypeData(".aif", "Audio Interchange File Format"));
            fileTypes.Add(new FileTypeData(".m3u", "Media Playlist File"));
            fileTypes.Add(new FileTypeData(".flac", "Free Lossless Audio Codec File"));
            fileTypes.Add(new FileTypeData(".aiff", "Audio Interchange File Format"));
            fileTypes.Add(new FileTypeData(".ksd", "Native Instruments Massive Sound File"));
            fileTypes.Add(new FileTypeData(".mui", "Myriad Instrument File"));
            fileTypes.Add(new FileTypeData(".dss", "Digital Speech Standard File"));
            fileTypes.Add(new FileTypeData(".flp", "FL Studio Project File"));
            fileTypes.Add(new FileTypeData(".gpk", "WaveLab Audio Peak File"));
            fileTypes.Add(new FileTypeData(".mus", "Finale Notation File"));
            fileTypes.Add(new FileTypeData(".5xe", "Line 6 POD HD500X Edit Preset File"));
            fileTypes.Add(new FileTypeData(".logic", "Logic Pro Project File"));
            fileTypes.Add(new FileTypeData(".minigsf", "Game Boy Advance Song File"));
            fileTypes.Add(new FileTypeData(".sd", "ESPS Sampled Data File"));
            fileTypes.Add(new FileTypeData(".sdat", "Nintendo DS Sound Data File"));
            fileTypes.Add(new FileTypeData(".ins", "Ensoniq Instrument"));
            fileTypes.Add(new FileTypeData(".aac", "Advanced Audio Coding File"));
            fileTypes.Add(new FileTypeData(".nki", "KONTAKT Instrument File"));
            fileTypes.Add(new FileTypeData(".flp", "FruityLoops Project"));
            fileTypes.Add(new FileTypeData(".pcg", "Korg Instrument Bank File"));
            fileTypes.Add(new FileTypeData(".wave", "WAVE Sound File"));
            fileTypes.Add(new FileTypeData(".wpk", "Nero Wave Editor File"));
            fileTypes.Add(new FileTypeData(".3ga", "3GPP Audio File"));
            fileTypes.Add(new FileTypeData(".dcf", "DRM Content Format File"));
            fileTypes.Add(new FileTypeData(".aud", "Video Game Compressed Audio File"));
            fileTypes.Add(new FileTypeData(".cwt", "Cakewalk SONAR Template"));
            fileTypes.Add(new FileTypeData(".dls", "Downloadable Sounds File"));
            fileTypes.Add(new FileTypeData(".ds2", "Olympus DSS Pro Audio File"));
            fileTypes.Add(new FileTypeData(".flm", "FL Studio Mobile Song File"));
            fileTypes.Add(new FileTypeData(".gsm", "Global System for Mobile Audio File"));
            fileTypes.Add(new FileTypeData(".nsa", "Nullsoft Streaming Audio File"));
            fileTypes.Add(new FileTypeData(".ds", "LMMS DrumSynth File"));
            fileTypes.Add(new FileTypeData(".pcm", "Pulse Code Modulation"));
            fileTypes.Add(new FileTypeData(".pho", "MBROLA Phonetic Data File"));
            fileTypes.Add(new FileTypeData(".q1", "Winamp Equalizer Presets File"));
            fileTypes.Add(new FileTypeData(".sph", "NIST SPHERE Audio File"));
            fileTypes.Add(new FileTypeData(".xwb", "XACT Wave Bank"));
            fileTypes.Add(new FileTypeData(".dsp", "Dynamic Studio Professional Module"));
            fileTypes.Add(new FileTypeData(".sam", "MOD Edit Sample File"));
            fileTypes.Add(new FileTypeData(".u8", "3D Lemmings Audio File"));
            fileTypes.Add(new FileTypeData(".ym", "Atari ST Audio File"));
            fileTypes.Add(new FileTypeData(".amr", "Adaptive Multi-Rate Codec File"));
            fileTypes.Add(new FileTypeData(".vlc", "VLC Playlist"));
            fileTypes.Add(new FileTypeData(".wve", "WaveEditor Project File"));
            fileTypes.Add(new FileTypeData(".dff", "DSD Audio File"));
            fileTypes.Add(new FileTypeData(".iff", "Interchange File Format"));
            fileTypes.Add(new FileTypeData(".cda", "CD Audio Track Shortcut"));
            fileTypes.Add(new FileTypeData(".ram", "Real Audio Metadata File"));
            fileTypes.Add(new FileTypeData(".oma", "Sony OpenMG Music File"));
            fileTypes.Add(new FileTypeData(".sds", "MIDI Sample Dump Standard File"));
            fileTypes.Add(new FileTypeData(".nsf", "NES Sound Format File"));
            fileTypes.Add(new FileTypeData(".acd", "ACID Project File"));
            fileTypes.Add(new FileTypeData(".ac3", "Audio Codec 3 File"));
            fileTypes.Add(new FileTypeData(".dsf", "Delusion Digital Sound File"));
            fileTypes.Add(new FileTypeData(".cpr", "Cubase Project"));
            fileTypes.Add(new FileTypeData(".m3u8", "UTF-8 M3U Playlist File"));
            fileTypes.Add(new FileTypeData(".xa", "The Sims Audio File"));
            fileTypes.Add(new FileTypeData(".it", "Impulse Tracker Module"));
            fileTypes.Add(new FileTypeData(".m4a", "MPEG-4 Audio File"));
            fileTypes.Add(new FileTypeData(".ac", "-zip	Sony ACID Project With Embedded Media File"));
            fileTypes.Add(new FileTypeData(".4mp", "4-MP3 Database File"));
            fileTypes.Add(new FileTypeData(".apl", "Monkey's Audio Track Information File"));
            fileTypes.Add(new FileTypeData(".cwp", "Cakewalk SONAR Project"));
            fileTypes.Add(new FileTypeData(".cws", "ChordWizard Song"));
            fileTypes.Add(new FileTypeData(".gsflib", "Game Boy Advance Song Library"));
            fileTypes.Add(new FileTypeData(".med", "Amiga MED Sound File"));
            fileTypes.Add(new FileTypeData(".mo3", "MO3 Audio File"));
            fileTypes.Add(new FileTypeData(".mx5", "Mixcraft 5 Audio Project"));
            fileTypes.Add(new FileTypeData(".ply", "Finale Playback File"));
            fileTypes.Add(new FileTypeData(".qcp", "PureVoice Audio File"));
            fileTypes.Add(new FileTypeData(".r1m", "RealOne Streaming Media File"));
            fileTypes.Add(new FileTypeData(".rmj", "Real Media Jukebox Audio File"));
            fileTypes.Add(new FileTypeData(".stm", "Scream Tracker 2 Module"));
            fileTypes.Add(new FileTypeData(".w64", "Sony Wave64 Audio File"));
            fileTypes.Add(new FileTypeData(".ahx", "WinAHX Tracker Module"));
            fileTypes.Add(new FileTypeData(".au", "Audacity Audio File"));
            fileTypes.Add(new FileTypeData(".b4s", "Winamp Playlist File"));
            fileTypes.Add(new FileTypeData(".hbb", "Line 6 POD HD Edit Bundle"));
            fileTypes.Add(new FileTypeData(".hbs", "Line 6 POD HD Edit Setlist File"));
            fileTypes.Add(new FileTypeData(".igr", "Igor Engraver File"));
            fileTypes.Add(new FileTypeData(".ins", "Sample Cell II Instrument Definition File"));
            fileTypes.Add(new FileTypeData(".kit", "Battery Drum Kit File"));
            fileTypes.Add(new FileTypeData(".kmp", "Korg Trinity/Triton Keymap File"));
            fileTypes.Add(new FileTypeData(".ksc", "Korg Trinity/Triton Script File"));
            fileTypes.Add(new FileTypeData(".mdl", "DigiTrakker Module"));
            fileTypes.Add(new FileTypeData(".mu3", "Myriad Packed Musical Score"));
            fileTypes.Add(new FileTypeData(".q2", "Winamp Equalizer Auto-Load Presets File"));
            fileTypes.Add(new FileTypeData(".sbg", "SBaGen Binaural Beat File"));
            fileTypes.Add(new FileTypeData(".sfap0", "Sound Forge Audio Proxy File"));
            fileTypes.Add(new FileTypeData(".toc", "PSP Audio File"));
            fileTypes.Add(new FileTypeData(".vgz", "Video Game Music Compressed File"));
            fileTypes.Add(new FileTypeData(".vmf", "Covox Speech Thing Sample"));
            fileTypes.Add(new FileTypeData(".zpa", "Vielklang Audio Metadata File"));
            fileTypes.Add(new FileTypeData(".2sf", "Nintendo DS Sound File"));
            fileTypes.Add(new FileTypeData(".gpx", "Guitar Pro 6 Document"));
            fileTypes.Add(new FileTypeData(".ape", "Monkey's Audio Lossless Audio File"));
            fileTypes.Add(new FileTypeData(".fls", "Flash Lite Sound Bundle"));
            fileTypes.Add(new FileTypeData(".mus", "Doom Music File"));
            fileTypes.Add(new FileTypeData(".emx", "eMusic Download File"));
            fileTypes.Add(new FileTypeData(".ftm", "FamiTracker Module"));
            fileTypes.Add(new FileTypeData(".nbs", "Minecraft Note Block Studio File"));
            fileTypes.Add(new FileTypeData(".pcast", "iTunes Podcast File"));
            fileTypes.Add(new FileTypeData(".sesx", "Adobe Audition Session File"));
            fileTypes.Add(new FileTypeData(".dtshd", "DTS-HD Master Audio File"));
            fileTypes.Add(new FileTypeData(".mmm", "Music Maker Arrangement File"));
            fileTypes.Add(new FileTypeData(".peak", "Steinberg Peak File"));
            fileTypes.Add(new FileTypeData(".vox", "Dialogic Voice Audio File"));
            fileTypes.Add(new FileTypeData(".bmml", "Braille Music Markup Language File"));
            fileTypes.Add(new FileTypeData(".mscx", "MuseScore Music Score File"));
            fileTypes.Add(new FileTypeData(".xmf", "Extensible Music File"));
            fileTypes.Add(new FileTypeData(".rtm", "Real Tracker Module"));
            fileTypes.Add(new FileTypeData(".pls", "Audio Playlist"));
            fileTypes.Add(new FileTypeData(".mus", "Minecraft Music File"));
            fileTypes.Add(new FileTypeData(".xm", "Fasttracker 2 Extended Module"));
            fileTypes.Add(new FileTypeData(".avastsounds", "Avast! Soundpack File"));
            fileTypes.Add(new FileTypeData(".snd", "Sound File"));
            fileTypes.Add(new FileTypeData(".wax", "Windows Media Audio Redirect"));
            fileTypes.Add(new FileTypeData(".wpp", "WavePad Project File"));
            fileTypes.Add(new FileTypeData(".ra", "Real Audio File"));
            fileTypes.Add(new FileTypeData(".seq", "PowerTracks Pro Audio Project File"));
            fileTypes.Add(new FileTypeData(".aa", "Audible Audio Book File"));
            fileTypes.Add(new FileTypeData(".m4b", "MPEG-4 Audio Book File"));
            fileTypes.Add(new FileTypeData(".odm", "OverDrive Media File"));
            fileTypes.Add(new FileTypeData(".sfl", "Sound Forge Sound Data File"));
            fileTypes.Add(new FileTypeData(".mpa", "MPEG-2 Audio File"));
            fileTypes.Add(new FileTypeData(".amz", "Amazon MP3 Downloader File"));
            fileTypes.Add(new FileTypeData(".5xs", "Line 6 POD HD500X Edit Setlist File"));
            fileTypes.Add(new FileTypeData(".a2m", "Adlib Tracker II File"));
            fileTypes.Add(new FileTypeData(".abc", "ABC Music Notation"));
            fileTypes.Add(new FileTypeData(".ac", "-bak	Sony ACID Project Backup File"));
            fileTypes.Add(new FileTypeData(".adts", "Audio Data Transport Stream File"));
            fileTypes.Add(new FileTypeData(".agm", "DTS Multi-channel Pro Packer File"));
            fileTypes.Add(new FileTypeData(".aifc", "Compressed Audio Interchange File"));
            fileTypes.Add(new FileTypeData(".alc", "Ableton Live Clip File"));
            fileTypes.Add(new FileTypeData(".amf", "Advanced Module File"));
            fileTypes.Add(new FileTypeData(".au", "Audio File"));
            fileTypes.Add(new FileTypeData(".band", "GarageBand Project File"));
            fileTypes.Add(new FileTypeData(".bap", "Blaze Audio Wave Information File"));
            fileTypes.Add(new FileTypeData(".bdd", "CARA Sound Radiation Data File"));
            fileTypes.Add(new FileTypeData(".bidule", "Bidule Layout File"));
            fileTypes.Add(new FileTypeData(".bwf", "Broadcast Wave File"));
            fileTypes.Add(new FileTypeData(".caff", "Core Audio File"));
            fileTypes.Add(new FileTypeData(".cdda", "CD Digital Audio File"));
            fileTypes.Add(new FileTypeData(".cdlx", "Audition CD Layout File"));
            fileTypes.Add(new FileTypeData(".cdo", "Crescendo Music Notation File"));
            fileTypes.Add(new FileTypeData(".cdr", "Raw Audio CD Data"));
            fileTypes.Add(new FileTypeData(".cel", "Audition Loop"));
            fileTypes.Add(new FileTypeData(".cgrp", "Pro Tools Clip Group File"));
            fileTypes.Add(new FileTypeData(".cidb", "iTunes CD Information File"));
            fileTypes.Add(new FileTypeData(".ckb", "Cricket Audio Bank File"));
            fileTypes.Add(new FileTypeData(".conform", "Conformalizer Change List File"));
            fileTypes.Add(new FileTypeData(".cpt", "DTS Compact Audio File"));
            fileTypes.Add(new FileTypeData(".cts", "CrazyTalk Script File"));
            fileTypes.Add(new FileTypeData(".cwb", "Cakewalk Bundle"));
            fileTypes.Add(new FileTypeData(".dct", "Dictation Audio File"));
            fileTypes.Add(new FileTypeData(".dewf", "SoundEdit Recorded Instrument"));
            fileTypes.Add(new FileTypeData(".df2", "Defractor 2 Instrument"));
            fileTypes.Add(new FileTypeData(".dig", "Sound Designer Audio File"));
            fileTypes.Add(new FileTypeData(".dm", "DRM Delivery Message"));
            fileTypes.Add(new FileTypeData(".dmf", "Delusion Digital Music File"));
            fileTypes.Add(new FileTypeData(".dra", "Nuance Dragon Voice Recording File"));
            fileTypes.Add(new FileTypeData(".dwd", "DiamondWare Digital Audio File"));
            fileTypes.Add(new FileTypeData(".efk", "Ensoniq KT File"));
            fileTypes.Add(new FileTypeData(".efq", "Ensoniq SQ1/SQ2/KS-32 File"));
            fileTypes.Add(new FileTypeData(".efs", "Ensoniq SQ-80 File"));
            fileTypes.Add(new FileTypeData(".efv", "Ensoniq VFX-SD File"));
            fileTypes.Add(new FileTypeData(".emd", "ABT Extended Module"));
            fileTypes.Add(new FileTypeData(".esps", "ESPS Sampled Data File"));
            fileTypes.Add(new FileTypeData(".f2r", "Farandoyle Linear Module File"));
            fileTypes.Add(new FileTypeData(".f32", "Raw 32-Bit Audio File"));
            fileTypes.Add(new FileTypeData(".f3r", "Farandoyle Blocked Module File"));
            fileTypes.Add(new FileTypeData(".f4a", "Adobe Flash Protected Audio File"));
            fileTypes.Add(new FileTypeData(".f64", "Raw 64-Bit Audio File"));
            fileTypes.Add(new FileTypeData(".fdp", "FMOD Project File"));
            fileTypes.Add(new FileTypeData(".fsb", "FMOD Sample Bank File"));
            fileTypes.Add(new FileTypeData(".fsc", "FL Studio Score File"));
            fileTypes.Add(new FileTypeData(".fsm", "Farandole Composer WaveSample File"));
            fileTypes.Add(new FileTypeData(".ftm", "Finale Template File"));
            fileTypes.Add(new FileTypeData(".ftmx", "Finale Template File"));
            fileTypes.Add(new FileTypeData(".fzf", "Casio FZ-1 Full Dump"));
            fileTypes.Add(new FileTypeData(".fzv", "Casio FZ-1 Voice Dump"));
            fileTypes.Add(new FileTypeData(".g721", "G.721 Audio File"));
            fileTypes.Add(new FileTypeData(".gig", "Tascam GigaSampler File"));
            fileTypes.Add(new FileTypeData(".gpbank", "Guitar Pro Sound Bank File"));
            fileTypes.Add(new FileTypeData(".groove", "ACID Groove File"));
            fileTypes.Add(new FileTypeData(".gsf", "Game Boy Advance Sound File"));
            fileTypes.Add(new FileTypeData(".h4b", "Line 6 POD HD400 Edit Bundle"));
            fileTypes.Add(new FileTypeData(".h5b", "Line 6 POD HD500 Edit Bundle"));
            fileTypes.Add(new FileTypeData(".h5s", "Line 6 POD HD500 Edit Setlist File"));
            fileTypes.Add(new FileTypeData(".hbe", "Line 6 POD HD Edit Preset File"));
            fileTypes.Add(new FileTypeData(".igp", "Igor Published Music Notation File"));
            fileTypes.Add(new FileTypeData(".iti", "Impulse Tracker Instrument"));
            fileTypes.Add(new FileTypeData(".koz", "Bell Music File"));
            fileTypes.Add(new FileTypeData(".koz", "Audiokoz Music File"));
            fileTypes.Add(new FileTypeData(".ksf", "Korg Trinity/Triton Sample File"));
            fileTypes.Add(new FileTypeData(".kt3", "Battery 3 Drum Kit File"));
            fileTypes.Add(new FileTypeData(".la", "Lossless Audio File"));
            fileTypes.Add(new FileTypeData(".lso", "Logic Audio Project"));
            fileTypes.Add(new FileTypeData(".lwv", "Linguistically Enhanced Sound File"));
            fileTypes.Add(new FileTypeData(".m4p", "iTunes Music Store Audio File"));
            fileTypes.Add(new FileTypeData(".ma1", "Monarch Audio File"));
            fileTypes.Add(new FileTypeData(".mdc", "MidiCo Karaoke Audio File"));
            fileTypes.Add(new FileTypeData(".mgv", "Yamaha MegaVoice File"));
            fileTypes.Add(new FileTypeData(".miniusf", "Nintendo 64 Song File"));
            fileTypes.Add(new FileTypeData(".mka", "Matroska Audio File"));
            fileTypes.Add(new FileTypeData(".mmlp", "Music Macro Language Project"));
            fileTypes.Add(new FileTypeData(".mmp", "MixMeister Playlist"));
            fileTypes.Add(new FileTypeData(".mmpz", "LMMS Project File"));
            fileTypes.Add(new FileTypeData(".mpc", "Musepack Compressed Audio File"));
            fileTypes.Add(new FileTypeData(".mte", "MadTracker 2 Envelope"));
            fileTypes.Add(new FileTypeData(".mti", "MadTracker Instrument"));
            fileTypes.Add(new FileTypeData(".mtm", "MultiTracker Module"));
            fileTypes.Add(new FileTypeData(".mux", "Trackmania Music File"));
            fileTypes.Add(new FileTypeData(".narrative", "Narrator Document"));
            fileTypes.Add(new FileTypeData(".nkb", "Kontakt Audio Bank"));
            fileTypes.Add(new FileTypeData(".nks", "Kontakt Monolith Container"));
            fileTypes.Add(new FileTypeData(".nkx", "Kontakt Monolith Container File"));
            fileTypes.Add(new FileTypeData(".nml", "Traktor Collection File"));
            fileTypes.Add(new FileTypeData(".note", "Notessimo Composition"));
            fileTypes.Add(new FileTypeData(".nrt", "Nokia Ringtone"));
            fileTypes.Add(new FileTypeData(".nst", "NoiseTracker Module"));
            fileTypes.Add(new FileTypeData(".ntn", "NOTION Song File"));
            fileTypes.Add(new FileTypeData(".nwc", "NoteWorthy Composer File"));
            fileTypes.Add(new FileTypeData(".obw", "Superior Drummer Sounds File"));
            fileTypes.Add(new FileTypeData(".okt", "Oktalyzer Module"));
            fileTypes.Add(new FileTypeData(".omx", "OtsAV Media Library Information File"));
            fileTypes.Add(new FileTypeData(".ots", "OtsAV Album File"));
            fileTypes.Add(new FileTypeData(".ovw", "Logic Pro Overview File"));
            fileTypes.Add(new FileTypeData(".pandora", "Pandora Android App Executable"));
            fileTypes.Add(new FileTypeData(".pca", "Perfect Clarity Audio File"));
            fileTypes.Add(new FileTypeData(".pek", "Adobe Peak Waveform File"));
            fileTypes.Add(new FileTypeData(".pna", "PhatNoise Audio File"));
            fileTypes.Add(new FileTypeData(".psm", "Protracker Studio Module"));
            fileTypes.Add(new FileTypeData(".ptm", "PolyTracker Module"));
            fileTypes.Add(new FileTypeData(".pts", "Pro Tools Session"));
            fileTypes.Add(new FileTypeData(".rax", "Real Music Store Audio File"));
            fileTypes.Add(new FileTypeData(".rgrp", "Pro Tools Region Group File"));
            fileTypes.Add(new FileTypeData(".rmi", "RMID MIDI File"));
            fileTypes.Add(new FileTypeData(".rmx", "RealJukebox Format"));
            fileTypes.Add(new FileTypeData(".rng", "Nokia Composer Ringtone"));
            fileTypes.Add(new FileTypeData(".rsn", "Reason Project File"));
            fileTypes.Add(new FileTypeData(".rso", "NXT Brick Audio File"));
            fileTypes.Add(new FileTypeData(".rti", "Real Tracker Instrument"));
            fileTypes.Add(new FileTypeData(".s3i", "Scream Tracker 3 Instrument"));
            fileTypes.Add(new FileTypeData(".sc2", "Sample Cell II Instrument Definition"));
            fileTypes.Add(new FileTypeData(".scs11", "Show Cue System Cue File"));
            fileTypes.Add(new FileTypeData(".sd2", "Sound Designer II File"));
            fileTypes.Add(new FileTypeData(".sfz", "SFZ Sample Definition File"));
            fileTypes.Add(new FileTypeData(".sgp", "MP3 Audio Mixer Sound Group Project"));
            fileTypes.Add(new FileTypeData(".smpx", "SmartMusic Accompaniment File"));
            fileTypes.Add(new FileTypeData(".sou", "SBStudio II Sound File"));
            fileTypes.Add(new FileTypeData(".sppack", "SPPack Sound Sample"));
            fileTypes.Add(new FileTypeData(".sprg", "Synclavier Program File"));
            fileTypes.Add(new FileTypeData(".stap", "Soundtrack Pro Audio Project File"));
            fileTypes.Add(new FileTypeData(".sty", "Band-in-a-Box Styles File"));
            fileTypes.Add(new FileTypeData(".sxt", "Propellerhead Reason NN-XT Patch File"));
            fileTypes.Add(new FileTypeData(".syn", "SimSynth Document"));
            fileTypes.Add(new FileTypeData(".td0", "Akai Teledisk Sound Library"));
            fileTypes.Add(new FileTypeData(".tta", "True Audio File"));
            fileTypes.Add(new FileTypeData(".txw", "Yamaha TX16W Audio File"));
            fileTypes.Add(new FileTypeData(".ult", "UltraTracker Module"));
            fileTypes.Add(new FileTypeData(".uni", "MikMod UniMOD Module"));
            fileTypes.Add(new FileTypeData(".usf", "Nintendo 64 Music File"));
            fileTypes.Add(new FileTypeData(".usflib", "Nintendo 64 Song Library"));
            fileTypes.Add(new FileTypeData(".ust", "UTAU Sequence Text File"));
            fileTypes.Add(new FileTypeData(".uw", "Unsigned Word Audio File"));
            fileTypes.Add(new FileTypeData(".uwf", "UltraTracker Wave File"));
            fileTypes.Add(new FileTypeData(".vap", "Dialogic Indexed Voice Audio File"));
            fileTypes.Add(new FileTypeData(".vc3", "VSampler Soundbank File"));
            fileTypes.Add(new FileTypeData(".vmo", "Siemens Voice Memo File"));
            fileTypes.Add(new FileTypeData(".voc", "Creative Labs Audio File"));
            fileTypes.Add(new FileTypeData(".voxal", "Voxal Project File"));
            fileTypes.Add(new FileTypeData(".vpm", "Garmin Voice File"));
            fileTypes.Add(new FileTypeData(".vpw", "VoxPro Wave File"));
            fileTypes.Add(new FileTypeData(".vrf", "Ventrilo Audio Recording"));
            fileTypes.Add(new FileTypeData(".vsq", "VOCALOID2 Project File"));
            fileTypes.Add(new FileTypeData(".wfb", "WaveFront Sound Bank"));
            fileTypes.Add(new FileTypeData(".wfm", "Pro Tools Wave Cache File"));
            fileTypes.Add(new FileTypeData(".wfp", "WaveFront Program File"));
            fileTypes.Add(new FileTypeData(".wow", "Grave Composer Music Module"));
            fileTypes.Add(new FileTypeData(".wproj", "Wwise Project File"));
            fileTypes.Add(new FileTypeData(".wrk", "Cakewalk Music Project"));
            fileTypes.Add(new FileTypeData(".wus", "WUTG Tagged Audio File"));
            fileTypes.Add(new FileTypeData(".wut", "WUTG Tag File"));
            fileTypes.Add(new FileTypeData(".wv", "WavPack Audio File"));
            fileTypes.Add(new FileTypeData(".wvc", "WavPack Correction File"));
            fileTypes.Add(new FileTypeData(".wwu", "Wwise Work Unit"));
            fileTypes.Add(new FileTypeData(".xmu", "Expressive Music Container File"));
            fileTypes.Add(new FileTypeData(".xrns", "Renoise Song File"));
            fileTypes.Add(new FileTypeData(".yookoo", "Yookoo Player Playlist File"));
            fileTypes.Add(new FileTypeData(".adv", "Ableton Device Preset File"));
            fileTypes.Add(new FileTypeData(".cmf", "Creative Music Format"));
            fileTypes.Add(new FileTypeData(".dmc", "DPCM Sample File"));
            fileTypes.Add(new FileTypeData(".gmc", "Game Music Creator Sound File"));
            fileTypes.Add(new FileTypeData(".mp_", "Mobile Phone Sound File"));
            fileTypes.Add(new FileTypeData(".ppcx", "Adobe Presenter Presentation Audio File"));
            fileTypes.Add(new FileTypeData(".sbk", "E-MU SoundFont Sound Bank"));
            fileTypes.Add(new FileTypeData(".sid", "SID Audio File"));
            fileTypes.Add(new FileTypeData(".sng", "Korg Trinity Song File"));
            fileTypes.Add(new FileTypeData(".sns", "SNS Video Game Audio File"));
            fileTypes.Add(new FileTypeData(".vgm", "Video Game Music File"));
            fileTypes.Add(new FileTypeData(".2sflib", "Nintendo DS Audio Library File"));
            fileTypes.Add(new FileTypeData(".6cm", "Six Channel Module"));
            fileTypes.Add(new FileTypeData(".8med", "Amiga OctaMed Music File"));
            fileTypes.Add(new FileTypeData(".a52", "Dolby Digital Audio File"));
            fileTypes.Add(new FileTypeData(".al", "A-Law Compressed Sound Format"));
            fileTypes.Add(new FileTypeData(".d01", "OPL2 FM Audio File"));
            fileTypes.Add(new FileTypeData(".gsm", "US Robotics GSM Audio File"));
            fileTypes.Add(new FileTypeData(".mini2sf", "Nintendo DS Sound Information File"));
            fileTypes.Add(new FileTypeData(".pd", "Spore Audio Playback File"));
            fileTypes.Add(new FileTypeData(".prg", "Akai MPC2000 Program File"));
            fileTypes.Add(new FileTypeData(".rmf", "Rich Music Format Audio File"));
            fileTypes.Add(new FileTypeData(".tun", "LEGO Racers Audio File"));
            fileTypes.Add(new FileTypeData(".wyz", "WYZTracker File"));
            fileTypes.Add(new FileTypeData(".xt", "Fastracker 2 Track"));
            fileTypes.Add(new FileTypeData(".kar", "Karaoke MIDI File"));
            fileTypes.Add(new FileTypeData(".vb", "Grand Theft Auto Audio File"));
            fileTypes.Add(new FileTypeData(".wem", "Wwise Encoded Media File"));
            fileTypes.Add(new FileTypeData(".adg", "Ableton Device Group"));
            fileTypes.Add(new FileTypeData(".dts", "DTS Encoded Audio File"));
            fileTypes.Add(new FileTypeData(".kfn", "KaraFun Karaoke File"));
            fileTypes.Add(new FileTypeData(".wav", "DTS-WAV File"));
            fileTypes.Add(new FileTypeData(".mtf", "Multi Tracker File"));
            fileTypes.Add(new FileTypeData(".ncw", "Native Compressed Wave File"));
            fileTypes.Add(new FileTypeData(".pk", "Audition Peak File"));
            fileTypes.Add(new FileTypeData(".dw", "David Whittaker Audio File"));
            fileTypes.Add(new FileTypeData(".vce", "Yamaha Voice File"));
            fileTypes.Add(new FileTypeData(".ddt", "Jill of the Jungle Music File"));
            fileTypes.Add(new FileTypeData(".k25", "Kurzweil K2500 File"));
            fileTypes.Add(new FileTypeData(".sf", "IRCAM Sound File"));
            fileTypes.Add(new FileTypeData(".dvf", "Sony Digital Voice File"));
            fileTypes.Add(new FileTypeData(".aa3", "ATRAC Audio File"));
            fileTypes.Add(new FileTypeData(".mxl", "Compressed MusicXML File"));
            fileTypes.Add(new FileTypeData(".adt", "ADTS Audio File"));
            fileTypes.Add(new FileTypeData(".fpa", "Finale Performance Assessment File"));
            fileTypes.Add(new FileTypeData(".h5e", "Line 6 POD HD500 Edit Preset File"));
            fileTypes.Add(new FileTypeData(".mpdp", "MixPad Project File"));
            fileTypes.Add(new FileTypeData(".ove", "Overture Musical Score"));
            fileTypes.Add(new FileTypeData(".rbs", "Rebirth Song File"));
            fileTypes.Add(new FileTypeData(".sd", "Sound Designer Audio File"));
            fileTypes.Add(new FileTypeData(".slx", "SpectraLayers Pro Project"));
            fileTypes.Add(new FileTypeData(".stx", "Scream Tracker Music Interface Kit File"));
            fileTypes.Add(new FileTypeData(".swa", "Shockwave Audio"));
            fileTypes.Add(new FileTypeData(".vsqx", "VOCALOID3 Project File"));
            fileTypes.Add(new FileTypeData(".w01", "Yamaha SY Series Wave File"));
            fileTypes.Add(new FileTypeData(".zpl", "Zune Playlist"));
            fileTypes.Add(new FileTypeData(".mmp", "LMMS Project File"));
            fileTypes.Add(new FileTypeData(".opus", "Opus Audio File"));
            fileTypes.Add(new FileTypeData(".ppc", "Adobe Presenter Audio File"));
            fileTypes.Add(new FileTypeData(".rsf", "LEGO MINDSTORMS EV3 Robot Sound File"));
            fileTypes.Add(new FileTypeData(".sdt", "Electronic Arts Sound Data File"));
            fileTypes.Add(new FileTypeData(".xa", "PlayStation Audio File"));
            fileTypes.Add(new FileTypeData(".xpf", "LMMS Preset File"));
            fileTypes.Add(new FileTypeData(".xsb", "XACT Sound Bank"));
            fileTypes.Add(new FileTypeData(".brstm", "BRSTM Audio Stream File"));
            fileTypes.Add(new FileTypeData(".tak", "Tom's Lossless Audio Kompressor File"));
            fileTypes.Add(new FileTypeData(".ptf", "Pro Tools 7 Session File"));
            fileTypes.Add(new FileTypeData(".efa", "Ensoniq ASR File"));
            fileTypes.Add(new FileTypeData(".g723", "G.723 Audio File"));
            fileTypes.Add(new FileTypeData(".mmf", "Synthetic Music Mobile Application File"));
            fileTypes.Add(new FileTypeData(".s3m", "ScreamTracker 3 Module"));
            fileTypes.Add(new FileTypeData(".sap", "Atari SAP Music File"));
            fileTypes.Add(new FileTypeData(".vqf", "TwinVQ Audio File"));
            fileTypes.Add(new FileTypeData(".ear", "Eyemail Audio Recording"));
            fileTypes.Add(new FileTypeData(".mp1", "MPEG-1 Layer 1 Audio File"));
            fileTypes.Add(new FileTypeData(".dcm", "DCM Audio Module"));
            fileTypes.Add(new FileTypeData(".ay", "AY Chiptune File"));
            fileTypes.Add(new FileTypeData(".zvr", "SAFA Media Audio File"));
            fileTypes.Add(new FileTypeData(".pat", "Gravis UltraSound GF1 Patch File"));
            fileTypes.Add(new FileTypeData(".ams", "Velvet Studio Module"));
            fileTypes.Add(new FileTypeData(".gbs", "GameBoy Sound File"));
            fileTypes.Add(new FileTypeData(".ics", "IC Recorder Sound File"));
            fileTypes.Add(new FileTypeData(".k26", "Kurzweil K2600 File"));
            fileTypes.Add(new FileTypeData(".mp2", "MPEG Layer II Compressed Audio File"));
            fileTypes.Add(new FileTypeData(".mts", "MadTracker 2 Sample File"));
            fileTypes.Add(new FileTypeData(".myr", "Myriad Music File"));
            fileTypes.Add(new FileTypeData(".psf", "Portable Sound File"));
            fileTypes.Add(new FileTypeData(".ses", "Audition Session File"));
            fileTypes.Add(new FileTypeData(".shn", "Shorten Compressed Audio File"));
            fileTypes.Add(new FileTypeData(".snd", "Macintosh Sound Resource"));
            fileTypes.Add(new FileTypeData(".wfd", "WaveFront Drum Kit File"));
            fileTypes.Add(new FileTypeData(".a2p", "Adlib Tracker II Pattern File"));
            fileTypes.Add(new FileTypeData(".a2t", "Adlib Tracker II Tiny Module File"));
            fileTypes.Add(new FileTypeData(".a2w", "Adlib Tracker II Instrument Bank with Macros"));
            fileTypes.Add(new FileTypeData(".ab", "Ambling BookPlayer MP3 File"));
            fileTypes.Add(new FileTypeData(".acp", "aacPlus Audio File"));
            fileTypes.Add(new FileTypeData(".ais", "Velvet Studio Instrument"));
            fileTypes.Add(new FileTypeData(".alaw", "A-Law Compressed Sound Format"));
            fileTypes.Add(new FileTypeData(".all", "Cubasis Project File"));
            fileTypes.Add(new FileTypeData(".apf", "Sony Ericsson Firmware Acoustics File"));
            fileTypes.Add(new FileTypeData(".aria", "Chipsounds Sound File"));
            fileTypes.Add(new FileTypeData(".ariax", "Chipsounds XML Sound File"));
            fileTypes.Add(new FileTypeData(".axa", "Annodex Audio File"));
            fileTypes.Add(new FileTypeData(".bwg", "BrainWave Generator Audio File"));
            fileTypes.Add(new FileTypeData(".c01", "Typhoon Wave Audio File"));
            fileTypes.Add(new FileTypeData(".ckf", "Casio Keyboard File"));
            fileTypes.Add(new FileTypeData(".djr", "Ringtone Media Studio DJ Ringtone Project"));
            fileTypes.Add(new FileTypeData(".efe", "Ensoniq EPS File"));
            fileTypes.Add(new FileTypeData(".emy", "eMelody Ringtone File"));
            fileTypes.Add(new FileTypeData(".erb", "Braille Music Reader File"));
            fileTypes.Add(new FileTypeData(".far", "Farandole Composer Module"));
            fileTypes.Add(new FileTypeData(".fti", "FamiTracker Instrument File"));
            fileTypes.Add(new FileTypeData(".gbproj", "GarageBand Project"));
            fileTypes.Add(new FileTypeData(".gym", "Sega Genesis Sound File"));
            fileTypes.Add(new FileTypeData(".h0", "Movie Edit Pro Waveform Information File"));
            fileTypes.Add(new FileTypeData(".h3b", "Line 6 POD HD300 Edit Bundle"));
            fileTypes.Add(new FileTypeData(".h3e", "Line 6 POD HD300 Edit Preset File"));
            fileTypes.Add(new FileTypeData(".h4e", "Line 6 POD HD400 Edit Preset File"));
            fileTypes.Add(new FileTypeData(".hdp", "MAGIX Hard Disk Project Audio File"));
            fileTypes.Add(new FileTypeData(".hps", "GameCube Audio File"));
            fileTypes.Add(new FileTypeData(".iaa", "INTUS Audio Archive"));
            fileTypes.Add(new FileTypeData(".imp", "Audition Impulse File"));
            fileTypes.Add(new FileTypeData(".itls", "iTunes Live Stream URL"));
            fileTypes.Add(new FileTypeData(".its", "Impulse Tracker Sample"));
            fileTypes.Add(new FileTypeData(".jam", "Line 6 Device Recording"));
            fileTypes.Add(new FileTypeData(".jam", "JAM Musical Score"));
            fileTypes.Add(new FileTypeData(".kpl", "Kazaa Playlist File"));
            fileTypes.Add(new FileTypeData(".kt2", "Battery 2 Drum Kit File"));
            fileTypes.Add(new FileTypeData(".l", "Left Audio Channel File"));
            fileTypes.Add(new FileTypeData(".lof", "Audacity File List"));
            fileTypes.Add(new FileTypeData(".lqt", "Liquid Audio File"));
            fileTypes.Add(new FileTypeData(".m", "PC-98 Game Music File"));
            fileTypes.Add(new FileTypeData(".m1a", "MPEG-1 Audio File"));
            fileTypes.Add(new FileTypeData(".m2", "PC-98 Game Music File"));
            fileTypes.Add(new FileTypeData(".minipsf", "Miniature PlayStation Sound Format File"));
            fileTypes.Add(new FileTypeData(".minipsf2", "Miniature PlayStation Sound Format File"));
            fileTypes.Add(new FileTypeData(".mogg", "Multitrack Ogg File"));
            fileTypes.Add(new FileTypeData(".mpu", "MPEG Layer 3 Audio File"));
            fileTypes.Add(new FileTypeData(".mt2", "MadTracker 2 Module"));
            fileTypes.Add(new FileTypeData(".mux", "Myriad Stand-Alone Music Score"));
            fileTypes.Add(new FileTypeData(".mx3", "Mixcraft 3 Audio Project"));
            fileTypes.Add(new FileTypeData(".mx4", "Mixcraft 4 Audio Project"));
            fileTypes.Add(new FileTypeData(".mx5template", "Mixcraft 5 Audio Project Template"));
            fileTypes.Add(new FileTypeData(".npl", "Cubase Library File"));
            fileTypes.Add(new FileTypeData(".ofr", "OptimFROG Audio File"));
            fileTypes.Add(new FileTypeData(".ovw", "Cubase WAVE Overview File"));
            fileTypes.Add(new FileTypeData(".pbf", "Pinnacle Sample Bank"));
            fileTypes.Add(new FileTypeData(".phy", "PhyMod Physical Modeling Data"));
            fileTypes.Add(new FileTypeData(".pjunoxl", "Preset File"));
            fileTypes.Add(new FileTypeData(".plst", "SmartMusic Playlist"));
            fileTypes.Add(new FileTypeData(".pno", "Windows 8 Piano Song"));
            fileTypes.Add(new FileTypeData(".prg", "WAVmaker Patch File"));
            fileTypes.Add(new FileTypeData(".psf1", "PlayStation Sound Format File"));
            fileTypes.Add(new FileTypeData(".psf2", "PlayStation Sound Format File"));
            fileTypes.Add(new FileTypeData(".psy", "Psycle Song File"));
            fileTypes.Add(new FileTypeData(".ptcop", "PxTone Audio File"));
            fileTypes.Add(new FileTypeData(".pvc", "Panasonic VM1 Voice File"));
            fileTypes.Add(new FileTypeData(".rad", "Reality Adlib Tracker Module"));
            fileTypes.Add(new FileTypeData(".raw", "Raw Audio Data"));
            fileTypes.Add(new FileTypeData(".rbs", "MP3 Ringtone File"));
            fileTypes.Add(new FileTypeData(".rcy", "ReCycle 1.x Document"));
            fileTypes.Add(new FileTypeData(".rmm", "RAM Meta File"));
            fileTypes.Add(new FileTypeData(".rta", "TrueRTA Project File"));
            fileTypes.Add(new FileTypeData(".rts", "Real Tracker Sample"));
            fileTypes.Add(new FileTypeData(".rvx", "Real Protected Video File"));
            fileTypes.Add(new FileTypeData(".s3z", "Compressed Scream Tracker 3 Module"));
            fileTypes.Add(new FileTypeData(".sd2f", "Sound Designer 2 File"));
            fileTypes.Add(new FileTypeData(".smp", "SampleVision Audio Sample Format"));
            fileTypes.Add(new FileTypeData(".spx", "Ogg Vorbis Speex File"));
            fileTypes.Add(new FileTypeData(".sseq", "Synclavier Sequence File"));
            fileTypes.Add(new FileTypeData(".ssnd", "Synclavier Sound File"));
            fileTypes.Add(new FileTypeData(".svq", "Roland Sequencer File"));
            fileTypes.Add(new FileTypeData(".svx", "8SVX Sound File"));
            fileTypes.Add(new FileTypeData(".thx", "Amiga THX Tracker Music File"));
            fileTypes.Add(new FileTypeData(".tsp", "TrueSpeech Audio File"));
            fileTypes.Add(new FileTypeData(".ub", "Unsigned Byte Audio File"));
            fileTypes.Add(new FileTypeData(".ulaw", "Raw u-Law Audio File"));
            fileTypes.Add(new FileTypeData(".v2m", "V2 Synthesizer Audio File"));
            fileTypes.Add(new FileTypeData(".vmf", "Vocaltec Media File"));
            fileTypes.Add(new FileTypeData(".vtx", "VTX Chiptune File"));
            fileTypes.Add(new FileTypeData(".wtpl", "WireTap Studio Library"));
            fileTypes.Add(new FileTypeData(".wtpt", "WireTap Studio Packaged Track"));
            fileTypes.Add(new FileTypeData(".xbmml", "Braille Music Markup Language File"));
            fileTypes.Add(new FileTypeData(".xmi", "Extended MIDI File"));
            fileTypes.Add(new FileTypeData(".xmz", "FastTracker 2 Extended Module"));
            fileTypes.Add(new FileTypeData(".xsp", "Kodi Smart Playlist File"));
            fileTypes.Add(new FileTypeData(".zgr", "BeatSlicer Groove File"));
            fileTypes.Add(new FileTypeData(".atrac", "Sony ATRAC Audio File"));
            fileTypes.Add(new FileTypeData(".box", "CARA Loudspeaker Design File"));
            fileTypes.Add(new FileTypeData(".hmi", "HMI Audio File"));
            fileTypes.Add(new FileTypeData(".imf", "Id Music File"));
            fileTypes.Add(new FileTypeData(".sb", "Signed Byte Audio File"));
            fileTypes.Add(new FileTypeData(".sdx", "Sample MIDI Dump Exchange"));
            fileTypes.Add(new FileTypeData(".aax", "Audible Enhanced Audiobook File"));
            fileTypes.Add(new FileTypeData(".cfa", "Adobe Conformed Audio File"));
            fileTypes.Add(new FileTypeData(".mxmf", "Mobile XMF Ringtone File"));
            fileTypes.Add(new FileTypeData(".pac", "SBStudio II Song File"));
            fileTypes.Add(new FileTypeData(".d00", "OPL2 FM Audio File"));
            fileTypes.Add(new FileTypeData(".8svx", "Amiga 8-Bit Sound File"));
            fileTypes.Add(new FileTypeData(".ams", "Extreme Tracker Module"));
            fileTypes.Add(new FileTypeData(".nmsv", "Native Instruments Massive Sound File"));
            fileTypes.Add(new FileTypeData(".msv", "Memory Stick Voice File"));
            fileTypes.Add(new FileTypeData(".xi", "Fasttracker 2 Extended Instrument File"));
            fileTypes.Add(new FileTypeData(".ase", "Velvet Studio Sample"));
            fileTypes.Add(new FileTypeData(".awb", "AMR-WB Audio File"));
            fileTypes.Add(new FileTypeData(".expressionmap", "Cubase Expression Map File"));
            fileTypes.Add(new FileTypeData(".hma", "Sony HI-MD Audio File"));
            fileTypes.Add(new FileTypeData(".mlp", "Meridian Lossless Packing Audio File"));
            fileTypes.Add(new FileTypeData(".mzp", "Mozart Percussion File"));
            fileTypes.Add(new FileTypeData(".sfs", "SFX Sample File"));
            fileTypes.Add(new FileTypeData(".snd", "Akai MPC Sample"));
            fileTypes.Add(new FileTypeData(".tak", "Music Maker Take File"));
            fileTypes.Add(new FileTypeData(".8cm", "Eight Channel Module"));
            fileTypes.Add(new FileTypeData(".gm", "Transport Tycoon Music File"));
            fileTypes.Add(new FileTypeData(".lvp", "Avaya Voice Player Audio File"));
            fileTypes.Add(new FileTypeData(".alac", "ALAC Encoded Audio File"));
            fileTypes.Add(new FileTypeData(".avr", "Audio Visual Research File"));
            fileTypes.Add(new FileTypeData(".bcs", "Sonic Foundry Batch Converter Script"));
            fileTypes.Add(new FileTypeData(".bonk", "Bonk Audio File"));
            fileTypes.Add(new FileTypeData(".cfxr", "Cocoa Sfxr File"));
            fileTypes.Add(new FileTypeData(".dwa", "Digital Waveform Archiver Audio File"));
            fileTypes.Add(new FileTypeData(".evr", "Enhanced Variable Rate Audio File"));
            fileTypes.Add(new FileTypeData(".fda", "Dawn of War Audio File"));
            fileTypes.Add(new FileTypeData(".fff", "Gravis UltraSound Sound Bank"));
            fileTypes.Add(new FileTypeData(".fzb", "Casio FZ-1 Bank Dump"));
            fileTypes.Add(new FileTypeData(".gio", "Adagio Score"));
            fileTypes.Add(new FileTypeData(".gio", "Nyquist MIDI File"));
            fileTypes.Add(new FileTypeData(".gro", "Allegro MIDI File"));
            fileTypes.Add(new FileTypeData(".jo", "jo Audio File"));
            fileTypes.Add(new FileTypeData(".j", "-7z	jo Audio File"));
            fileTypes.Add(new FileTypeData(".kin", "Kinetic Music Project"));
            fileTypes.Add(new FileTypeData(".ksm", "Ken Silverman Music File"));
            fileTypes.Add(new FileTypeData(".ktp", "Kinetic Project Template"));
            fileTypes.Add(new FileTypeData(".minincsf", "NCSF Nintendo DS Audio File"));
            fileTypes.Add(new FileTypeData(".mt9", "MT9 Audio File"));
            fileTypes.Add(new FileTypeData(".musa", "Aleph One Music File"));
            fileTypes.Add(new FileTypeData(".muz", "MUZ Audio File"));
            fileTypes.Add(new FileTypeData(".mwand", "GarageBand MagicMentor Template"));
            fileTypes.Add(new FileTypeData(".mws", "MWave DSP Synth Instrument Extract"));
            fileTypes.Add(new FileTypeData(".nap", "Napster Secured Music File"));
            fileTypes.Add(new FileTypeData(".orc", "Voyetra Digital Orchestrator File"));
            fileTypes.Add(new FileTypeData(".pmpl", "PSBMusic Playlist File"));
            fileTypes.Add(new FileTypeData(".r", "Right Audio Channel File"));
            fileTypes.Add(new FileTypeData(".record", "GarageBand Records Audio File"));
            fileTypes.Add(new FileTypeData(".sdii", "Sound Designer 2 Audio File"));
            fileTypes.Add(new FileTypeData(".seg", "Eragon Audio File"));
            fileTypes.Add(new FileTypeData(".snsf", "Super NES Sound Format File"));
            fileTypes.Add(new FileTypeData(".sth", "SampleTank 2 User Preset Data File"));
            fileTypes.Add(new FileTypeData(".sti", "SampleTank 2 User Preset Data File"));
            fileTypes.Add(new FileTypeData(".stw", "SampleTank 2 User Preset Data File"));
            fileTypes.Add(new FileTypeData(".sw", "Signed Word Audio File"));
            fileTypes.Add(new FileTypeData(".swav", "Nintendo DS Audio File"));
            fileTypes.Add(new FileTypeData(".syn", "Synergy On Air Audio File"));
            fileTypes.Add(new FileTypeData(".tfmx", "Final Music System Tracker Module"));
            fileTypes.Add(new FileTypeData(".tm2", "Theta Music Composer 2.x Audio File"));
            fileTypes.Add(new FileTypeData(".tm8", "Theta Music Composer 1.x Audio File"));
            fileTypes.Add(new FileTypeData(".tmc", "Theta Music Composer 1.x Audio File"));
            fileTypes.Add(new FileTypeData(".ulw", "u-Law Audio File"));
            fileTypes.Add(new FileTypeData(".val", "Olympus Voice Recording"));
            fileTypes.Add(new FileTypeData(".voi", "Voyetra Voice File"));
            fileTypes.Add(new FileTypeData(".wand", "GarageBand Magic Template"));
            fileTypes.Add(new FileTypeData(".xp", "Fastracker 2 Pattern"));


            return fileTypes;
        }
    }
}
